export const DONATE_DETAILS = 'DONATE_DETAILS'
export const CLEAR_DONATE_DETAILS_RESPONSE = 'CLEAR_DONATE_DETAILS_RESPONSE'

export const DONATE_PURCHASE_CREATE = 'DONATE_PURCHASE_CREATE'
export const CLEAR_DONATE_PURCHASE_CREATE_RESPONSE = 'CLEAR_DONATE_PURCHASE_CREATE_RESPONSE'

export const DONATE_PURCHASE_UPDATE = 'DONATE_PURCHASE_UPDATE'
export const CLEAR_DONATE_PURCHASE_UPDATE_RESPONSE = 'CLEAR_DONATE_PURCHASE_UPDATE_RESPONSE'

export const DONATE_PURCHASE = 'DONATE_PURCHASE'
export const CLEAR_DONATE_PURCHASE = 'CLEAR_DONATE_PURCHASE'
