apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: match
  namespace: dev
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - 'curl -X PUT https://matchmanage-dev.beta.crictracker.com/api/match'
            image: curlimages/curl
            name: match
          restartPolicy: OnFailure