apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: redis-to-fantasyarticle
  namespace: dev
spec:
  schedule: "*/60 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - 'curl -X GET https://matchmanage-dev.beta.crictracker.com/api/viewcount/redis-to-fantasyarticle'
            image: curlimages/curl
            name: redis-to-fantasyarticle
          restartPolicy: OnFailure