<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer
 */
/** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer */
?>
<?php
$_objectManager =   \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $_objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<?php $_item = $block->getItem() ?>
<?php $items = $block->getChildren($_item); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $_item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr>
                <td class="col-product"><div class="option-label"><?= /* @escapeNotVerified */ $attributes['option_label'] ?></div></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td class="last">&nbsp;</td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?= (++$_index == $_count && !$_showlastRow) ? ' class="border"' : '' ?>>
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
            <td class="col-product">
                <div class="product-title"><?= $block->escapeHtml($_item->getName()) ?></div>
                <div class="product-sku-block">
                    <span><?= /* @escapeNotVerified */ __('SKU') ?>:</span>
                    <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))) ?>
                </div>
            </td>
        <?php else: ?>
            <td class="col-product"><div class="option-value"><?= $block->getValueHtml($_item) ?></div></td>
        <?php endif; ?>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'price') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-ordered-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Ordered') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getOrderItem()->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getOrderItem()->getQtyInvoiced()): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Invoiced') ?></th>
                            <td><?= /* @escapeNotVerified */ $_item->getOrderItem()->getQtyInvoiced()*1 ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getOrderItem()->getQtyShipped() && $block->isShipmentSeparately($_item)): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Shipped') ?></th>
                            <td><?= /* @escapeNotVerified */ $_item->getOrderItem()->getQtyShipped()*1 ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getOrderItem()->getQtyRefunded()): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Refunded') ?></th>
                            <td><?= /* @escapeNotVerified */ $_item->getOrderItem()->getQtyRefunded()*1 ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getOrderItem()->getQtyCanceled()): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Canceled') ?></th>
                            <td><?= /* @escapeNotVerified */ $_item->getOrderItem()->getQtyCanceled()*1 ?></td>
                        </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($block->isShipmentSeparately($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Ordered') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getOrderItem()->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getOrderItem()->getQtyShipped()): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Shipped') ?></th>
                            <td><?= /* @escapeNotVerified */ $_item->getOrderItem()->getQtyShipped()*1 ?></td>
                        </tr>
                    <?php endif; ?>
                </table>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <?php if ($block->canParentReturnToStock($_item)) : ?>
            <td class="col-return-to-stock">
                <?php if ($block->canShowPriceInfo($_item)): ?>
                    <?php if ($block->canReturnItemToStock($_item)) : ?>
                        <input type="checkbox"
                               class="admin__control-checkbox"
                               name="creditmemo[items][<?= /* @escapeNotVerified */ $_item->getOrderItemId() ?>][back_to_stock]"
                               value="1"<?php if ($_item->getBackToStock()):?> checked="checked"<?php endif;?> />
                        <label class="admin__field-label"></label>
                    <?php endif; ?>
                <?php else: ?>
                    &nbsp;
                <?php endif; ?>
            </td>
        <?php endif; ?>
        <td class="col-refund col-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?php if ($block->canEditQty()) : ?>
                    <input type="text"
                           class="input-text admin__control-text qty-input"
                           name="creditmemo[items][<?= /* @escapeNotVerified */ $_item->getOrderItemId() ?>][qty]"
                           value="<?= /* @escapeNotVerified */ $_item->getQty()*1 ?>" />
                <?php else: ?>
                    <?= /* @escapeNotVerified */ $_item->getQty()*1 ?>
                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'subtotal') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax-amount">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */ $block->displayPriceAttribute('tax_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discont">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */ $block->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <?php if($_item->getOrderItem()->getParentItem()) :?>
            <td class="col-price" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
                <table class="cgst">
                    <tbody style="background:none;text-align:center">
                    <tr>
                        <td style="text-align: center;width: 50px;"><?php echo round($_item->getOrderItem()->getCgstPercent() ? $_item->getOrderItem()->getCgstPercent() : 0,2);?></span></td>
                        <td style="text-align: center;width: 50px;">
                            <?php
                            $formattedPrice = $priceHelper->currency($_item->getOrderItem()->getData('cgst_amount'), true, false);
                            echo $formattedPrice;
                            ?>
                        </td>
                    </tr>
                </table>
            </td>
            <?php
            $sgstUtgstPercent=0;
            $sgstUtgstAmount=0;
            if($_item->getOrderItem()->getSgstPercent()>0){
                $sgstUtgstPercent=$_item->getOrderItem()->getSgstPercent();
                $sgstUtgstAmount=$_item->getOrderItem()->getData('sgst_amount');
            }
            else{
                $sgstUtgstPercent=$_item->getOrderItem()->getUtgstPercent();
                $sgstUtgstAmount=$_item->getOrderItem()->getData('utgst_amount');
            }
            ?>

            <td class="col-price" data-th="<?php echo $block->escapeHtml(__('SGST')); ?>">
                <table class="sgst">
                    <tbody style="background:none;text-align:center">
                    <tr>
                        <td style="text-align: center;width: 50px;"><?php echo round($sgstUtgstPercent ? $sgstUtgstPercent : 0,2);?></span></td>
                        <td style="text-align: center;width: 50px;">
                            <?php
                            $formattedPrice = $priceHelper->currency($sgstUtgstAmount, true, false);
                            echo $formattedPrice;
                            ?>
                        </td>
                    </tr>
                </table>
            </td>
            <td class="col-price" data-th="<?php echo $block->escapeHtml(__('IGST')); ?>">
                <table class="Sgst">
                    <tbody style="background:none;text-align:center">
                    <tr>
                        <td style="text-align: center;width: 50px;"><?php echo round($_item->getOrderItem()->getIgstPercent() ? $_item->getOrderItem()->getIgstPercent() : 0,2);?></span></td>
                        <td style="text-align: center;width: 50px;">
                            <?php
                            $formattedPrice = $priceHelper->currency($_item->getOrderItem()->getData('igst_amount'), true, false);
                            echo $formattedPrice;
                            ?>
                        </td>
                    </tr>
                </table>
            </td>
        <?php endif; ?>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'total') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions($_item->getOrderItem())): ?>
                <dl class="item-options">
                    <?php foreach ($block->getOrderOptions($_item->getOrderItem()) as $option): ?>
                        <dt><?= /* @escapeNotVerified */ $option['label'] ?></dt>
                        <dd>
                            <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                                <?= /* @escapeNotVerified */ $option['value'] ?>
                            <?php else: ?>
                                <?= $block->truncateString($option['value'], 55, '', $_remainder) ?>
                                <?php if ($_remainder):?>
                                    ... <span id="<?= /* @escapeNotVerified */ $_id = 'id' . uniqid() ?>"><?= /* @escapeNotVerified */ $_remainder ?></span>
                                    <script>
                                        require(['prototype'], function(){

                                            $('<?= /* @escapeNotVerified */ $_id ?>').hide();
                                            $('<?= /* @escapeNotVerified */ $_id ?>').up().observe('mouseover', function(){$('<?= /* @escapeNotVerified */ $_id ?>').show();});
                                            $('<?= /* @escapeNotVerified */ $_id ?>').up().observe('mouseout',  function(){$('<?= /* @escapeNotVerified */ $_id ?>').hide();});

                                        });
                                    </script>
                                <?php endif;?>
                            <?php endif;?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
