export const GET_NUU_COINS_TRANSACTION_LIST = 'GET_NUU_COINS_TRANSACTION_LIST'
export const CLEAR_GET_NUU_COINS_TRANSACTION_LIST_RESPONSE = 'CLEAR_GET_NUU_COINS_TRANSACTION_LIST_RESPONSE'

export const NUU_COINS_DETAILS = 'NUU_COINS_DETAILS'
export const CLEAR_NUU_COINS_DETAILS_RESPONSE = 'CLEAR_NUU_COINS_DETAILS_RESPONSE'

export const NUU_COINS_PURCHASE_CREATE = 'NUU_COINS_PURCHASE_CREATE'
export const CLEAR_NUU_COINS_PURCHASE_CREATE_RESPONSE = 'CLEAR_NUU_COINS_PURCHASE_CREATE_RESPONSE'

export const NUU_COINS_PURCHASE_UPDATE = 'NUU_COINS_PURCHASE_UPDATE'
export const CLEAR_NUU_COINS_PURCHASE_UPDATE_RESPONSE = 'CLEAR_NUU_COINS_PURCHASE_UPDATE_RESPONSE'

export const NUU_COINS_PURCHASE = 'NUU_COINS_PURCHASE'
export const CLEAR_NUU_COINS_PURCHASE = 'CLEAR_NUU_COINS_PURCHASE'
