export const allRoutes = {
  home: '/',
  login: '/login',
  signUp: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  explore: '/explore',
  profile: '/profile',
  createAsset: '/create-asset',
  resellCreateAsset: (type, id) => `/resell-asset/${type}/${id}`,
  changePassword: '/change-password',
  setPassword: '/set-password',
  termsAndConditions: '/terms-and-conditions',
  privacyPolicy: '/privacy-policy',
  assetDetails: (id) => `/asset-details/${id}`,
  checkout: (id) => `/checkout/${id}`,
  nuucoins: '/nuucoins',
  donate: '/donate',
  referrals: '/referrals',
  community: '/community',
  resellAssetDetails: (type, id) => `/asset-details/${type}/${id}`,
  profileNested: {
    collected: 'collected',
    created: 'created',
    communities: 'communities',
    private: 'private',
    wishlist: 'wishlist',
    myWallets: 'my-wallets',
    orders: 'orders',
    cardsAndAddresses: 'cards-and-addresses'
  },
  profileCollected: '/profile/collected',
  creatorProfile: '/creator',
  creatorCollected: (id) => `/creator/collected/${id}`,
  creatorCreated: (id) => `/creator/created/${id}`,
  creatorCommunities: (id) => `/creator/communities/${id}`,
  crates: '/crates',
  editProfile: '/edit-profile',
  purchaseNuucoins: '/purchase-nuucoins'
}
