kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: development
  REACT_APP_API_URL: 'https://gateway-stag.crictracker.ml/'
  REACT_APP_S3_PREFIX: 'https://admin-media-cdn.crictracker.com/'