export const ORDER_CREATION = 'ORDER_CREATION'
export const CLEAR_ORDER_CREATION_RESPONSE = 'CLEAR_ORDER_CREATION_RESPONSE'

export const ORDER_UPDATE = 'ORDER_UPDATE'
export const CLEAR_ORDER_UPDATE_RESPONSE = 'CLEAR_ORDER_UPDATE_RESPONSE'

export const ORDER_PAYMENT = 'ORDER_PAYMENT'
export const CLEAR_ORDER_PAYMENT_RESPONSE = 'CLEAR_ORDER_PAYMENT_RESPONSE'

export const PENDING_ORDER = 'PENDING_ORDER'
export const CLEAR_PENDING_ORDER_RESPONSE = 'CLEAR_PENDING_ORDER_RESPONSE'

export const STOCK_AVAILABILITY = 'STOCK_AVAILABILITY'
export const CLEAR_STOCK_AVAILABILITY_RESPONSE = 'CLEAR_STOCK_AVAILABILITY_RESPONSE'

export const REFERRAL_DISCOUNT = 'REFERRAL_DISCOUNT'
export const CLEAR_REFERRAL_DISCOUNT_RESPONSE = 'CLEAR_REFERRAL_DISCOUNT_RESPONSE'
