replicaCount: 2

# image: dockerregistry.fantasywl.tk/fantasy-app-staging:latest
image: 352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-app-staging:latest

namespace: staging

labels:
  tier: frontend
  release: blue-green

pullPolicy: Always

service:
  type: NodePort
  port: 80
  healthcheck: /

resources: 
  requests:
    memory: "50Mi"
    cpu: "20m"
  limits:
    memory: "200Mi"
    cpu: "100m"

livenessProbe:
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  initialDelaySeconds: 5
  timeoutSeconds: 30
readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 30
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  targetCPU: "60"

#Because we are using our private docker registry deployed in Kubernetes if you are using AWS(ECR) than you can disable this.
imagePullSecrets:
  enabled: true
  name: regcred