image: public.ecr.aws/d7h0j7s7/docker:18.09
stages:
  - lint-check
  - sonarqube-check
  - deploy-local-dev
  - deploy-dev
  - deploy-prod
  - rollback-prod

lint-check:
  stage: lint-check
  image: 
    name: public.ecr.aws/d7h0j7s7/node:16-alpine3.11
    # entrypoint: [""]
  script: 
    - npm install
    # - npm install eslint-plugin-react@latest --save-dev
    - npm install -g eslint
    - eslint .
  allow_failure: false
  only:
    - dev

sonarqube-check:
  stage: sonarqube-check
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
    - dev


#crictracker-admin-frontend-local-dev

deploy-local-dev:
  stage: deploy-local-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deployed
    - docker build --build-arg NODE_ENV=development --build-arg REACT_APP_ENV=development --build-arg GLOBAL_WIDGET_BASE_URL=https://globalwidget-dev.crictracker.ml/api --build-arg REACT_APP_API_URL=https://gateway-dev.crictracker.ml/graphql --build-arg REACT_APP_URL_PREFIX=https://cricweb-dev.crictracker.ml/ --build-arg REACT_APP_ADMIN_URL=https://admin-dev.crictracker.ml --build-arg REACT_APP_PLAYLIST_URL=https://article-dev.crictracker.ml/ --build-arg REACT_APP_PREVIEW_URL=https://cricweb-dev.crictracker.ml/article-preview/ --build-arg REACT_APP_S3_PREFIX=https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/ --build-arg REACT_APP_SUBSCRIPTION_URL=wss://subscription-dev.crictracker.ml/graphql --build-arg MATCH_MANAGEMENT_BASE_URL=https://matchmanage.crictracker.com/api -t crictracker-admin-frontend:local-dev_$CI_COMMIT_SHA .
    - docker tag crictracker-admin-frontend:local-dev_$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:local-dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:local-dev_$CI_COMMIT_SHA
    - helm upgrade -n local-dev crictracker-admin-frontend-local-dev crictracker-helmrepo/crictracker-admin-frontend-local-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:local-dev_$CI_COMMIT_SHA
  only:
    - dev
  when: manual 
    
deploy-dev:
  stage: deploy-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  environment: crictracker-prod
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build --build-arg NODE_ENV=development --build-arg REACT_APP_ENV=staging --build-arg GLOBAL_WIDGET_BASE_URL=https://globalwidget-dev.beta.crictracker.com/api --build-arg REACT_APP_API_URL=https://gateway-dev.beta.crictracker.com/graphql --build-arg REACT_APP_URL_PREFIX=https://www.crictracker.com/ --build-arg REACT_APP_ADMIN_URL=https://admin-dev.beta.crictracker.com/ --build-arg REACT_APP_PLAYLIST_URL=https://article-dev.beta.crictracker.com/ --build-arg REACT_APP_PREVIEW_URL=https://cricweb-dev.beta.crictracker.com/article-preview/ --build-arg REACT_APP_S3_PREFIX=https://media.crictracker.com/ --build-arg REACT_APP_SUBSCRIPTION_URL=wss://subscription-dev.beta.crictracker.com/graphql --build-arg MATCH_MANAGEMENT_BASE_URL=https://matchmanage.crictracker.com/api -t crictracker-admin-frontend:dev_$CI_COMMIT_SHA .
    # - docker build -t crictracker-admin-frontend-dev:$CI_COMMIT_SHA .
    - docker tag crictracker-admin-frontend:dev_$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:dev_$CI_COMMIT_SHA
    - helm upgrade -n dev crictracker-admin-frontend-dev crictracker-helmrepo/crictracker-admin-frontend-prod-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:dev_$CI_COMMIT_SHA
  only:
    - dev
  when: manual 


deploy-prod:
  stage: deploy-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build --build-arg NODE_ENV=development --build-arg REACT_APP_ENV=production --build-arg GLOBAL_WIDGET_BASE_URL=https://globalwidget.crictracker.com/api --build-arg REACT_APP_API_URL=https://gateway.crictracker.com/graphql --build-arg REACT_APP_URL_PREFIX=https://www.crictracker.com/ --build-arg REACT_APP_ADMIN_URL=https://admin.crictracker.com/ --build-arg REACT_APP_PLAYLIST_URL=https://article.crictracker.com/ --build-arg REACT_APP_PREVIEW_URL=https://www.crictracker.com/article-preview/ --build-arg REACT_APP_S3_PREFIX=https://media.crictracker.com/ --build-arg REACT_APP_SUBSCRIPTION_URL=wss://subscription.crictracker.com/graphql --build-arg MATCH_MANAGEMENT_BASE_URL=https://matchmanage.crictracker.com/api -t crictracker-admin-frontend:$CI_COMMIT_SHA .
    - docker tag crictracker-admin-frontend:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:$CI_COMMIT_SHA
    - helm upgrade -n production crictracker-admin-frontend-prod crictracker-helmrepo/crictracker-admin-frontend-prod --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-admin-frontend:$CI_COMMIT_SHA
  only:
    - master
  when: manual 

rollback-prod:
  stage: rollback-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    - helm history -n production crictracker-admin-frontend-prod
    - helm rollback -n production crictracker-admin-frontend-prod
    - kubectl rollout status -w deployment/crictracker-admin-frontend-prod -n production
    - helm history -n production crictracker-admin-frontend-prod
  when: manual
  only:
    - master
