kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: "crictracker-redis-local-dev-headless.local-dev.svc.cluster.local"
  REDIS_PORT: "6379"
  NODE_ENV: local-dev
  PORT: "4004"
  SUPPORT_EMAIL: 'Crictracker@yudizproject.tk'
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: 'crictracker-admin-panel-local-dev-08032022'
  S3_BUCKET_URL: 'https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/'
  S3_BUCKET_PROFILE_PATH: profile-pic/
  S3_BUCKET_KYC_PATH: kyc/pan/
  S3_BUCKET_FB_PATH: seo/fb/
  S3_BUCKET_TWITTER_PATH: seo/twitter/
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: media/featureimage/
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: media/thumbnailimage/
  S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH:  media/chatmedia/
  # SEO_SUBGRAPH_URL: 'https://gateway-dev.crictracker.ml/'
  SEO_SUBGRAPH_URL: http://crictracker-seo-local-dev-internal.local-dev.svc.cluster.local/graphql
  # ARTICLE_SUBGRAPH_URL: 'https://article-dev.crictracker.ml'
  ARTICLE_SUBGRAPH_URL: http://crictracker-article-local-dev-internal.local-dev.svc.cluster.local
  SEO_REST_URL: 'https://seo-dev.crictracker.ml/'
  ENTITY_SPORT_BASE_URL: 'https://rest.entitysport.com/v2/' 

  SEO_GRPC_URL: 'crictracker-seo-local-dev-grpc.local-dev.svc.cluster.local:80'
  MATCHMANAGEMENT_GRPC_URL: '0.0.0.0:3004'
  GLOBAL_WIDGET_GRPC_URL: 'crictracker-global-widget-local-dev-grpc.local-dev.svc.cluster.local:80'  