export const ADMIN_GET_ASSETS = 'ADMIN_GET_ASSETS'
export const ADMIN_CLEAR_GET_ASSETS = 'ADMIN_CLEAR_GET_ASSETS'

export const ADMIN_BLOCK_UNBLOCK_ASSET = 'ADMIN_BLOCK_UNBLOCK_ASSET'
export const ADMIN_CLEAR_BLOCK_UNBLOCK_ASSET = 'ADMIN_CLEAR_BLOCK_UNBLOCK_ASSET'
