apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trending-news
  namespace: dev
spec:
  schedule: "*/120 7,23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - 'curl -X GET https://article-dev.beta.crictracker.com/api/trending-news'
            image: curlimages/curl
            name: trending-news
          restartPolicy: OnFailure