export const GET_PUSH_NOTIFICATIONS = 'GET_PUSH_NOTIFICATIONS'
export const CLEAR_GET_PUSH_NOTIFICATIONS_RESPONSE = 'CLEAR_GET_PUSH_NOTIFICATIONS_RESPONSE'
export const INSERT_PUSH_NOTIFICATION = 'INSERT_PUSH_NOTIFICATION'
