kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: "crictracker-redis-local-dev-headless.local-dev.svc.cluster.local"
  REDIS_PORT: "6379"
  NODE_ENV: local-dev
  PORT: "4002"
  SUPPORT_EMAIL: 'Crictracker@yudizproject.tk'
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: 'crictracker-admin-panel-local-dev-08032022'
  S3_BUCKET_URL: 'https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/'
  # S3_BUCKET_PROFILE_PATH: profile-pic/
  # S3_BUCKET_KYC_PATH: kyc/pan
  # S3_BUCKET_FB_PATH: fb/
  # S3_BUCKET_TWITTER_PATH: seo/twitter/
  # S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: media/featureimage
  # S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: media/thumbnailimage
  # S3_BUCKET_ARTICLE_EDITOR_MEDIA_PATH: media/editorimage
  # S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH: media/chatmedia
  # AUTH_SUBGRAPH_URL: 'https://auth-dev.crictracker.ml'
  AUTH_SUBGRAPH_URL: http://crictracker-authentication-local-dev-internal.local-dev.svc.cluster.local
  # SMTP_EMAIL: 'yudizmean@gmail.com'
  YOUTUBE_CLIENT_ID: '443902559106-jn4efqb3phg7houm9qu4h28eg0kb34t3.apps.googleusercontent.com' 
  YOUTUBE_REDIRECT_URI: 'https://article-dev.crictracker.ml/api/oauth2callback'
  YOUTUBE_OAUTH_SCOPE: 'https://www.googleapis.com/auth/youtube.readonly'
  ADMIN_FRONT_REDIRECT_URL: 'https://admin-dev.crictracker.ml/fetch-playlist-success'
  # HOME_PAGE_ID_EVENT: 'homepage-id-event'
  # HOME_PAGE_SLUG_EVENT: 'homepage-slug-event'
  # HOME_PAGE_SLUG_CONSUMER: 'homepage-slug-consumer'
  # HOME_PAGE_ID_CONSUMER: 'homepage-id-consumer'
  # HOME_PAGE_SLUG_GROUP: 'homepage-slug-group'
  # HOME_PAGE_ID_GROUP: 'homepage-id-group'
  # SEO_SUBGRAPH_URL: 'https://seo-dev.crictracker.ml'
  SEO_SUBGRAPH_URL: http://crictracker-seo-local-dev-internal.local-dev.svc.cluster.local

  BASE_SITEMAP: 'sitemap'
  # POST_SITEMAP: 'post-sitemap'
  # CATEGORY_SITEMAP: 'category-sitemap'
  # POST_TAG_SITEMAP: 'post_tag-sitemap'
  # AUTHOR_SITEMAP: 'author-sitemap'
  # SITEMAP_REDIS_KEY: 'sitemap'

  SITEMAP_SLUG_EVENT: 'sitemap-slug-event'
  SITEMAP_SLUG_CONSUMER: 'sitemap-slug-consumer'
  SITEMAP_SLUG_GROUP: 'sitemap-slug-group'
  SITEMAP_ID_EVENT: 'sitemap-id-event'
  SITEMAP_ID_CONSUMER: 'sitemap-id-consumer'
  SITEMAP_ID_GROUP: 'sitemap-id-group'

  CONNECTION: '50'
  MATCH_MANAGEMENT_SUBGRAPH_URL: http://crictracker-matchmanagement-local-dev-internal.local-dev.svc.cluster.local
  SENTRY_DSN: https://4e97d3b1ccdd4779a086215a9d8bbd51@o992135.ingest.sentry.io/6725495
  S3_CDN_URL: https://admin-media-cdn.crictracker.com/
  S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH: media/attachments
  MAX_ALLOW_CLAPS: '5'
  IP_EXPIRE_SEC: '300'
  CREATE_SEO_CONSUMER_0: create-seo-consumer-0
  BOOKMARK_COUNT_UPDATE_EVENT: bookmark-count-update-event
  BOOKMARK_COUNT_UPDATE_CONSUMER: bookmark-count-update-consumer
  BOOKMARK_COUNT_UPDATE_GROUP: bookmark-count-update-group
  HOME_WIDGET_ID_EVENT: home-widget-id-event
  HOME_WIDGET_ID_CONSUMER: home-widget-id-consumer
  HOME_WIDGET_ID_GROUP: home-widget-id-group
  FEED_TITLE: CricTracker
  FEED_DESCRIPTION: Latest Cricket News, Updates, Articles, Stats, Records, Etc
  CREATE_SEO_EVENT: create-seo-event
  ALLOW_DISK_USE: "false"
  S3_BUCKET_VIDEO_PATH: 'video/'
  S3_BUCKET_PLAYLIST_PATH: 'playlist/'

  CREATE_SERIES_SEO_SLUG_GROUP: 'create-series-seo-slug-group'
  CREATE_SERIES_SEO_SLUG_EVENT: 'create-series-seo-slug-event'
  
  INSTANT_ARTICLE_FEED_TITLE: 'INSTANT_ARTICLE_FEED_TITLE'
  
  CREATE_BOOKMARK_FANTASY_ARTICLE_EVENT: 'create-bookmark-fantasy-article-event'
  CREATE_BOOKMARK_FANTASY_ARTICLE_GROUP: 'create-bookmark-fantasy-article-group'

  UPDATE_BOOKMARK_GROUP: 'update-bookmark-group'
  UPDATE_BOOKMARK_CONSUMER_0: 'update-bookmark-consumer'
  UPDATE_BOOKMARK_EVENT: 'update-bookmark-event'

  CREATE_CURRENT_SERIES_EVENT: 'create-current-series-event'
  CREATE_CURRENT_SERIES_GROUP: 'create-current-series-group'
  CREATE_CURRENT_SERIES_CONSUMER: 'create-current-series-consumer'

  CREATE_FILTER_CATEGORY_EVENT: 'create-filter-category-event'
  CREATE_FILTER_CATEGORY_GROUP: 'create-filter-category-group'

  TAG_SERVICE_EVENT: 'tag-service-event'
  TAG_SERVICE_GROUP: 'tag-service-group'
  TAG_SERVICE_CONSUMER_0: 'tag-service-consumer-0'

  CREATE_TAG_EVENT : 'create-tag-event'
  CREATE_TAG_GROUP : 'create-tag-group'
  CREATE_TAG_CONSUMER_0 : 'create-tag-consumer-0'
  CREATE_SEO_GROUP : 'create-seo-group'
  SERIES_CATEGORY_CONSUMER : 'series-category-consumer-0'
  SERIES_CATEGORY_EVENT : 'series-category-event'
  SERIES_CATEGORY_GROUP : 'series-category-group'

  SEO_GRPC_URL: 'crictracker-seo-local-dev-grpc.local-dev.svc.cluster.local:80'
  MATCHMANAGEMENT_GRPC_URL: 'crictracker-matchmanagement-local-dev-grpc.local-dev.svc.cluster.local:80'
  ARTICLE_GRPC_URL: '0.0.0.0:3002'
  BACKEND_URL: 'https://article-dev.crictracker.ml'
  AUTH_GRPC_URL: 'crictracker-authentication-local-dev-grpc.local-dev.svc.cluster.local:80'