export const CLEAR_USER_RESPONSE = 'CLEAR_USER_RESPONSE'
export const GET_USER = 'GET_USER'

export const GET_USER_ASSETS = 'GET_USER_ASSETS'
export const CLEAR_USER_ASSETS_RESPONSE = 'CLEAR_USER_ASSETS_RESPONSE'

export const GET_USER_OWNED_ASSETS = 'GET_USER_OWNED_ASSETS'
export const CLEAR_USER_OWNED_ASSETS_RESPONSE = 'CLEAR_USER_OWNED_ASSETS_RESPONSE'

export const PROFILE_UPDATE = 'UPDATE_USER_PROFILE'
export const CLEAR_PROFILE_UPDATE_RESPONSE = 'CLEAR_PROFILE_UPDATE_RESPONSE'

export const KYC_STATUS_HIDE = 'KYC_STATUS_HIDE'

export const GET_USER_BANK_ACCOUNT_DETAILS = 'GET_USER_BANK_ACCOUNT_DETAILS'
export const CLEAR_USER_BANK_ACCOUNT_DETAILS_RESPONSE = 'CLEAR_USER_BANK_ACCOUNT_DETAILS_RESPONSE'
