const router = require('express').Router()
const testServices = require('./services')
const validators = require('./validators')
const { validate, isStudentAuthenticated } = require('../../../middlewares/middleware')

router.get('/v1/student/test-with-subcategory', isStudentAuthenticated, testServices.getAllTestwithSubcategory)
router.post('/v1/student/question-of-subcategory', isStudentAuthenticated, testServices.getAllQuestions)
router.post('/v1/student/interest-test-questions', isStudentAuthenticated, testServices.getAllInterestTestQuestions)
router.post('/v1/student/interest-test', isStudentAuthenticated, testServices.getAllInterestTest)
router.post('/v1/student/test-subcategory', isStudentAuthenticated, validators.TestSubCategory, validate, testServices.getTestSubCategoryById)
router.post('/v1/student/others-packages', isStudentAuthenticated, testServices.getOtherPackages)
router.post('/v1/student/completed-test', isStudentAuthenticated, testServices.getAllCompletedTest)
router.post('/v1/student/assessment', isStudentAuthenticated, testServices.studentAssessment)
router.post('/v1/student/assessment-report', isStudentAuthenticated, testServices.studentAssessmentReport)
router.get('/v1/student/test-completed-details', isStudentAuthenticated, testServices.getMainTestCompletedDetail)
router.post('/v1/student/question/select-option', isStudentAuthenticated, testServices.updateStudentQuestionOption)
router.post('/v1/student/test/finish', validators.finishTest, validate, isStudentAuthenticated, testServices.studentTestFinish)
router.get('/v1/student/result', validate, isStudentAuthenticated, testServices.studentTestResult)
router.get('/v1/razorpay/pay', testServices.razorpayPayment)
module.exports = router
