image: public.ecr.aws/d7h0j7s7/docker:18.09
stages:
  - lint-check
  - sonarqube-check
  - deploy-local-dev
  - gateway-reload-local-dev
  - deploy-dev
  - gateway-reload-dev
  - deploy-prod
  - gateway-reload-prod
  - gateway-reload-dev-master
  - rollback-prod


lint-check:
  stage: lint-check
  image: 
    name: public.ecr.aws/d7h0j7s7/node:16-alpine3.11
  script: 
    - npm install --legacy-peer-deps
    # - npm install eslint-plugin-react@latest --save-dev
    - npm install -g eslint
    - eslint .
  allow_failure: false
  only:
    - dev

sonarqube-check:
  stage: sonarqube-check
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
    - dev

deploy-local-dev:
  stage: deploy-local-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    # - docker:18.09-dind
    - docker:18.09.7-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:local-dev_$CI_COMMIT_SHA .
    # - docker tag crictracker-matchmanagement-local-dev:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:local-dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:local-dev_$CI_COMMIT_SHA
    - helm upgrade -n local-dev crictracker-matchmanagement-local-dev crictracker-helmrepo/crictracker-matchmanagement-local-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:local-dev_$CI_COMMIT_SHA
    - helm upgrade -n local-dev crictracker-matchmanagement-local-dev-crons crictracker-helmrepo/crictracker-matchmanagement-local-dev-crons --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:local-dev_$CI_COMMIT_SHA
  only:
    - dev

gateway-reload-local-dev:
  stage: gateway-reload-local-dev
  image: public.ecr.aws/d7h0j7s7/node:16.14
  script:
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/supergraph-config-local-dev.yaml --output supergraph-config-local-dev.yaml"
    - npm install -g @apollo/rover
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/mm-gateway-local-dev-realod.sh --output mm-gateway-local-dev-realod.sh"
    - chmod +x mm-gateway-local-dev-realod.sh
    - ./mm-gateway-local-dev-realod.sh
  only:
    - dev

deploy-dev:
  stage: deploy-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  environment: crictracker-prod
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:dev_$CI_COMMIT_SHA .
    # - docker tag crictracker-matchmanagement-dev:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:dev_$CI_COMMIT_SHA
    - helm upgrade -n dev crictracker-matchmanagement-dev crictracker-helmrepo/crictracker-matchmanagement-prod-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:dev_$CI_COMMIT_SHA
    - helm upgrade -n dev crictracker-matchmanagement-dev-crons crictracker-helmrepo/crictracker-matchmanagement-dev-crons-prod-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:dev_$CI_COMMIT_SHA
  allow_failure: true
  only:
    - dev

gateway-reload-dev:
  stage: gateway-reload-dev
  image: public.ecr.aws/d7h0j7s7/node:16.14
  script:
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/supergraph-config-dev.yaml --output supergraph-config-dev.yaml"
    - npm install -g @apollo/rover
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/mm-gateway-dev-realod.sh --output mm-gateway-dev-realod.sh"
    - chmod +x mm-gateway-dev-realod.sh
    - ./mm-gateway-dev-realod.sh
  only:
    - dev

deploy-prod:
  stage: deploy-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t crictracker-matchmanagement:$CI_COMMIT_SHA .
    - docker tag crictracker-matchmanagement:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:$CI_COMMIT_SHA
    - helm upgrade -n production crictracker-matchmanagement-prod crictracker-helmrepo/crictracker-matchmanagement-prod --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:$CI_COMMIT_SHA
    - helm upgrade -n production crictracker-matchmanagement-prod-crons crictracker-helmrepo/crictracker-matchmanagement-prod-crons --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-matchmanagement:$CI_COMMIT_SHA
  only:
    - master
  when: manual

gateway-reload-prod:
  stage: gateway-reload-prod
  image: public.ecr.aws/d7h0j7s7/node:16.14
  script:
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/supergraph-config-prod.yaml --output supergraph-config-prod.yaml"
    - npm install -g @apollo/rover
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/mm-gateway-prod-realod.sh --output mm-gateway-prod-realod.sh"
    - chmod +x mm-gateway-prod-realod.sh
    - ./mm-gateway-prod-realod.sh
  when: manual
  only:
    - master

gateway-reload-dev-master:
  stage: gateway-reload-dev-master
  image: public.ecr.aws/d7h0j7s7/node:16.14
  script:
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/supergraph-config-dev.yaml --output supergraph-config-dev.yaml"
    - npm install -g @apollo/rover
    - "curl https://crictracker-gateway-configfile.s3.ap-south-1.amazonaws.com/mm-gateway-dev-realod.sh --output mm-gateway-dev-realod.sh"
    - chmod +x mm-gateway-dev-realod.sh
    - ./mm-gateway-dev-realod.sh
  only:
    - master
  when: manual

#crictracker-matchmanagement-prod

rollback-prod:
  stage: rollback-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    - helm history -n production crictracker-matchmanagement-prod
    - helm rollback -n production crictracker-matchmanagement-prod
    - kubectl rollout status -w deployment/crictracker-matchmanagement-prod
    - helm history -n production crictracker-matchmanagement-prod
  when: manual
  only:
    - master
