export const GET_ADDRESS = 'GET_ADDRESS'
export const CLEAR_GET_ADDRESSES_RESPONSE = 'CLEAR_GET_ADDRESSES_RESPONSE'

export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const CLEAR_UPDATE_ADDRESS_RESPONSE = 'CLEAR_UPDATE_ADDRESS_RESPONSE'

export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const CLEAR_DELETE_ADDRESS_RESPONSE = 'CLEAR_DELETE_ADDRESS_RESPONSE'

export const ADD_ADDRESS = 'ADD_ADDRESS'
export const CLEAR_ADD_ADDRESS_RESPONSE = 'CLEAR_ADD_ADDRESS_RESPONSE'
