kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: development
  REACT_APP_API_URL: 'https://gateway.crictracker.com/'
  REACT_APP_S3_PREFIX: 'https://media.crictracker.com/'