apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-efs-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: jenkins-sc
  resources:
    requests:
      storage: 5Gi
