apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: local-dev
  name: local-dev-read-only
rules:
- apiGroups: [""]
  verbs: ["get", "watch", "list", "create"]
  resources:
  - pods
  - pods/log
  - pods/exec
  - pods/portforward
  - services
  - services/portforward
