apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only-dev
rules:
- apiGroups: [""]
  resources: ["pods","pods/log","pods/exec","pods/portforward"]
  verbs: ["get","watch","list","create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list"]
- apiGroups: [""]
  resources: ["services","services/portforward"]
  verbs: ["get","watch","list","create"]