export const GET_DROP_LIST = 'GET_DROP_LIST'
export const CLEAR_GET_DROP_LIST_RESPONSE = 'CLEAR_GET_DROP_LIST_RESPONSE'

export const CREATE_DROP = 'CREATE_DROP'
export const CLEAR_CREATE_DROP_RESPONSE = 'CLEAR_CREATE_DROP_RESPONSE'

export const UPDATE_DROP = 'UPDATE_DROP'
export const CLEAR_UPDATE_DROP_RESPONSE = 'CLEAR_UPDATE_DROP_RESPONSE'

export const GET_DROP_ASSETS = 'GET_DROP_ASSETS'
export const CLEAR_GET_DROP_ASSETS_RESPONSE = 'CLEAR_GET_DROP_ASSETS_RESPONSE'
