image: public.ecr.aws/d7h0j7s7/docker:stable
stages:
  - lint-check
  - deploy-local-dev
  - deploy-dev
  - deploy-prod
  - rollback-prod

lint-check:
  stage: lint-check
  image: 
    name: public.ecr.aws/d7h0j7s7/node:16-alpine3.11
  script: 
    - npm install
    # - npm install eslint-plugin-react@latest --save-dev
    - npm install -g eslint
    - eslint .
  allow_failure: false
  only:
    - dev

deploy-local-dev:
  stage: deploy-local-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:local-dev_$CI_COMMIT_SHA .
    # - docker tag crictracker-subscription-local-dev:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:local-dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:local-dev_$CI_COMMIT_SHA
    - helm upgrade -n local-dev crictracker-subscription-local-dev crictracker-helmrepo/crictracker-subscription-local-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:local-dev_$CI_COMMIT_SHA
  only:
    - dev

deploy-dev:
  stage: deploy-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  environment: crictracker-prod
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    - docker build -t 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:dev_$CI_COMMIT_SHA .
    # - docker tag crictracker-subscription-dev:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:dev_$CI_COMMIT_SHA
    - helm upgrade -n dev crictracker-subscription-dev crictracker-helmrepo/crictracker-subscription-prod-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:dev_$CI_COMMIT_SHA
  only:
    - dev

deploy-prod:
  stage: deploy-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t crictracker-subscription:$CI_COMMIT_SHA .
    - docker tag crictracker-subscription:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:$CI_COMMIT_SHA
    - helm upgrade -n production crictracker-subscription-prod crictracker-helmrepo/crictracker-subscription-prod --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-subscription:$CI_COMMIT_SHA
  only:
    - master
  when: manual

rollback-prod:
  stage: rollback-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    - helm history -n production crictracker-subscription-prod
    - helm rollback -n production crictracker-subscription-prod
    - kubectl rollout status -w deployment/crictracker-subscription-prod
    - helm history -n production crictracker-subscription-prod
  when: manual
  only:
    - master
