apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}
  labels:
    release: {{ .Values.labels.release }}
    app: {{ .Release.Name }}
    environment: {{ .Values.labels.environment }}
    tier: {{ .Values.labels.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecrets.enabled }} 
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      terminationGracePeriodSeconds: 50
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 20"]
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.service.healthcheck }}
            port: {{ .Values.service.port }}
            scheme: HTTP
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.service.healthcheck }}
            port: {{ .Values.service.port }}
            scheme: HTTP
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: JWT_SECRET

          - name: AWS_ACCESSKEYID
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: AWS_ACCESSKEYID

          - name: AWS_SECRETKEY
            valueFrom:
              secretKeyRef:
                name: aws-secrets
                key: AWS_SECRETKEY

          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: SEO_DB_URL

          # configmaps      
                
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: NODE_ENV       

          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: PORT

          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: REDIS_HOST      

          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: REDIS_PORT    

          - name: SUPPORT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SUPPORT_EMAIL       

          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: AWS_REGION

          - name: S3_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_NAME

          - name: S3_BUCKET_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_URL
           
          - name: S3_BUCKET_PROFILE_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_PROFILE_PATH

          - name: S3_BUCKET_KYC_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_KYC_PATH

          - name: S3_BUCKET_FB_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_FB_PATH

          - name: S3_BUCKET_TWITTER_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_TWITTER_PATH

          - name: S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH

          - name: S3_BUCKET_ARTICLE_THUMBIMAGE_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_ARTICLE_THUMBIMAGE_PATH

          - name: S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH

          - name: AUTH_SUBGRAPH_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: AUTH_SUBGRAPH_URL
              
          - name: HOME_PAGE_ID_EVENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: HOME_PAGE_ID_EVENT

          - name: HOME_PAGE_SLUG_EVENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: HOME_PAGE_SLUG_EVENT

          - name: HOME_PAGE_SLUG_CONSUMER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: HOME_PAGE_SLUG_CONSUMER

          - name: HOME_PAGE_ID_CONSUMER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: HOME_PAGE_ID_CONSUMER

          - name: HOME_PAGE_SLUG_GROUP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: HOME_PAGE_SLUG_GROUP

          - name: HOME_PAGE_ID_GROUP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: HOME_PAGE_ID_GROUP

          - name: SEO_STATUS_CHANGE_EVENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SEO_STATUS_CHANGE_EVENT

          - name: SEO_STATUS_CHANGE_CONSUMER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SEO_STATUS_CHANGE_CONSUMER

          - name: SEO_STATUS_CHANGE_GROUP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SEO_STATUS_CHANGE_GROUP

          - name: BASE_SITEMAP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: BASE_SITEMAP

          - name: POST_SITEMAP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: POST_SITEMAP

          - name: CATEGORY_SITEMAP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: CATEGORY_SITEMAP

          - name: POST_TAG_SITEMAP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: POST_TAG_SITEMAP

          - name: AUTHOR_SITEMAP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: AUTHOR_SITEMAP

          - name: SITEMAP_REDIS_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SITEMAP_REDIS_KEY

          - name: SITEMAP_SLUG_EVENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SITEMAP_SLUG_EVENT

          - name: SITEMAP_SLUG_CONSUMER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SITEMAP_SLUG_CONSUMER

          - name: SITEMAP_SLUG_GROUP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SITEMAP_SLUG_GROUP

          - name: SITEMAP_ID_EVENT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SITEMAP_ID_EVENT
            
          - name: SITEMAP_ID_CONSUMER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SITEMAP_ID_CONSUMER

          - name: SITEMAP_ID_GROUP
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SITEMAP_ID_GROUP
          
          - name: SEO_GRPC_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: SEO_GRPC_URL                 