image: docker:stable
stages:
  - sonar-scanner
  - build_prod
  - build_stag
  - build_dev
  - sportgully-stag
  - sportgully-prod
  - gullysport-prod
  - rollback-dev
  - rollback-stag
  - rollback-prod
  - rollback-sportgully-stag
  - rollback-sportgully-prod

sonarqube-check:
  stage: sonar-scanner
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task 
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - staging
    #- master
    #- develop

# build_prod:
#   stage: build_prod
#   image: jaydobariya/gitlab-ci:latestv1
#   services:
#     - docker:18.09-dind
#   variables:
#       DOCKER_HOST: tcp://localhost:2375
#       DOCKER_DRIVER: overlay2
#   before_script:
#     - aws eks --region ap-south-1 update-kubeconfig --name Fansportiz
#     - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
#     - helm repo update
#   script:
#     - docker build --build-arg REACT_APP_ENVIRONMENT=production --build-arg REACT_APP_AXIOS_BASE_URL_PROD='https://nodeback.fantasywl.in/api/admin' --build-arg REACT_APP_NODE_AXIOS_BASE_URL_PROD='https://node.fantasywl.in/api/admin' -t fantasy-admin-panel:$CI_COMMIT_SHA .
#     - docker tag fantasy-admin-panel:$CI_COMMIT_SHA 352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel:$CI_COMMIT_SHA
#     - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 352650027354.dkr.ecr.ap-south-1.amazonaws.com
#     - docker push 352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel:$CI_COMMIT_SHA
#     - helm upgrade -n production fantasy-admin-panel project-1/fantasy-admin-panel --set=image=352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel:$CI_COMMIT_SHA
#     - kubectl rollout status -w deployment/fantasy-admin-panel -n production
#   when: manual
#   only:
#     - master

# build_stag:
#   stage: build_stag
#   image: jaydobariya/gitlab-ci:latestv1
#   services:
#     - docker:18.09-dind
#   variables:
#       DOCKER_HOST: tcp://localhost:2375
#       DOCKER_DRIVER: overlay2
#   before_script:
#     - aws eks --region ap-south-1 update-kubeconfig --name Fansportiz
#     - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
#     - helm repo update
#   script:
#     #deploy
#     - docker build --build-arg REACT_APP_ENVIRONMENT=staging --build-arg REACT_APP_AXIOS_BASE_URL_STAG='https://nodebackstag.fantasywl.in/api/admin' --build-arg REACT_APP_NODE_AXIOS_BASE_URL_STAG='https://nodestag.fantasywl.in/api/admin' -t fantasy-admin-panel-staging:$CI_COMMIT_SHA .
#     - docker tag fantasy-admin-panel-staging:$CI_COMMIT_SHA 352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel-staging:$CI_COMMIT_SHA
#     - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 352650027354.dkr.ecr.ap-south-1.amazonaws.com
#     - docker push 352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel-staging:$CI_COMMIT_SHA
#     - helm upgrade -n default fantasy-admin-panel-stag project-1/fantasy-admin-panel-stag --set=image=352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel-staging:$CI_COMMIT_SHA
#     - kubectl rollout status -w deployment/fantasy-admin-panel-stag -n staging
#   only:
#     - staging

# build_dev:
#   stage: build_dev
#   image: jaydobariya/gitlab-ci:latestv1
#   services:
#     - docker:18.09-dind
#   variables:
#       DOCKER_HOST: tcp://localhost:2375
#       DOCKER_DRIVER: overlay2
#   before_script:
#     - aws eks --region ap-south-1 update-kubeconfig --name Fansportiz
#     - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
#     - helm repo update
#   script:
#     #deploy
#     - docker build --build-arg REACT_APP_ENVIRONMENT=development --build-arg REACT_APP_AXIOS_BASE_URL_DEV='https://nodeback-dev.fantasywl.in/api/admin' --build-arg REACT_APP_NODE_AXIOS_BASE_URL_DEV='https://node-dev.fantasywl.in/api/admin' -t fantasy-admin-panel-dev:$CI_COMMIT_SHA .
#     - docker tag fantasy-admin-panel-dev:$CI_COMMIT_SHA 352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel-dev:$CI_COMMIT_SHA
#     - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 352650027354.dkr.ecr.ap-south-1.amazonaws.com
#     - docker push 352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel-dev:$CI_COMMIT_SHA
#     - helm upgrade -n default fantasy-admin-panel-dev project-1/fantasy-admin-panel-dev --set=image=352650027354.dkr.ecr.ap-south-1.amazonaws.com/fantasy-admin-panel-dev:$CI_COMMIT_SHA
#     - kubectl rollout status -w deployment/fantasy-admin-panel-dev -n dev
#   only:
#     - dev

sportgully-stag :
  stage: sportgully-stag 
  image: jaydobariya/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$SPORTGULLY_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$SPORTGULLY_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$SPORTGULLY_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name sportgully
    - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build --build-arg REACT_APP_ENVIRONMENT=staging --build-arg REACT_APP_AXIOS_BASE_URL_STAG='https://apiv2.beta.sportgully.com/api/admin' --build-arg REACT_APP_NODE_AXIOS_BASE_URL_STAG='https://lf.beta.sportgully.com/api/admin' -t sportgully-admin-panel-stag:$CI_COMMIT_SHA .
    - docker tag sportgully-admin-panel-stag:$CI_COMMIT_SHA 818619633648.dkr.ecr.ap-south-1.amazonaws.com/sportgully-admin-panel-stag:$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 818619633648.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 818619633648.dkr.ecr.ap-south-1.amazonaws.com/sportgully-admin-panel-stag:$CI_COMMIT_SHA
    - helm upgrade -n staging sportgully-admin-panel-stag project-1/sportgully-admin-panel-stag --set=image=818619633648.dkr.ecr.ap-south-1.amazonaws.com/sportgully-admin-panel-stag:$CI_COMMIT_SHA
    - kubectl rollout status -w deployment/sportgully-admin-panel-stag -n staging
  only:
    - sportgully-stag

sportgully-prod:
  stage: sportgully-prod
  image: jaydobariya/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$SPORTGULLY_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$SPORTGULLY_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$SPORTGULLY_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name sportgully
    - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build --build-arg REACT_APP_ENVIRONMENT=production --build-arg REACT_APP_AXIOS_BASE_URL_PROD='https://apiv2.sportgully.com/api/admin' --build-arg REACT_APP_NODE_AXIOS_BASE_URL_PROD='https://lf.sportgully.com/api/admin' -t sportgully-admin-panel:$CI_COMMIT_SHA .
    - docker tag sportgully-admin-panel:$CI_COMMIT_SHA 818619633648.dkr.ecr.ap-south-1.amazonaws.com/sportgully-admin-panel:$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 818619633648.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 818619633648.dkr.ecr.ap-south-1.amazonaws.com/sportgully-admin-panel:$CI_COMMIT_SHA
    - helm upgrade -n production sportgully-admin-panel project-1/sportgully-admin-panel --set=image=818619633648.dkr.ecr.ap-south-1.amazonaws.com/sportgully-admin-panel:$CI_COMMIT_SHA
    - kubectl rollout status -w deployment/sportgully-admin-panel -n production
  when: manual
  only:
    - sportgully-prod

rollback-dev:
  stage: rollback-dev
  image: jaydobariya/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - aws eks --region ap-south-1 update-kubeconfig --name Fansportiz
    - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
    - helm repo update
  script:
    - helm history -n default fantasy-admin-panel-dev
    - helm rollback -n default fantasy-admin-panel-dev
    - kubectl rollout status -w deployment/fantasy-admin-panel-dev -n dev
    - helm history -n default fantasy-admin-panel-dev
  when: manual
  only:
    - dev

rollback-stag:
  stage: rollback-stag
  image: jaydobariya/gitlab-ci:latestv1
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - aws eks --region ap-south-1 update-kubeconfig --name Fansportiz
    - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
    - helm repo update
  script:
    - helm history -n default fantasy-admin-panel-stag
    - helm rollback -n default fantasy-admin-panel-stag
    - kubectl rollout status -w deployment/fantasy-admin-panel-stag -n staging
    - helm history -n default fantasy-admin-panel-stag
  when: manual
  only:
    - staging

rollback-prod:
  stage: rollback-prod
  image: jaydobariya/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - aws eks --region ap-south-1 update-kubeconfig --name Fansportiz
    - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
    - helm repo update
  script:
    - helm history -n production fantasy-admin-panel
    - helm rollback -n production fantasy-admin-panel
    - kubectl rollout status -w deployment/fantasy-admin-panel -n production
    - helm history -n production fantasy-admin-panel
  when: manual
  only:
    - master

rollback-sportgully-stag:
  stage: rollback-sportgully-stag
  image: jaydobariya/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$SPORTGULLY_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$SPORTGULLY_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$SPORTGULLY_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name sportgully
    - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
    - helm repo update
  script:
    - helm history -n staging sportgully-admin-panel-stag
    - helm rollback -n staging sportgully-admin-panel-stag
    - kubectl rollout status -w deployment/sportgully-admin-panel-stag -n staging
    - helm history -n staging sportgully-admin-panel-stag
  when: manual
  only:
    - sportgully-stag

rollback-sportgully-prod:
  stage: rollback-sportgully-prod
  image: jaydobariya/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$SPORTGULLY_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$SPORTGULLY_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$SPORTGULLY_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name sportgully
    - helm repo add --username yudiz_AmanM --password 35xYz5xqobP5xQFgAnqQ project-1 https://gitlab.com/api/v4/projects/28916807/packages/helm/stable
    - helm repo update
  script:
    - helm history -n production sportgully-admin-panel
    - helm rollback -n production sportgully-admin-panel
    - kubectl rollout status -w deployment/sportgully-admin-panel -n production
    - helm history -n production sportgully-admin-panel
  when: manual
  only:
    - sportgully-prod
