if (!process.env.NODE_ENV) process.env.NODE_ENV = 'dev'
const ENV = process.env.NODE_ENV

const dev = {
  DB_URL: process.env.DB_URL || 'mongodb+srv://brijesh_1116:mLab17@mycluster0.xnamd.mongodb.net/crictracker-auth-dev?authSource=admin&replicaSet=myCluster0-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true',
  JWT_SECRET: process.env.JWT_SECRET || 'crictracker',
  CONNECTION: parseInt(process.env.CONNECTION) || 10,
  PRIVATE_KEY: process.env.PRIVATE_KEY || '-----BEGIN RSA PRIVATE KEY-----MIIJKQIBAAKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQKCAgBj6XnsIfwdHnnLvL+DRHfVOTP+EV9153/Gd5ib2huhVoqw2ZGU1K92xrJ5FGEAxWeIUwLjVaZHXVvs/nVzjKQyacaZjtaMgHZH7tls9nanW9q5wdA9thmElHvwSNMlepg5OZV2sbke/MOmt2k6UvyFooWHAjit4zP5Sg0UTSsgAl91sRKZwOdsy4UjXoLsH6klMI8IeFIEsckHXR+v2n373ZekOqETlyLUht4MWo+iacoeVqw0JQrxfdBxH3OokJfS9+ieN7HEDCI2vukGQC4stasicAn48O09GiypQa551cnSS51k3zpsIDsQdGJQ/exEQpQzxIIyArYbwizAtmAeJTkbz7S2vitBSnECmxbwZmQgV/V3LdpZQ6UITgmZnoqHnfmtMj1rJUSILOxNEVATmzS2Yf1GHM3O8ChKRfrTstPA9n7Y3nSTSmGrk/sn9LDa75q51SvYs6SBWALDzqtK15mz4lTpfb13n8hRlEvWJwREq0P2/SYWmGuNacB0xrfeRdnqwyFPLDslNo8zD9wL8n5Jiz2WrxILohDSJ7npLu9dkkqYIKwGFmrejPCHR0EHwA1sdHDoM1/m2ux0d0rzyKb5LYs9t91mdV1XGzTuFGuxnHEOcveEJsrDqiainfXZdmLrcqi6/Gk9DKPCyT+nUnRl7+DPU83mqLQOIQUMAQKCAQEA5Q5r9IQuqK/IiP4/HfLNtEMwAYvKFFzWP1L80RmCSuzMoB6bSY3fWuXA4AEVQkfjAprSIvnByjMnsayGpfeR02NlLeyxGqpxcyZHt2hgemk9H6RUl5fIC4slu1W3lBRoL4Sps6qdyx74IMZMqANsC+f8eYeF+JigoKkLajLVzpAY+XU12AkBdokjBCVScLc84UDI3UXacxuS0dhAKhggRaPNMHY6pKel0wvek3olxDxlLjb6DuTEEa5Z0EVQ4qhx7aobFBQmp4+wjVb2re2G5FhnGJfh6/t/6QrTOYjGKiPiMSJZjqizQO9I1bSQp/oJ8/0W6Z/htOffibD83FRbgQKCAQEA4E332PHgegfXEMDab5Hk5+y9riQ7nfeSTgTT0W9hjbjdoXtgcUgQ8S9Pu9Fd+rTVW6RQM2OJ2DVjf6Eu98PYzlGxoL0DeejCFWU/WnrtpkjE6zvkbBLcNtgKkV6OfEhfQzk5/p+cGtjcV80P1YkkIQ9EBUHzyk6IDq9Ok4JWyTIS6PdL53r81a+ub+pQlW53YrJQRXRXnUEnM1xhZhH2AivuIRGuvdVzPPiZfLYd7TANDrQnmeByp2QRJwkT1FVe6MAaR2q3j7piBIbfvmtxNPzYl2HWlyxvEniGRDQbAkMmuIv+7+NYxD/d3EpTrt0AiCe6CckPJNOZkhpXQgU69QKCAQEApj8XX3romooq1DMkAEqPvjvdheG9o5XV8lP7JpCLHnJL+hL8xh/wcnq6yFpA4cBnJSbVSYlYe7cxIiWD/MV406Iad4CI8j+u49JuztE05OOo92Q/+V6yVJ6DnjoSaal+DK8OtFYq/JfXo4IJdRA2xVV0y4fvVoUAYFsQ691FjQzM85F8qPWwWCYkggfMk/6KczqgDul6KX1jzGZV+7dTBPhkHr5Qxdzf4BOHUiafbpQfI7HHQDQNkn+mtCD7GecD+WkzChmuDIOfspXhqE7zTpxTB2iFEs+RAMVYlTOOEFvG+b5incYXhBOoG2NYcnJp8upITPw7xx9cAQWyIQAhAQKCAQEAt/IYzFfnoAun6nxNZmu9zhjOoO3j2jL6T3MUBlASL3gogVI9kAjqo/AJslwLdxsvUX0ZrFr341A9LaCQdO2ucdx7D/eRzzr7VzJ11wyyschBfSvbsmlxIKThXb+ul+t9/BIFJnPcQAQSBwsK7jIOZ/It9SXV+NWYLHrFtKCR7WNcMKMFI2svx0nQgsUkmrdBvrW+sIathy+0JyGeWmdmWPePzJzEsbdHTvwMW0K6nhXmz2UciMuRGwcsLdf65Amy0Kshoem5aWwPD+lPuchAyZSFRvgcVFNDL2GZsnsMnzlUmslsI2xNEnvRxONLZz6kPgReQ8IX4jqJWVCyuFiztQKCAQBYCfBrzQjxpSw+Cof981HIPjSz479dPvoulobzWqKyyIE/qOsn+WOFvF6PaamiDoFn+JHATuzcSHXCu97A+3AMS5ileqkoSF7ua7dEETGlQCNdn0V2BhAmnmzw8hlo5pS8ljcGSuWWbs/F+BOOfkGyIiVxBHsNm0X5EVFcLskSofcg8ssxMdYlObnAXWN84jnWxfBVnDMOqPyQVh67Taz+Bck1L0ibUx46v+IJACmKljVzWItb0pftBgvKiS441wcGz+tb6h2XMVKYNMjBCiAJwnIacbSCUPq/vlJnoq6zE2zV3kl16lzLeFNX5pbX3xLTncqaOfBp10L7DyEV6PqX-----END RSA PRIVATE KEY-----',
  PUBLIC_KEY: process.env.PUBLIC_KEY || '-----BEGIN PUBLIC KEY-----MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQ==-----END PUBLIC KEY-----',
  REDIS_HOST: process.env.REDIS_HOST || '127.0.0.1',
  REDIS_PORT: process.env.REDIS_PORT || 6379,
  NODE_ENV: process.env.NODE_ENV || 'dev',
  PORT: process.env.PORT || 4001,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL || 'Crictracker@yudizproject.tk',
  AWS_ACCESSKEYID: process.env.AWS_ACCESSKEYID || 'AKIAVEG4UMFNJUU4K6N5',
  AWS_SECRETKEY: process.env.AWS_SECRETKEY || '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',
  AWS_REGION: process.env.AWS_REGION || 'ap-south-1',
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || 'crictracker-admin-panel',
  S3_BUCKET_PROFILE_PATH: process.env.S3_BUCKET_PROFILE_PATH || 'profile-pic/',
  S3_BUCKET_KYC_PATH: process.env.S3_BUCKET_KYC_PATH || 'kyc/pan/',
  S3_BUCKET_BANK_PATH: process.env.S3_BUCKET_BANK_PATH || 'kyc/bank/',
  S3_BUCKET_FB_PATH: process.env.S3_BUCKET_FB_PATH || 'fb/',
  S3_BUCKET_TWITTER_PATH: process.env.S3_BUCKET_TWITTER_PATH || 'twitter/',
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH || 'media/featureimage',
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_THUMBIMAGE_PATH || 'media/thumbnailimage',
  S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH: process.env.S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH || 'media/chatmedia',
  S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH || 'media/attachments/',
  S3_BUCKET_TEAM_PATH: process.env.S3_BUCKET_ARTICLE_EDITOR_MEDIA_PATH || 'team/',
  S3_BUCKET_PLAYER_PATH: process.env.S3_BUCKET_PLAYER_PATH || 'player/',
  S3_BUCKET_CATEGORY_PATH: process.env.S3_BUCKET_CATEGORY_PATH || 'category/',
  S3_BUCKET_SIDEMENU_PATH: process.env.S3_BUCKET_SIDEMENU_PATH || 'sidemenu/',
  SMTP_EMAIL: process.env.SMTP_EMAIL || 'yudizmean@gmail.com',
  SMTP_PASSWORD: process.env.SMTP_PASSWORD || 'Yudiz@321',
  POSTMARK_SERVER_CLIENT: process.env.POSTMARK_SERVER_CLIENT || '',
  SENTRY_DSN: process.env.SENTRY_DSN || 'https://c4d6413db2ab401fa354fd66a24810a2@o992135.ingest.sentry.io/5949470',
  BOOKMARK_COUNT_UPDATE_EVENT: process.env.BOOKMARK_COUNT_UPDATE_EVENT || 'bookmark-count-update-event',
  BOOKMARK_COUNT_UPDATE_CONSUMER: process.env.BOOKMARK_COUNT_UPDATE_CONSUMER || 'bookmark-count-update-consumer',
  BOOKMARK_COUNT_UPDATE_GROUP: process.env.BOOKMARK_COUNT_UPDATE_GROUP || 'bookmark-count-update-group',
  S3_BUCKET_URL: process.env.S3_BUCKET_URL || 'https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/',
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '1596294133114-4dbktn77eg9vcn4esek3vpapvg6look9.apps.googleusercontent.com',
  authGrpcUrl: process.env.AUTH_GRPC_URL || '0.0.0.0:2001',
  KEEP_ALIVE_TIMEOUT: process.env.KEEP_ALIVE_TIMEOUT || 65000
}

const stag = {
  DB_URL: process.env.DB_URL || 'mongodb+srv://brijesh_1116:mLab17@mycluster0.xnamd.mongodb.net/crictracker-auth-dev?authSource=admin&replicaSet=myCluster0-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true',
  CONNECTION: parseInt(process.env.CONNECTION) || 10,
  JWT_SECRET: process.env.JWT_SECRET || 'crictracker',
  PRIVATE_KEY: process.env.PRIVATE_KEY || '-----BEGIN RSA PRIVATE KEY-----MIIJKQIBAAKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQKCAgBj6XnsIfwdHnnLvL+DRHfVOTP+EV9153/Gd5ib2huhVoqw2ZGU1K92xrJ5FGEAxWeIUwLjVaZHXVvs/nVzjKQyacaZjtaMgHZH7tls9nanW9q5wdA9thmElHvwSNMlepg5OZV2sbke/MOmt2k6UvyFooWHAjit4zP5Sg0UTSsgAl91sRKZwOdsy4UjXoLsH6klMI8IeFIEsckHXR+v2n373ZekOqETlyLUht4MWo+iacoeVqw0JQrxfdBxH3OokJfS9+ieN7HEDCI2vukGQC4stasicAn48O09GiypQa551cnSS51k3zpsIDsQdGJQ/exEQpQzxIIyArYbwizAtmAeJTkbz7S2vitBSnECmxbwZmQgV/V3LdpZQ6UITgmZnoqHnfmtMj1rJUSILOxNEVATmzS2Yf1GHM3O8ChKRfrTstPA9n7Y3nSTSmGrk/sn9LDa75q51SvYs6SBWALDzqtK15mz4lTpfb13n8hRlEvWJwREq0P2/SYWmGuNacB0xrfeRdnqwyFPLDslNo8zD9wL8n5Jiz2WrxILohDSJ7npLu9dkkqYIKwGFmrejPCHR0EHwA1sdHDoM1/m2ux0d0rzyKb5LYs9t91mdV1XGzTuFGuxnHEOcveEJsrDqiainfXZdmLrcqi6/Gk9DKPCyT+nUnRl7+DPU83mqLQOIQUMAQKCAQEA5Q5r9IQuqK/IiP4/HfLNtEMwAYvKFFzWP1L80RmCSuzMoB6bSY3fWuXA4AEVQkfjAprSIvnByjMnsayGpfeR02NlLeyxGqpxcyZHt2hgemk9H6RUl5fIC4slu1W3lBRoL4Sps6qdyx74IMZMqANsC+f8eYeF+JigoKkLajLVzpAY+XU12AkBdokjBCVScLc84UDI3UXacxuS0dhAKhggRaPNMHY6pKel0wvek3olxDxlLjb6DuTEEa5Z0EVQ4qhx7aobFBQmp4+wjVb2re2G5FhnGJfh6/t/6QrTOYjGKiPiMSJZjqizQO9I1bSQp/oJ8/0W6Z/htOffibD83FRbgQKCAQEA4E332PHgegfXEMDab5Hk5+y9riQ7nfeSTgTT0W9hjbjdoXtgcUgQ8S9Pu9Fd+rTVW6RQM2OJ2DVjf6Eu98PYzlGxoL0DeejCFWU/WnrtpkjE6zvkbBLcNtgKkV6OfEhfQzk5/p+cGtjcV80P1YkkIQ9EBUHzyk6IDq9Ok4JWyTIS6PdL53r81a+ub+pQlW53YrJQRXRXnUEnM1xhZhH2AivuIRGuvdVzPPiZfLYd7TANDrQnmeByp2QRJwkT1FVe6MAaR2q3j7piBIbfvmtxNPzYl2HWlyxvEniGRDQbAkMmuIv+7+NYxD/d3EpTrt0AiCe6CckPJNOZkhpXQgU69QKCAQEApj8XX3romooq1DMkAEqPvjvdheG9o5XV8lP7JpCLHnJL+hL8xh/wcnq6yFpA4cBnJSbVSYlYe7cxIiWD/MV406Iad4CI8j+u49JuztE05OOo92Q/+V6yVJ6DnjoSaal+DK8OtFYq/JfXo4IJdRA2xVV0y4fvVoUAYFsQ691FjQzM85F8qPWwWCYkggfMk/6KczqgDul6KX1jzGZV+7dTBPhkHr5Qxdzf4BOHUiafbpQfI7HHQDQNkn+mtCD7GecD+WkzChmuDIOfspXhqE7zTpxTB2iFEs+RAMVYlTOOEFvG+b5incYXhBOoG2NYcnJp8upITPw7xx9cAQWyIQAhAQKCAQEAt/IYzFfnoAun6nxNZmu9zhjOoO3j2jL6T3MUBlASL3gogVI9kAjqo/AJslwLdxsvUX0ZrFr341A9LaCQdO2ucdx7D/eRzzr7VzJ11wyyschBfSvbsmlxIKThXb+ul+t9/BIFJnPcQAQSBwsK7jIOZ/It9SXV+NWYLHrFtKCR7WNcMKMFI2svx0nQgsUkmrdBvrW+sIathy+0JyGeWmdmWPePzJzEsbdHTvwMW0K6nhXmz2UciMuRGwcsLdf65Amy0Kshoem5aWwPD+lPuchAyZSFRvgcVFNDL2GZsnsMnzlUmslsI2xNEnvRxONLZz6kPgReQ8IX4jqJWVCyuFiztQKCAQBYCfBrzQjxpSw+Cof981HIPjSz479dPvoulobzWqKyyIE/qOsn+WOFvF6PaamiDoFn+JHATuzcSHXCu97A+3AMS5ileqkoSF7ua7dEETGlQCNdn0V2BhAmnmzw8hlo5pS8ljcGSuWWbs/F+BOOfkGyIiVxBHsNm0X5EVFcLskSofcg8ssxMdYlObnAXWN84jnWxfBVnDMOqPyQVh67Taz+Bck1L0ibUx46v+IJACmKljVzWItb0pftBgvKiS441wcGz+tb6h2XMVKYNMjBCiAJwnIacbSCUPq/vlJnoq6zE2zV3kl16lzLeFNX5pbX3xLTncqaOfBp10L7DyEV6PqX-----END RSA PRIVATE KEY-----',
  PUBLIC_KEY: process.env.PUBLIC_KEY || '-----BEGIN PUBLIC KEY-----MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQ==-----END PUBLIC KEY-----',
  REDIS_HOST: process.env.REDIS_HOST || '127.0.0.1',
  REDIS_PORT: process.env.REDIS_PORT || 6379,
  NODE_ENV: process.env.NODE_ENV || 'dev',
  PORT: process.env.PORT || 4001,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL || 'Crictracker@yudizproject.tk',
  AWS_ACCESSKEYID: process.env.AWS_ACCESSKEYID || 'AKIAVEG4UMFNJUU4K6N5',
  AWS_SECRETKEY: process.env.AWS_SECRETKEY || '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',
  AWS_REGION: process.env.AWS_REGION || 'ap-south-1',
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || 'crictracker-admin-panel',
  S3_BUCKET_PROFILE_PATH: process.env.S3_BUCKET_PROFILE_PATH || 'profile-pic/',
  S3_BUCKET_KYC_PATH: process.env.S3_BUCKET_KYC_PATH || 'kyc/pan/',
  S3_BUCKET_BANK_PATH: process.env.S3_BUCKET_BANK_PATH || 'kyc/bank/',
  S3_BUCKET_FB_PATH: process.env.S3_BUCKET_FB_PATH || 'fb/',
  S3_BUCKET_TWITTER_PATH: process.env.S3_BUCKET_TWITTER_PATH || 'twitter/',
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH || 'media/featureimage',
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_THUMBIMAGE_PATH || 'media/thumbnailimage',
  S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH || 'media/attachments/',
  S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH: process.env.S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH || 'media/chatmedia',
  S3_BUCKET_TEAM_PATH: process.env.S3_BUCKET_ARTICLE_EDITOR_MEDIA_PATH || 'team/',
  S3_BUCKET_PLAYER_PATH: process.env.S3_BUCKET_PLAYER_PATH || 'player/',
  S3_BUCKET_CATEGORY_PATH: process.env.S3_BUCKET_CATEGORY_PATH || 'category/',
  SMTP_EMAIL: process.env.SMTP_EMAIL || 'yudizmean@gmail.com',
  SMTP_PASSWORD: process.env.SMTP_PASSWORD || 'Yudiz@321',
  POSTMARK_SERVER_CLIENT: process.env.POSTMARK_SERVER_CLIENT || '',
  SENTRY_DSN: process.env.SENTRY_DSN || 'https://c4d6413db2ab401fa354fd66a24810a2@o992135.ingest.sentry.io/5949470',
  BOOKMARK_COUNT_UPDATE_EVENT: process.env.BOOKMARK_COUNT_UPDATE_EVENT || 'bookmark-count-update-event',
  BOOKMARK_COUNT_UPDATE_CONSUMER: process.env.BOOKMARK_COUNT_UPDATE_CONSUMER || 'bookmark-count-update-consumer',
  BOOKMARK_COUNT_UPDATE_GROUP: process.env.BOOKMARK_COUNT_UPDATE_GROUP || 'bookmark-count-update-group',
  S3_BUCKET_URL: process.env.S3_BUCKET_URL || 'https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/',
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '1596294133114-4dbktn77eg9vcn4esek3vpapvg6look9.apps.googleusercontent.com',
  authGrpcUrl: process.env.AUTH_GRPC_URL || '0.0.0.0:2001',
  KEEP_ALIVE_TIMEOUT: process.env.KEEP_ALIVE_TIMEOUT || 65000
}

const development = {
  DB_URL: process.env.DB_URL || 'mongodb+srv://brijesh_1116:mLab17@mycluster0.xnamd.mongodb.net/crictracker-auth-dev?authSource=admin&replicaSet=myCluster0-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true',
  CONNECTION: parseInt(process.env.CONNECTION) || 10,
  JWT_SECRET: process.env.JWT_SECRET || 'crictracker',
  PRIVATE_KEY: process.env.PRIVATE_KEY || '-----BEGIN RSA PRIVATE KEY-----MIIJKQIBAAKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQKCAgBj6XnsIfwdHnnLvL+DRHfVOTP+EV9153/Gd5ib2huhVoqw2ZGU1K92xrJ5FGEAxWeIUwLjVaZHXVvs/nVzjKQyacaZjtaMgHZH7tls9nanW9q5wdA9thmElHvwSNMlepg5OZV2sbke/MOmt2k6UvyFooWHAjit4zP5Sg0UTSsgAl91sRKZwOdsy4UjXoLsH6klMI8IeFIEsckHXR+v2n373ZekOqETlyLUht4MWo+iacoeVqw0JQrxfdBxH3OokJfS9+ieN7HEDCI2vukGQC4stasicAn48O09GiypQa551cnSS51k3zpsIDsQdGJQ/exEQpQzxIIyArYbwizAtmAeJTkbz7S2vitBSnECmxbwZmQgV/V3LdpZQ6UITgmZnoqHnfmtMj1rJUSILOxNEVATmzS2Yf1GHM3O8ChKRfrTstPA9n7Y3nSTSmGrk/sn9LDa75q51SvYs6SBWALDzqtK15mz4lTpfb13n8hRlEvWJwREq0P2/SYWmGuNacB0xrfeRdnqwyFPLDslNo8zD9wL8n5Jiz2WrxILohDSJ7npLu9dkkqYIKwGFmrejPCHR0EHwA1sdHDoM1/m2ux0d0rzyKb5LYs9t91mdV1XGzTuFGuxnHEOcveEJsrDqiainfXZdmLrcqi6/Gk9DKPCyT+nUnRl7+DPU83mqLQOIQUMAQKCAQEA5Q5r9IQuqK/IiP4/HfLNtEMwAYvKFFzWP1L80RmCSuzMoB6bSY3fWuXA4AEVQkfjAprSIvnByjMnsayGpfeR02NlLeyxGqpxcyZHt2hgemk9H6RUl5fIC4slu1W3lBRoL4Sps6qdyx74IMZMqANsC+f8eYeF+JigoKkLajLVzpAY+XU12AkBdokjBCVScLc84UDI3UXacxuS0dhAKhggRaPNMHY6pKel0wvek3olxDxlLjb6DuTEEa5Z0EVQ4qhx7aobFBQmp4+wjVb2re2G5FhnGJfh6/t/6QrTOYjGKiPiMSJZjqizQO9I1bSQp/oJ8/0W6Z/htOffibD83FRbgQKCAQEA4E332PHgegfXEMDab5Hk5+y9riQ7nfeSTgTT0W9hjbjdoXtgcUgQ8S9Pu9Fd+rTVW6RQM2OJ2DVjf6Eu98PYzlGxoL0DeejCFWU/WnrtpkjE6zvkbBLcNtgKkV6OfEhfQzk5/p+cGtjcV80P1YkkIQ9EBUHzyk6IDq9Ok4JWyTIS6PdL53r81a+ub+pQlW53YrJQRXRXnUEnM1xhZhH2AivuIRGuvdVzPPiZfLYd7TANDrQnmeByp2QRJwkT1FVe6MAaR2q3j7piBIbfvmtxNPzYl2HWlyxvEniGRDQbAkMmuIv+7+NYxD/d3EpTrt0AiCe6CckPJNOZkhpXQgU69QKCAQEApj8XX3romooq1DMkAEqPvjvdheG9o5XV8lP7JpCLHnJL+hL8xh/wcnq6yFpA4cBnJSbVSYlYe7cxIiWD/MV406Iad4CI8j+u49JuztE05OOo92Q/+V6yVJ6DnjoSaal+DK8OtFYq/JfXo4IJdRA2xVV0y4fvVoUAYFsQ691FjQzM85F8qPWwWCYkggfMk/6KczqgDul6KX1jzGZV+7dTBPhkHr5Qxdzf4BOHUiafbpQfI7HHQDQNkn+mtCD7GecD+WkzChmuDIOfspXhqE7zTpxTB2iFEs+RAMVYlTOOEFvG+b5incYXhBOoG2NYcnJp8upITPw7xx9cAQWyIQAhAQKCAQEAt/IYzFfnoAun6nxNZmu9zhjOoO3j2jL6T3MUBlASL3gogVI9kAjqo/AJslwLdxsvUX0ZrFr341A9LaCQdO2ucdx7D/eRzzr7VzJ11wyyschBfSvbsmlxIKThXb+ul+t9/BIFJnPcQAQSBwsK7jIOZ/It9SXV+NWYLHrFtKCR7WNcMKMFI2svx0nQgsUkmrdBvrW+sIathy+0JyGeWmdmWPePzJzEsbdHTvwMW0K6nhXmz2UciMuRGwcsLdf65Amy0Kshoem5aWwPD+lPuchAyZSFRvgcVFNDL2GZsnsMnzlUmslsI2xNEnvRxONLZz6kPgReQ8IX4jqJWVCyuFiztQKCAQBYCfBrzQjxpSw+Cof981HIPjSz479dPvoulobzWqKyyIE/qOsn+WOFvF6PaamiDoFn+JHATuzcSHXCu97A+3AMS5ileqkoSF7ua7dEETGlQCNdn0V2BhAmnmzw8hlo5pS8ljcGSuWWbs/F+BOOfkGyIiVxBHsNm0X5EVFcLskSofcg8ssxMdYlObnAXWN84jnWxfBVnDMOqPyQVh67Taz+Bck1L0ibUx46v+IJACmKljVzWItb0pftBgvKiS441wcGz+tb6h2XMVKYNMjBCiAJwnIacbSCUPq/vlJnoq6zE2zV3kl16lzLeFNX5pbX3xLTncqaOfBp10L7DyEV6PqX-----END RSA PRIVATE KEY-----',
  PUBLIC_KEY: process.env.PUBLIC_KEY || '-----BEGIN PUBLIC KEY-----MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQ==-----END PUBLIC KEY-----',
  REDIS_HOST: process.env.REDIS_HOST || '127.0.0.1',
  REDIS_PORT: process.env.REDIS_PORT || 6379,
  NODE_ENV: process.env.NODE_ENV || 'dev',
  PORT: process.env.PORT || 4001,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL || 'Crictracker@yudizproject.tk',
  AWS_ACCESSKEYID: process.env.AWS_ACCESSKEYID || 'AKIAVEG4UMFNJUU4K6N5',
  AWS_SECRETKEY: process.env.AWS_SECRETKEY || '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',
  AWS_REGION: process.env.AWS_REGION || 'ap-south-1',
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || 'crictracker-admin-panel',
  S3_BUCKET_PROFILE_PATH: process.env.S3_BUCKET_PROFILE_PATH || 'profile-pic/',
  S3_BUCKET_KYC_PATH: process.env.S3_BUCKET_KYC_PATH || 'kyc/pan/',
  S3_BUCKET_BANK_PATH: process.env.S3_BUCKET_BANK_PATH || 'kyc/bank/',
  S3_BUCKET_FB_PATH: process.env.S3_BUCKET_FB_PATH || 'fb/',
  S3_BUCKET_TWITTER_PATH: process.env.S3_BUCKET_TWITTER_PATH || 'twitter/',
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH || 'media/featureimage',
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_THUMBIMAGE_PATH || 'media/thumbnailimage',
  S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH: process.env.S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH || 'media/chatmedia',
  S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH || 'media/attachments/',
  SMTP_EMAIL: process.env.SMTP_EMAIL || 'yudizmean@gmail.com',
  SMTP_PASSWORD: process.env.SMTP_PASSWORD || 'Yudiz@321',
  POSTMARK_SERVER_CLIENT: process.env.POSTMARK_SERVER_CLIENT || '',
  SENTRY_DSN: process.env.SENTRY_DSN || 'https://c4d6413db2ab401fa354fd66a24810a2@o992135.ingest.sentry.io/5949470',
  S3_BUCKET_CATEGORY_PATH: process.env.S3_BUCKET_CATEGORY_PATH || 'team/',
  S3_BUCKET_PLAYER_PATH: process.env.S3_BUCKET_PLAYER_PATH || 'player/',
  S3_BUCKET_TEAM_PATH: process.env.S3_BUCKET_TEAM_PATH || 'team/',
  BOOKMARK_COUNT_UPDATE_EVENT: process.env.BOOKMARK_COUNT_UPDATE_EVENT || 'bookmark-count-update-event',
  BOOKMARK_COUNT_UPDATE_CONSUMER: process.env.BOOKMARK_COUNT_UPDATE_CONSUMER || 'bookmark-count-update-consumer',
  BOOKMARK_COUNT_UPDATE_GROUP: process.env.BOOKMARK_COUNT_UPDATE_GROUP || 'bookmark-count-update-group',
  S3_BUCKET_URL: process.env.S3_BUCKET_URL || 'https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/',
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '1596294133114-4dbktn77eg9vcn4esek3vpapvg6look9.apps.googleusercontent.com',
  authGrpcUrl: process.env.AUTH_GRPC_URL || '0.0.0.0:2001',
  KEEP_ALIVE_TIMEOUT: process.env.KEEP_ALIVE_TIMEOUT || 65000
}

const prod = {
  DB_URL: process.env.DB_URL || 'mongodb+srv://brijesh_1116:mLab17@mycluster0.xnamd.mongodb.net/crictracker-auth-dev?authSource=admin&replicaSet=myCluster0-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true',
  CONNECTION: parseInt(process.env.CONNECTION) || 10,
  JWT_SECRET: process.env.JWT_SECRET || 'crictracker',
  PRIVATE_KEY: process.env.PRIVATE_KEY || '-----BEGIN RSA PRIVATE KEY-----MIIJKQIBAAKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQKCAgBj6XnsIfwdHnnLvL+DRHfVOTP+EV9153/Gd5ib2huhVoqw2ZGU1K92xrJ5FGEAxWeIUwLjVaZHXVvs/nVzjKQyacaZjtaMgHZH7tls9nanW9q5wdA9thmElHvwSNMlepg5OZV2sbke/MOmt2k6UvyFooWHAjit4zP5Sg0UTSsgAl91sRKZwOdsy4UjXoLsH6klMI8IeFIEsckHXR+v2n373ZekOqETlyLUht4MWo+iacoeVqw0JQrxfdBxH3OokJfS9+ieN7HEDCI2vukGQC4stasicAn48O09GiypQa551cnSS51k3zpsIDsQdGJQ/exEQpQzxIIyArYbwizAtmAeJTkbz7S2vitBSnECmxbwZmQgV/V3LdpZQ6UITgmZnoqHnfmtMj1rJUSILOxNEVATmzS2Yf1GHM3O8ChKRfrTstPA9n7Y3nSTSmGrk/sn9LDa75q51SvYs6SBWALDzqtK15mz4lTpfb13n8hRlEvWJwREq0P2/SYWmGuNacB0xrfeRdnqwyFPLDslNo8zD9wL8n5Jiz2WrxILohDSJ7npLu9dkkqYIKwGFmrejPCHR0EHwA1sdHDoM1/m2ux0d0rzyKb5LYs9t91mdV1XGzTuFGuxnHEOcveEJsrDqiainfXZdmLrcqi6/Gk9DKPCyT+nUnRl7+DPU83mqLQOIQUMAQKCAQEA5Q5r9IQuqK/IiP4/HfLNtEMwAYvKFFzWP1L80RmCSuzMoB6bSY3fWuXA4AEVQkfjAprSIvnByjMnsayGpfeR02NlLeyxGqpxcyZHt2hgemk9H6RUl5fIC4slu1W3lBRoL4Sps6qdyx74IMZMqANsC+f8eYeF+JigoKkLajLVzpAY+XU12AkBdokjBCVScLc84UDI3UXacxuS0dhAKhggRaPNMHY6pKel0wvek3olxDxlLjb6DuTEEa5Z0EVQ4qhx7aobFBQmp4+wjVb2re2G5FhnGJfh6/t/6QrTOYjGKiPiMSJZjqizQO9I1bSQp/oJ8/0W6Z/htOffibD83FRbgQKCAQEA4E332PHgegfXEMDab5Hk5+y9riQ7nfeSTgTT0W9hjbjdoXtgcUgQ8S9Pu9Fd+rTVW6RQM2OJ2DVjf6Eu98PYzlGxoL0DeejCFWU/WnrtpkjE6zvkbBLcNtgKkV6OfEhfQzk5/p+cGtjcV80P1YkkIQ9EBUHzyk6IDq9Ok4JWyTIS6PdL53r81a+ub+pQlW53YrJQRXRXnUEnM1xhZhH2AivuIRGuvdVzPPiZfLYd7TANDrQnmeByp2QRJwkT1FVe6MAaR2q3j7piBIbfvmtxNPzYl2HWlyxvEniGRDQbAkMmuIv+7+NYxD/d3EpTrt0AiCe6CckPJNOZkhpXQgU69QKCAQEApj8XX3romooq1DMkAEqPvjvdheG9o5XV8lP7JpCLHnJL+hL8xh/wcnq6yFpA4cBnJSbVSYlYe7cxIiWD/MV406Iad4CI8j+u49JuztE05OOo92Q/+V6yVJ6DnjoSaal+DK8OtFYq/JfXo4IJdRA2xVV0y4fvVoUAYFsQ691FjQzM85F8qPWwWCYkggfMk/6KczqgDul6KX1jzGZV+7dTBPhkHr5Qxdzf4BOHUiafbpQfI7HHQDQNkn+mtCD7GecD+WkzChmuDIOfspXhqE7zTpxTB2iFEs+RAMVYlTOOEFvG+b5incYXhBOoG2NYcnJp8upITPw7xx9cAQWyIQAhAQKCAQEAt/IYzFfnoAun6nxNZmu9zhjOoO3j2jL6T3MUBlASL3gogVI9kAjqo/AJslwLdxsvUX0ZrFr341A9LaCQdO2ucdx7D/eRzzr7VzJ11wyyschBfSvbsmlxIKThXb+ul+t9/BIFJnPcQAQSBwsK7jIOZ/It9SXV+NWYLHrFtKCR7WNcMKMFI2svx0nQgsUkmrdBvrW+sIathy+0JyGeWmdmWPePzJzEsbdHTvwMW0K6nhXmz2UciMuRGwcsLdf65Amy0Kshoem5aWwPD+lPuchAyZSFRvgcVFNDL2GZsnsMnzlUmslsI2xNEnvRxONLZz6kPgReQ8IX4jqJWVCyuFiztQKCAQBYCfBrzQjxpSw+Cof981HIPjSz479dPvoulobzWqKyyIE/qOsn+WOFvF6PaamiDoFn+JHATuzcSHXCu97A+3AMS5ileqkoSF7ua7dEETGlQCNdn0V2BhAmnmzw8hlo5pS8ljcGSuWWbs/F+BOOfkGyIiVxBHsNm0X5EVFcLskSofcg8ssxMdYlObnAXWN84jnWxfBVnDMOqPyQVh67Taz+Bck1L0ibUx46v+IJACmKljVzWItb0pftBgvKiS441wcGz+tb6h2XMVKYNMjBCiAJwnIacbSCUPq/vlJnoq6zE2zV3kl16lzLeFNX5pbX3xLTncqaOfBp10L7DyEV6PqX-----END RSA PRIVATE KEY-----',
  PUBLIC_KEY: process.env.PUBLIC_KEY || '-----BEGIN PUBLIC KEY-----MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyLJhj3L0BOqiIEjnYLdBgAwf4elZ7lJOqzSsllw9SuNsWv12C8GTVmAlKMbw3YKNcF2+a/DSY22UJQ3gSNT7xWr0rhwHTsltBbyf+Rgd/OmXTxTPFMe8CfcPHk8mq4G/V+kkBINhYXPh1X74v2zKYcKKJE/H4fZxHnnb7K8REUotOk2+1Vu0Fy+cr5obi9RKC9iMrh/gVugE16uQbi6XXKHqo/Jri791PWN/h+wBy/EYh3feD/w5/WahuUlW7HbUmvtmEXwFjaTvf3Oj1BGsdRmYFO2QXh4139MhwE4GBbbeLqagOrplXyrh9AmgOH8nlEYuyJf0gEggQLhdjY9Mo9PS8WQqS/v8pxl1Yd3xAb6jMwjKfVWwsSniEekW+Mgnqss1OkwUTD92a3+QDY9qc/DmdyXayw/t4po0io6AuN/Q5Twqzof4Gvc0Nh9jwH9Ei9ywTruOADtl2TkiyEu00CIpliRSUoaX8NKHCYrCDGh+IX93f1NNgbchSJD8TI2QJl+/64Lw78Mta7KV0yGiajrlhia45HeYtfjv7cnSLpR13KHNSzGHFakgPM4REYVUJUm3rZe9CvEQvZCXEByhaHnZB/YrTAdTGTrI1A7RSCTVjhc5mShrM9iGXcBLULlYU3DVCxfWddzi5QTkeeLDJY5kgGKVxP5OgSXr/gT7zHUCAwEAAQ==-----END PUBLIC KEY-----',
  REDIS_HOST: process.env.REDIS_HOST || '127.0.0.1',
  REDIS_PORT: process.env.REDIS_PORT || 6379,
  NODE_ENV: process.env.NODE_ENV || 'dev',
  PORT: process.env.PORT || 4001,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL || 'Crictracker@yudizproject.tk',
  AWS_ACCESSKEYID: process.env.AWS_ACCESSKEYID || 'AKIAVEG4UMFNJUU4K6N5',
  AWS_SECRETKEY: process.env.AWS_SECRETKEY || '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',
  AWS_REGION: process.env.AWS_REGION || 'ap-south-1',
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || 'crictracker-admin-panel',
  S3_BUCKET_PROFILE_PATH: process.env.S3_BUCKET_PROFILE_PATH || 'profile-pic/',
  S3_BUCKET_BANK_PATH: process.env.S3_BUCKET_BANK_PATH || 'kyc/bank/',
  S3_BUCKET_KYC_PATH: process.env.S3_BUCKET_KYC_PATH || 'kyc/pan/',
  S3_BUCKET_FB_PATH: process.env.S3_BUCKET_FB_PATH || 'fb/',
  S3_BUCKET_TWITTER_PATH: process.env.S3_BUCKET_TWITTER_PATH || 'twitter/',
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH || 'media/featureimage',
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_THUMBIMAGE_PATH || 'media/thumbnailimage',
  S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH: process.env.S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH || 'media/chatmedia',
  S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH: process.env.S3_BUCKET_ARTICLE_ATTACHMENTIMAGE_PATH || 'media/attachments/',
  SMTP_EMAIL: process.env.SMTP_EMAIL || 'yudizmean@gmail.com',
  SMTP_PASSWORD: process.env.SMTP_PASSWORD || 'Yudiz@321',
  POSTMARK_SERVER_CLIENT: process.env.POSTMARK_SERVER_CLIENT || '',
  SENTRY_DSN: process.env.SENTRY_DSN || 'https://f80326950ae04f23be6fa308406b6d3a@o992135.ingest.sentry.io/6725499',
  S3_BUCKET_CATEGORY_PATH: process.env.S3_BUCKET_CATEGORY_PATH || 'category/',
  S3_BUCKET_PLAYER_PATH: process.env.S3_BUCKET_PLAYER_PATH || 'player/',
  S3_BUCKET_TEAM_PATH: process.env.S3_BUCKET_TEAM_PATH || 'team/',
  BOOKMARK_COUNT_UPDATE_EVENT: process.env.BOOKMARK_COUNT_UPDATE_EVENT || 'bookmark-count-update-event',
  BOOKMARK_COUNT_UPDATE_CONSUMER: process.env.BOOKMARK_COUNT_UPDATE_CONSUMER || 'bookmark-count-update-consumer',
  BOOKMARK_COUNT_UPDATE_GROUP: process.env.BOOKMARK_COUNT_UPDATE_GROUP || 'bookmark-count-update-group',
  S3_BUCKET_URL: process.env.S3_BUCKET_URL || 'https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/',
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '1596294133114-4dbktn77eg9vcn4esek3vpapvg6look9.apps.googleusercontent.com',
  authGrpcUrl: process.env.AUTH_GRPC_URL || '0.0.0.0:2001',
  KEEP_ALIVE_TIMEOUT: process.env.KEEP_ALIVE_TIMEOUT || 65000
}

if (ENV === 'prod') {
  module.exports = prod
} else if (ENV === 'development') {
  module.exports = development
} else if (ENV === 'stag') {
  module.exports = stag
} else {
  module.exports = dev
}

console.log(`Server Env is ${ENV}`)
