# Generated by Django 3.2.18 on 2023-03-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
