# Generated by Django 3.2.18 on 2023-03-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0003_user_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('resident_permit', models.CharField(choices=[('resident', 'resident'), ('tourist', 'tourist')], default='resident', max_length=10)),
                ('profile_pic', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(choices=[('resident', 'resident'), ('tourist', 'tourist')], default='single', max_length=20)),
                ('children_info', models.CharField(max_length=75)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='user_flow.user')),
            ],
        ),
    ]
