# Generated by Django 4.1.7 on 2023-03-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='children_info',
            field=models.JSONField(default=None),
        ),
    ]
