# Generated by Django 4.1.7 on 2023-03-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0006_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'single'), ('Relationship', 'Relationship'), ('Parents', 'Parents')], default='single', max_length=20),
        ),
    ]
