# Generated by Django 4.1.7 on 2023-03-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0007_alter_userprofile_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='children_info',
            field=models.JSONField(null=True),
        ),
    ]
