# Generated by Django 4.1.7 on 2023-03-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0008_alter_userprofile_children_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
