# Generated by Django 4.1.7 on 2023-03-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0010_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
