# Generated by Django 4.1.7 on 2023-03-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0015_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
