# Generated by Django 3.2.18 on 2023-03-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0018_alter_userprofile_relationship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mood', models.CharField(choices=[('adventurous', 'adventurous'), ('sporty', 'sporty'), ('relaxing', 'relaxing'), ('family_friendly', 'family_friendly')], default='sporty', max_length=30)),
                ('user_budget', models.FloatField()),
                ('user_time', models.CharField(default='[]', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserPreferedChoice', to='user_flow.user')),
            ],
        ),
    ]
