# Generated by Django 3.2.18 on 2023-03-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0019_userchoicepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoicepreference',
            name='user_budget',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userchoicepreference',
            name='user_mood',
            field=models.CharField(max_length=30),
        ),
    ]
