# Generated by Django 3.2.18 on 2023-03-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0020_auto_20230309_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoicepreference',
            name='user_time',
            field=models.CharField(max_length=200),
        ),
    ]
