# Generated by Django 3.2.18 on 2023-03-15 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0021_alter_userchoicepreference_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoicepreference',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 5, 30, 49, 107115)),
            preserve_default=False,
        ),
    ]
