# Generated by Django 3.2.18 on 2023-03-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0022_userchoicepreference_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoicepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPreferedChoice', to='user_flow.user'),
        ),
    ]
