# Generated by Django 3.2.18 on 2023-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0024_userbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('manual', 'manual'), ('google', 'google'), ('facebook', 'facebook'), ('apple', 'apple')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='socialToken',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
