# Generated by Django 3.2.18 on 2023-03-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0025_auto_20230320_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
