# Generated by Django 3.2.18 on 2023-03-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0026_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
