# Generated by Django 3.2.18 on 2023-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0028_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpriority',
            name='notification_resume_time',
            field=models.DateTimeField(null=True),
        ),
    ]
