# Generated by Django 3.2.18 on 2023-03-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0029_userpriority_notification_resume_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='socialToken',
        ),
        migrations.AddField(
            model_name='user',
            name='social_token',
            field=models.TextField(blank=True),
        ),
    ]
