# Generated by Django 3.2.18 on 2023-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0030_auto_20230330_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_plateform',
            field=models.CharField(blank=True, choices=[('ios', 'ios'), ('android', 'android')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.TextField(blank=True),
        ),
    ]
