# Generated by Django 3.2.18 on 2023-05-17 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0031_auto_20230330_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_previous_recommandation', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserRecommandation', to='user_flow.user')),
            ],
        ),
    ]
