export const GET_COMMENTS = 'GET_COMMENTS'
export const CLEAR_GET_COMMENTS_RESPONSE = 'CLEAR_GET_COMMENTS_RESPONSE'

export const ADD_COMMENT = 'ADD_COMMENT'
export const CLEAR_ADD_COMMENT_RESPONSE = 'CLEAR_ADD_COMMENT_RESPONSE'

export const DELETE_COMMENT = 'DELETE_COMMENT'
