apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-min
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: crictracker-website-dev