kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: development
  REACT_APP_API_URL: 'https://gateway-stag.crictracker.ml/'
  REACT_APP_S3_PREFIX: 'https://crictracker-admin-panel-local-dev-08032022.s3.ap-south-1.amazonaws.com/'
  ARTICLE_BASE_URL: 'https://article-dev.crictracker.ml/'