<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */
?>
<?php $parentItem = $block->getItem();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php $items = array_merge([$parentItem], $parentItem->getChildrenItems()); ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item',
            $parentItem) && $parentItem->getGiftMessageId()): ?>
        <?php $_showlastRow = true ?>
    <?php else: ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr class="options-label">
                <td class="col label" colspan="12"><?= /* @escapeNotVerified */
                    $attributes['option_label'] ?></td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr id="order-item-row-<?= /* @escapeNotVerified */
    $_item->getId() ?>"
        class="<?php if ($_item->getParentItem()): ?>item-options-container<?php else: ?>item-parent<?php endif; ?>"<?php if ($_item->getParentItem()): ?> data-th="<?= /* @escapeNotVerified */
    $attributes['option_label'] ?>"<?php endif; ?>>
        <?php if (!$_item->getParentItem()): ?>
            <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
                <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
            </td>
        <?php else: ?>
            <td class="col value"
                data-th="<?= $block->escapeHtml(__('Product Name')) ?>"><?= $block->getValueHtml($_item) ?></td>
        <?php endif; ?>
        <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @escapeNotVerified */
            $block->prepareSku($_item->getSku()) ?></td>
        <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?php if (!$_item->getParentItem()): ?>
                <?= $block->getItemPriceHtml() ?>
            <?php endif; ?>
        </td>

        <td class="col qty" colspan="2" data-th="<?= $block->escapeHtml(__('Quantity')) ?>">
            <table class="cgst">
                <tbody style="background:none;text-align:center">
                <tr>
                    <?php if ($_item->getParentItem()): ?>
                        <td><?= /* @escapeNotVerified */
                            round($_item->getCgstPercent() ? $_item->getCgstPercent() : 0, 2) ?></td>
                    <?php endif; ?>
                    <td><?= /* @escapeNotVerified */
                        $priceHelper->currency($_item->getCgstAmount(), true, false) ?></td>
                </tr>
                </tbody>
            </table>
        </td>

        <?php
        $sgstUtgstPercent = 0;
        $sgstUtgstAmount = 0;
        if ($_item->getSgstPercent() > 0) {
            $sgstUtgstPercent = $_item->getSgstPercent();
            $sgstUtgstAmount = $_item->getSgstAmount();
        } else {
            $sgstUtgstPercent = $_item->getUtgstPercent();
            $sgstUtgstAmount = $_item->getUtgstAmount();
        }
        ?>

        <td class="col qty" colspan="2" data-th="<?= $block->escapeHtml(__('Quantity')) ?>">
            <table class="cgst">
                <tbody style="background:none;text-align:center">
                <tr>
                    <?php if ($_item->getParentItem()): ?>
                        <td><?= /* @escapeNotVerified */
                            round($sgstUtgstPercent ? $sgstUtgstPercent : 0, 2) ?></td>
                    <?php endif; ?>
                    <td><?= /* @escapeNotVerified */
                        $priceHelper->currency($sgstUtgstAmount, true, false) ?></td>
                </tr>
                </tbody>
            </table>
        </td>
        <td class="col qty" colspan="2" data-th="<?= $block->escapeHtml(__('Quantity')) ?>">
            <table class="cgst">
                <tbody style="background:none;text-align:center">
                <tr>
                    <?php if ($_item->getParentItem()): ?>
                        <td><?= /* @escapeNotVerified */
                            round($_item->getIgstPercent() ? $_item->getIgstPercent() : 0, 2) ?></td>
                    <?php endif; ?>
                    <td><?= /* @escapeNotVerified */
                        $priceHelper->currency($_item->getIgstAmount(), true, false) ?></td>
                </tr>
                </tbody>
            </table>
        </td>

        <td class="col qty" colspan="2" data-th="<?= $block->escapeHtmlAttr(__('Quantity')); ?>">
            <ul class="items-qty">
                <?php if (($_item->getParentItem() && $block->isChildCalculated()) ||
                    (!$_item->getParentItem() && !$block->isChildCalculated()) ||
                    ($_item->getQtyShipped() > 0 && $_item->getParentItem() && $block->isShipmentSeparately())) : ?>

                <?php endif; ?>
                <?php if (($_item->getParentItem() && $block->isChildCalculated()) ||
                    (!$_item->getParentItem() && !$block->isChildCalculated())) : ?>
                    <?php if ($_item->getQtyOrdered() > 0) : ?>
                        <li class="item">
                            <span class="title"><?= $block->escapeHtml(__('Ordered')); ?></span>
                            <span class="content"><?= /* @noEscape */
                                $_item->getQtyOrdered() * 1; ?></span>
                        </li>
                    <?php endif; ?>
                    <?php if ($_item->getQtyShipped() > 0 && !$block->isShipmentSeparately()) : ?>
                        <li class="item">
                            <span class="title"><?= $block->escapeHtml(__('Shipped')); ?></span>
                            <span class="content"><?= /* @noEscape */
                                $_item->getQtyShipped() * 1; ?></span>
                        </li>
                    <?php endif; ?>
                    <?php if ($_item->getQtyCanceled() > 0) : ?>
                        <li class="item">
                            <span class="title"><?= $block->escapeHtml(__('Canceled')); ?></span>
                            <span class="content"><?= /* @noEscape */
                                $_item->getQtyCanceled() * 1; ?></span>
                        </li>
                    <?php endif; ?>
                    <?php if ($_item->getQtyRefunded() > 0) : ?>
                        <li class="item">
                            <span class="title"><?= $block->escapeHtml(__('Refunded')); ?></span>
                            <span class="content"><?= /* @noEscape */
                                $_item->getQtyRefunded() * 1; ?></span>
                        </li>
                    <?php endif; ?>
                <?php elseif ($_item->getQtyShipped() > 0 && $_item->getParentItem() && $block->isShipmentSeparately()) : ?>
                    <li class="item">
                        <span class="title"><?= $block->escapeHtml(__('Shipped')); ?></span>
                        <span class="content"><?= /* @noEscape */
                            $_item->getQtyShipped() * 1; ?></span>
                    </li>
                <?php else : ?>

                <?php endif; ?>
            </ul>
        </td>
        <td class="col subtotal" colspan="8" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
            <?php if (!$_item->getParentItem()) : ?>
                <?= /* @noEscape */
                $block->getItemRowTotalHtml(); ?>
            <?php else : ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>

<?php if ($_showlastRow && (($_options = $block->getItemOptions()) || $block->escapeHtml($_item->getDescription()))): ?>
    <tr>
        <td class="col options" colspan="5">
            <?php if ($_options = $block->getItemOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                                <?= /* @escapeNotVerified */
                                $_formatedOptionValue['value'] ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <div class="tooltip content">
                                        <dl class="item options">
                                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                            <dd><?= /* @escapeNotVerified */
                                                $_formatedOptionValue['full_view'] ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd><?= $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
    </tr>
<?php endif; ?>
