<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem();
$_objectManager =   \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $_objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
 ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="tooltip wrapper"<?php endif; ?>>
                    <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                    <div class="tooltip content">
                        <dl class="item options">
                            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                            <dd><?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?></dd>
                        </dl>
                    </div>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd><?php echo $block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
        <table class="cgst">
            <tbody style="background:none;text-align:center">
            <tr>
                <td><?php echo round($_item->getOrderItem()->getCgstPercent() ? $_item->getOrderItem()->getCgstPercent(): 0,2);?></span></td>
                <td>
                    <?= /* @noEscape */ $block->getOrder()->formatPrice($_item->getData('cgst_amount')) ?>
                </td>
            </tr>
        </table>
    </td>
    <?php
    $sgstUtgstPercent=0;
    $sgstUtgstAmount=0;
    if($_item->getOrderItem()->getSgstPercent()>0){
        $sgstUtgstPercent=$_item->getOrderItem()->getSgstPercent();
        $sgstUtgstAmount=$_item->getOrderItem()->getSgstAmount();
    }
    else{
        $sgstUtgstPercent=$_item->getOrderItem()->getUtgstPercent();
        $sgstUtgstAmount=$_item->getOrderItem()->getUtgstAmount();
    }
    ?>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('SGST / UTGST')); ?>">
        <table class="Sgst">
            <tbody style="background:none;text-align:center">
            <tr>
                <td><?php echo round($sgstUtgstPercent,2);?></span></td>
                <td>
                    <?= /* @noEscape */ $block->getOrder()->formatPrice($sgstUtgstAmount) ?>
                </td>
            </tr>
        </table>
    </td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('IGST')); ?>">
        <table class="Sgst">
            <tbody style="background:none;text-align:center">
            <tr>
                <td><?php echo round($_item->getOrderItem()->getIgstPercent() ? $_item->getOrderItem()->getIgstPercent(): 0,2);?></span></td>
                <td>
                    <?= /* @noEscape */ $block->getOrder()->formatPrice($_item->getData('igst_amount')) ?>
                </td>
            </tr>
        </table>
    </td>
    <td class="col qty" style="text-align: center" data-th="<?php echo $block->escapeHtml(__('Qty Invoiced')); ?>">
        <span class="qty summary"><?php /* @escapeNotVerified */ echo $_item->getOrderItem()->getQtyOrdered()*1 ?></span>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
