export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'

export const SET_BREADCRUMB = 'SET_BREADCRUMB'

export const CLEAR_BREADCRUMB = 'CLEAR_BREADCRUMB'

export const UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'
