export const allRoutes = {
  home: '/',
  login: '/login',
  signUp: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  explore: '/explore',
  auction: '/auction',
  profile: '/profile',
  createAsset: '/create-asset',
  resellCreateAsset: (type, id, assetId) => `/resell-asset/${type}/${assetId}/${id}`,
  changePassword: '/change-password',
  setPassword: '/set-password',
  termsAndConditions: '/terms-and-conditions',
  privacyPolicy: '/privacy-policy',
  assetDetails: (id) => `/asset-details/${id}`,
  checkout: (id) => `/checkout/${id}`,
  mysteryBoxCheckout: (id) => `/mystery-box-checkout/${id}`,
  lootBoxCheckout: (id) => `/loot-box-checkout/${id}`,
  nuuCoins: '/nuucoins',
  donate: '/donate',
  referrals: '/referrals',
  community: '/community',
  editViewCommunity: (id) => `/community/${id}`,
  resellAssetDetails: (type, id) => `/asset-details/${type}/${id}`,
  profileChildRoutes: {
    collected: 'collected',
    created: 'created',
    communities: 'communities',
    private: 'private',
    wishlist: 'wishlist',
    myWallets: 'my-wallets',
    orders: 'orders',
    orderToSend: 'order-to-send',
    cardsAndAddresses: 'cards-and-addresses',
    transactions: 'transactions'
  },
  profileCollected: '/profile/collected',
  profileWishlist: '/profile/wishlist',
  profileCardsAndAddresses: '/profile/cards-and-addresses',
  creatorProfile: '/creator',
  creatorCollected: (id) => `/creator/collected/${id}`,
  creatorCreated: (id) => `/creator/created/${id}`,
  creatorCommunities: (id) => `/creator/communities/${id}`,
  crates: '/crates',
  editProfile: '/edit-profile',
  purchaseNuuCoins: '/purchase-nuucoins',
  createPost: '/create-post',
  editPost: (id) => `/edit-post/${id}`,
  finalizePost: (id) => `/finalize-post/${id}`,
  postDetails: (id) => `/post-details/${id}`,
  communities: '/communities',
  myPosts: '/my-posts',
  drop: '/drop',
  myDrops: '/my-drops',
  dropAssets: (id) => `/drop-assets/${id}`,
  trendingNfts: '/trending-nfts',
  orderDetails: '/order-details',
  createMysteryLootBox: '/create-mystery-loot-box',
  mysteryBoxDetails: (id) => `/mystery-box/${id}`,
  lootBoxDetails: (id) => `/loot-box/${id}`,
  giftAsset: (id) => `/gift-asset/${id}`,
  adminAssetDetails: (type, id) => `/admin-asset-details/${type}/${id}`,
  previewAsset: (link) => `/asset-preview/${link}`,
  donatePayment: '/donate-payment',
  faq: '/faq',
  customerSupport: '/customer-support'
}
