export const validationErrors = {
  serverError: 'Server is unavailable.',
  required: 'This field is required.',
  email: 'Please enter a valid email address.',
  number: 'Please enter a valid number.',
  digit: 'Please enter only digits.',
  url: 'Please enter a valid URL.',
  minLength: (length) => `Please enter a value greater than or equal to ${length}`,
  maxLength: (length) => `Please enter a value less than or equal to ${length}`,
  rangeLength: (min, max) => `Please enter a value between ${min} and ${max} characters long`,
  password: 'Password must contain 1 number, uppercase, lowercase, and special character.',
  passwordNotMatch: 'Please enter same password',
  noSPace: 'This field consisting only of non-whitespaces',
  pleaseLoginToWriteComment: 'Please login to write a comment',
  noSpecialCharacters: 'This field does not consist of special characters',
  donationMinPercentage: 'Donation percentage should be greater than or equal to 0.5',
  donationMaxPercentage: 'Donation percentage should be less than or equal to 10',
  royaltyMaxPercentage: 'Royalty percentage should be less than or equal to 50',
  percentage: 'Percentage should be greater than or equal to 0',
  price: 'Please enter a valid price',
  creditCard: 'Please enter valid credit card number',
  cvv: 'Please enter valid CVV number',
  phoneNumber: 'Please enter valid phone number',
  bidAmount: 'Please enter greater than or equal to minimum amount',
  walletAddress: 'Please enter valid wallet address',
  greaterThanMin: 'Please enter value greater than minimum amount',
  lessThanMax: 'Please enter value less than maximum amount'
}
