apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}
data:
  NODE_ENV: staging
  DEPLOY_HOST_URL: https://nodebackstag.fantasywl.in
  DEPLOY_HOST_PORT: '1338'
  DB_SQL_NAME: fantasy_stag
  DB_SQL_DIALECT: mysql
  # DB_SQL_HOST: fantasy.cyaoqdrfnsw7.ap-south-1.rds.amazonaws.com
  DB_SQL_HOST: mysql-staging-headless
  REDIS_HOST: 'redis-staging-master.staging.svc.cluster.local'
  REDIS_PORT: '6379'
  
  FRONTEND_HOST_URL: https://appstag.fantasywl.in
  FANTASY_NODE_URL: https://nodestag.fantasywl.in


  CASHFREE_APPID: 75766f425d7dd6b895948bd2f66757
  CASHFREE_BASEURL: https://payout-gamma.cashfree.com
  CASHFREE_CLIENTID: CF75766C494LPKPRI0BTG2EAV4G
  CASHFREE_RETURN_URL: https://appstag.fantasywl.in/profile
  CASHFREE_URL: https://test.cashfree.com

  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: '587'
  SMTP_FROM: fwl47576@gmail.com

  OTP_PROVIDER: TEST

  REDIS_2_HOST: 'redis-staging-master.staging.svc.cluster.local'
  REDIS_2_PORT: '6379'

  FANTASY_NODE_URL: https://nodestag.fantasywl.in

  DYNAMIC_LINK_DOMAIN_URI_PREFIX: 'https://wlfantasy.page.link'

  AWS_REGION: "ap-south-1"
  
  CRON_AUTH_ENABLED: "true"

  SENTRY_DSN: 'https://f9b9cbe448994647b39df3e26c9c1251@o1220141.ingest.sentry.io/6362906'

  GRPC_SERVER_URI: '0.0.0.0:1339'
  NOTIFICATIONS_TARGET_URI: 'fantasy-node-notifications-staging-grpc.staging.svc.cluster.local:80'
  USER_INFO_TARGET_URI: 'fantasy-node-user-informations-staging-grpc.staging.svc.cluster.local:80'
  STATICS_TARGET_URI: 'fantasy-node-statics-staging-grpc.staging.svc.cluster.local:80'
  ADMIN_TARGET_URI: 'fantasy-node-admin-staging-grpc.staging.svc.cluster.local:80'
  PAYMENT_TARGET_URI: 'fantasy-node-payments-staging-grpc.staging.svc.cluster.local:80'

  IOS_APP_STORE_ID: '6443831473'
  IOS_CUSTOM_SCHEME: 'fantasyapp.firebase.scheme'
  IOS_BUNDLE_ID: 'com.app.FantasyApp'
  DYNAMIC_LINK_ANDROID_PACKAGE_NAME: 'com.fantasy.wl'