export const CREATE_MYSTERY_BOX = 'CREATE_MYSTERY_BOX'
export const CLEAR_CREATE_MYSTERY_BOX_RESPONSE = 'CLEAR_CREATE_MYSTERY_BOX_RESPONSE'

export const GET_CRATE_ASSETS = 'GET_CRATE_ASSETS'
export const CLEAR_CRATE_ASSETS_RESPONSE = 'CLEAR_CRATE_ASSETS_RESPONSE'

export const CREATE_LOOT_BOX = 'CREATE_LOOT_BOX'
export const CLEAR_CREATE_LOOT_BOX_RESPONSE = 'CLEAR_CREATE_LOOT_BOX_RESPONSE'

export const GET_MYSTERY_BOXES = 'GET_MYSTERY_BOXES'
export const CLEAR_MYSTERY_BOXES_RESPONSE = 'CLEAR_MYSTERY_BOXES_RESPONSE'

export const GET_MYSTERY_BOX_DETAILS = 'GET_MYSTERY_BOX_DETAILS'
export const CLEAR_MYSTERY_BOX_DETAILS_RESPONSE = 'CLEAR_MYSTERY_BOX_DETAILS_RESPONSE'

export const GET_LOOT_BOXES = 'GET_LOOT_BOXES'
export const CLEAR_LOOT_BOXES_RESPONSE = 'CLEAR_LOOT_BOXES_RESPONSE'

export const GET_LOOT_BOX_DETAILS = 'GET_LOOT_BOX_DETAILS'
export const CLEAR_LOOT_BOX_DETAILS_RESPONSE = 'CLEAR_LOOT_BOX_DETAILS_RESPONSE'
