replicaCount: 1    # dont change the replica to more than 1 because it is queue type so mismatches the data in other deployments

image: 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-ampconverter:latest

labels:
  tier: backend
  release: blue-green
  environment: production

namespace: production

service:
  type: NodePort
  port: 80
  # internaltype: ClusterIP
  # internalport: 80
  # 
  healthcheck: /api/ping
  # pm2: 9209

resources:
  requests:
    memory: "50Mi"
    cpu: "50m"
  limits:
    memory: "200Mi"
    cpu: "200m"

# livenessProbe:
#   periodSeconds: 10
#   successThreshold: 1
#   failureThreshold: 3
#   initialDelaySeconds: 5
#   timeoutSeconds: 30
# readinessProbe:
#   initialDelaySeconds: 5
#   timeoutSeconds: 30
#   failureThreshold: 3
#   periodSeconds: 10
#   successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: "1"
  maxReplicas: "5"
  targetCPU: "60"

#Because we are using our private docker registry deployed in Kubernetes if you are using AWS(ECR) than you can disable this.
imagePullSecrets:
  enabled: false
  name: regcred