export const ADMIN_GET_USERS = 'ADMIN_GET_USERS'
export const ADMIN_CLEAR_GET_USERS = 'ADMIN_CLEAR_GET_USERS'

export const ADMIN_BLOCK_UNBLOCK_USER = 'ADMIN_BLOCK_UNBLOCK_USER'
export const ADMIN_CLEAR_BLOCK_UNBLOCK_USER = 'ADMIN_CLEAR_BLOCK_UNBLOCK_USER'
