export const LIKE_POST = 'LIKE_POST'
export const CLEAR_LIKE_POST_RESPONSE = 'CLEAR_LIKE_POST_RESPONSE'

export const UN_LIKE_POST = 'UN_LIKE_POST'
export const CLEAR_UN_LIKE_POST_RESPONSE = 'CLEAR_UN_LIKE_RESPONSE'
