# Generated by Django 3.2.18 on 2023-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
