# Generated by Django 3.2.18 on 2023-03-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_flow', '0002_admin_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='otp',
            field=models.IntegerField(blank=True, default=123123),
            preserve_default=False,
        ),
    ]
