# Generated by Django 3.2.18 on 2023-03-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_flow', '0004_alter_admin_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
