# Generated by Django 3.2.18 on 2023-03-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_flow', '0006_alter_admin_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.TextField(blank=True),
        ),
    ]
