# Generated by Django 3.2.18 on 2023-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_flow', '0007_alter_admin_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.TextField(blank=True)),
            ],
        ),
    ]
