kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  REACT_APP_API_URL: 'https://gateway-dev.crictracker.ml/'
  REACT_APP_DOMAIN: 'https://cricweb-dev.crictracker.ml/'
  REACT_APP_ARTICLE_REST_URL: 'https://article-dev.crictracker.ml'  
