export const CLEAR_CONNECT_WALLET = 'CLEAR_CONNECT_WALLET'
export const CONNECT_WALLET = 'CONNECT_WALLET'

export const WALLET_ACCOUNT = 'WALLET_ACCOUNT'
export const CLEAR_WALLET_ACCOUNT = 'CLEAR_WALLET_ACCOUNT'
