export const FOLLOW_COMMUNITY = 'FOLLOW_COMMUNITY'
export const CLEAR_FOLLOW_COMMUNITY_RESPONSE = 'CLEAR_FOLLOW_COMMUNITY_RESPONSE'

export const UN_FOLLOW_COMMUNITY = 'UN_FOLLOW_COMMUNITY'
export const CLEAR_UN_FOLLOW_COMMUNITY_RESPONSE = 'CLEAR_UN_FOLLOW_COMMUNITY_RESPONSE'

export const GET_COMMUNITY_FOLLOWER = 'GET_COMMUNITY_FOLLOWER'
export const CLEAR_GET_COMMUNITY_FOLLOWER_RESPONSE = 'CLEAR_GET_COMMUNITY_FOLLOWER_RESPONSE'

export const GET_FOLLOWED_COMMUNITY = 'GET_FOLLOWED_COMMUNITY'
export const CLEAR_GET_FOLLOWED_COMMUNITY_RESPONSE = 'CLEAR_GET_FOLLOWED_COMMUNITY_RESPONSE'
