image: public.ecr.aws/d7h0j7s7/docker:18.09
stages:
  - lint-check
  - deploy-local-dev
  - deploy-dev
  - deploy-prod
  - rollback-prod

lint-check:
  stage: lint-check
  image: 
    name: public.ecr.aws/d7h0j7s7/node:16-alpine3.11
  script: 
    - npm install
    # - npm install eslint-plugin-react@latest --save-dev
    - npm install -g eslint
    - eslint .
  allow_failure: false
  only:
    - dev

deploy-local-dev:
  stage: deploy-local-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:local-dev_$CI_COMMIT_SHA .
    # - docker tag crictracker-redis-server-local-dev:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:local-dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:local-dev_$CI_COMMIT_SHA
    - helm upgrade -n local-dev crictracker-redis-server-local-dev crictracker-helmrepo/crictracker-redis-server-local-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:local-dev_$CI_COMMIT_SHA
  only:
    - dev

deploy-dev:
  stage: deploy-dev
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  environment: crictracker-prod
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - export VERIFY_CHECKSUM=false
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:dev_$CI_COMMIT_SHA .
    # - docker tag crictracker-redis-server-dev:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:dev_$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:dev_$CI_COMMIT_SHA
    - helm upgrade -n dev crictracker-redis-server-dev crictracker-helmrepo/crictracker-redis-server-prod-dev --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:dev_$CI_COMMIT_SHA
  only:
    - dev

deploy-prod:
  stage: deploy-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  environment: crictracker-prod
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - export VERIFY_CHECKSUM=false
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    #deploy
    - docker build -t crictracker-redis-server:$CI_COMMIT_SHA .
    - docker tag crictracker-redis-server:$CI_COMMIT_SHA 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:$CI_COMMIT_SHA
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 693583001687.dkr.ecr.ap-south-1.amazonaws.com
    - docker push 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:$CI_COMMIT_SHA
    - helm upgrade -n production crictracker-redis-server-prod crictracker-helmrepo/crictracker-redis-server-prod --set=image=693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-redis-server:$CI_COMMIT_SHA
  only:
    - master
  when:  manual
  
# sonarqube-check:
#   stage: sonarqube-check
#   image: 
#     name: sonarsource/sonar-scanner-cli:latest
#     entrypoint: [""]
#   variables:
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
#     GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script: 
#     - sonar-scanner
#   allow_failure: true
#   only:
#     - dev


rollback-prod:
  stage: rollback-prod
  image: public.ecr.aws/d7h0j7s7/gitlab-ci:latestv1
  services:
    - docker:18.09-dind
  variables:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
  before_script:
    - export AWS_ACCESS_KEY_ID=$CRICTRACKER_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$CRICTRACKER_AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$CRICTRACKER_AWS_DEFAULT_REGION
    - aws eks --region ap-south-1 update-kubeconfig --name crictracker
    - helm repo add --username yudiz_AmanM --password jkxCqf4ctBEZTsCQgfxU crictracker-helmrepo https://gitlab.com/api/v4/projects/30639052/packages/helm/stable
    - helm repo update
  script:
    - helm history -n production crictracker-redis-server-prod
    - helm rollback -n production crictracker-redis-server-prod
    - kubectl rollout status -w deployment/crictracker-redis-server-prod
    - helm history -n production crictracker-redis-server-prod
  when: manual
  only:
    - master
