export const INTERNAL_WALLET_NUU_COINS = 'INTERNAL_WALLET_NUU_COINS'
export const CLEAR_INTERNAL_WALLET_NUU_COINS_RESPONSE = 'CLEAR_INTERNAL_WALLET_NUU_COINS_RESPONSE'

export const NUU_COINS_DETAILS = 'NUU_COINS_DETAILS'
export const CLEAR_NUU_COINS_DETAILS_RESPONSE = 'CLEAR_NUU_COINS_DETAILS_RESPONSE'
