apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: past-upcoming
  namespace: local-dev
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - 'curl -X PUT https://matchmanage-dev.crictracker.ml/api/past-upcoming'
            image: curlimages/curl
            name: past-upcoming
          restartPolicy: OnFailure
