apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: series-statistics
  namespace: local-dev
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - 'curl -X PUT https://matchmanage-dev.crictracker.ml/api/series-statistics'
            image: curlimages/curl
            name: series-statistics
          restartPolicy: OnFailure