export const CREATE_POST = 'CREATE_POST'
export const CLEAR_CREATE_POST_RESPONSE = 'CLEAR_CREATE_POST_RESPONSE'

export const UPLOAD_BLOG_CONTENT = 'UPLOAD_BLOG_CONTENT'
export const CLEAR_UPLOAD_BLOG_CONTENT_RESPONSE = 'CLEAR_UPLOAD_BLOG_CONTENT_RESPONSE'

export const UPDATE_POST = 'UPDATE_POST'
export const CLEAR_UPDATE_POST_RESPONSE = 'CLEAR_UPDATE_POST_RESPONSE'

export const GET_POSTS = 'GET_POSTS'
export const CLEAR_GET_POSTS_RESPONSE = 'CLEAR_GET_POSTS_RESPONSE'

export const GET_POST_DETAILS = 'GET_POST_DETAILS'
export const CLEAR_GET_POST_DETAILS_RESPONSE = 'CLEAR_GET_POST_DETAILS_RESPONSE'

export const GET_MY_POSTS = 'GET_MY_POSTS'
export const CLEAR_GET_MY_POSTS_RESPONSE = 'CLEAR_GET_MY_POSTS_RESPONSE'

export const DELETE_POST = 'DELETE_POST'
export const CLEAR_DELETE_POST_RESPONSE = 'CLEAR_DELETE_POST_RESPONSE'
