<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        Language::truncate();
        Schema::enableForeignKeyConstraints();

        $languages = [
            [
                'id'            =>  1,
                'iso2'          =>  "ab",
                'name'          =>  "Abkhazian",
                'name_native'   =>  "аҧсуа",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(1),
                'updated_at'    =>  now()->addSeconds(1),
            ],
            [
                'id'            =>  2,
                'iso2'          =>  "aa",
                'name'          =>  "Afar",
                'name_native'   =>  "Afaraf",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(2),
                'updated_at'    =>  now()->addSeconds(2),
            ],
            [
                'id'            =>  3,
                'iso2'          =>  "af",
                'name'          =>  "Afrikaans",
                'name_native'   =>  "Afrikaans",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(3),
                'updated_at'    =>  now()->addSeconds(3),
            ],
            [
                'id'            =>  4,
                'iso2'          =>  "ak",
                'name'          =>  "Akan",
                'name_native'   =>  "Akan",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(4),
                'updated_at'    =>  now()->addSeconds(4),
            ],
            [
                'id'            =>  5,
                'iso2'          =>  "sq",
                'name'          =>  "Albanian",
                'name_native'   =>  "Shqip",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(5),
                'updated_at'    =>  now()->addSeconds(5),
            ],
            [
                'id'            =>  6,
                'iso2'          =>  "am",
                'name'          =>  "Amharic",
                'name_native'   =>  "አማርኛ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(6),
                'updated_at'    =>  now()->addSeconds(6),
            ],
            [
                'id'            =>  7,
                'iso2'          =>  "ar",
                'name'          =>  "Arabic",
                'name_native'   =>  "العربية",
                'dir'           =>  "rtl",
                'created_at'    =>  now()->addSeconds(7),
                'updated_at'    =>  now()->addSeconds(7),
            ],
            [
                'id'            =>  8,
                'iso2'          =>  "an",
                'name'          =>  "Aragonese",
                'name_native'   =>  "Aragonés",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(8),
                'updated_at'    =>  now()->addSeconds(8),
            ],
            [
                'id'            =>  9,
                'iso2'          =>  "hy",
                'name'          =>  "Armenian",
                'name_native'   =>  "Հայերեն",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(9),
                'updated_at'    =>  now()->addSeconds(9),
            ],
            [
                'id'            =>  10,
                'iso2'          =>  "as",
                'name'          =>  "Assamese",
                'name_native'   =>  "অসমীয়া",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(10),
                'updated_at'    =>  now()->addSeconds(10),
            ],
            [
                'id'            =>  11,
                'iso2'          =>  "av",
                'name'          =>  "Avaric",
                'name_native'   =>  "авар мацӀ, магӀарул мацӀ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(11),
                'updated_at'    =>  now()->addSeconds(11),
            ],
            [
                'id'            =>  12,
                'iso2'          =>  "ae",
                'name'          =>  "Avestan",
                'name_native'   =>  "avesta",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(12),
                'updated_at'    =>  now()->addSeconds(12),
            ],
            [
                'id'            =>  13,
                'iso2'          =>  "ay",
                'name'          =>  "Aymara",
                'name_native'   =>  "aymar aru",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(13),
                'updated_at'    =>  now()->addSeconds(13),
            ],
            [
                'id'            =>  14,
                'iso2'          =>  "az",
                'name'          =>  "Azerbaijani",
                'name_native'   =>  "azərbaycan dili",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(14),
                'updated_at'    =>  now()->addSeconds(14),
            ],
            [
                'id'            =>  15,
                'iso2'          =>  "bm",
                'name'          =>  "Bambara",
                'name_native'   =>  "bamanankan",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(15),
                'updated_at'    =>  now()->addSeconds(15),
            ],
            [
                'id'            =>  16,
                'iso2'          =>  "ba",
                'name'          =>  "Bashkir",
                'name_native'   =>  "башҡорт теле",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(16),
                'updated_at'    =>  now()->addSeconds(16),
            ],
            [
                'id'            =>  17,
                'iso2'          =>  "eu",
                'name'          =>  "Basque",
                'name_native'   =>  "euskara, euskera",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(17),
                'updated_at'    =>  now()->addSeconds(17),
            ],
            [
                'id'            =>  18,
                'iso2'          =>  "be",
                'name'          =>  "Belarusian",
                'name_native'   =>  "Беларуская",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(18),
                'updated_at'    =>  now()->addSeconds(18),
            ],
            [
                'id'            =>  19,
                'iso2'          =>  "bn",
                'name'          =>  "Bengali",
                'name_native'   =>  "বাংলা",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(19),
                'updated_at'    =>  now()->addSeconds(19),
            ],
            [
                'id'            =>  20,
                'iso2'          =>  "bh",
                'name'          =>  "Bihari",
                'name_native'   =>  "भोजपुरी",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(20),
                'updated_at'    =>  now()->addSeconds(20),
            ],
            [
                'id'            =>  21,
                'iso2'          =>  "bi",
                'name'          =>  "Bislama",
                'name_native'   =>  "Bislama",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(21),
                'updated_at'    =>  now()->addSeconds(21),
            ],
            [
                'id'            =>  22,
                'iso2'          =>  "bs",
                'name'          =>  "Bosnian",
                'name_native'   =>  "bosanski jezik",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(22),
                'updated_at'    =>  now()->addSeconds(22),
            ],
            [
                'id'            =>  23,
                'iso2'          =>  "br",
                'name'          =>  "Breton",
                'name_native'   =>  "brezhoneg",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(23),
                'updated_at'    =>  now()->addSeconds(23),
            ],
            [
                'id'            =>  24,
                'iso2'          =>  "bg",
                'name'          =>  "Bulgarian",
                'name_native'   =>  "български език",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(24),
                'updated_at'    =>  now()->addSeconds(24),
            ],
            [
                'id'            =>  25,
                'iso2'          =>  "my",
                'name'          =>  "Burmese",
                'name_native'   =>  "ဗမာစာ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(25),
                'updated_at'    =>  now()->addSeconds(25),
            ],
            [
                'id'            =>  26,
                'iso2'          =>  "ca",
                'name'          =>  "Catalan; Valencian",
                'name_native'   =>  "Català",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(26),
                'updated_at'    =>  now()->addSeconds(26),
            ],
            [
                'id'            =>  27,
                'iso2'          =>  "ch",
                'name'          =>  "Chamorro",
                'name_native'   =>  "Chamoru",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(27),
                'updated_at'    =>  now()->addSeconds(27),
            ],
            [
                'id'            =>  28,
                'iso2'          =>  "ce",
                'name'          =>  "Chechen",
                'name_native'   =>  "нохчийн мотт",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(28),
                'updated_at'    =>  now()->addSeconds(28),
            ],
            [
                'id'            =>  29,
                'iso2'          =>  "ny",
                'name'          =>  "Chichewa; Chewa; Nyanja",
                'name_native'   =>  "chiCheŵa, chinyanja",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(29),
                'updated_at'    =>  now()->addSeconds(29),
            ],
            [
                'id'            =>  30,
                'iso2'          =>  "zh",
                'name'          =>  "Chinese",
                'name_native'   =>  "中文 (Zhōngwén), 汉语, 漢語",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(30),
                'updated_at'    =>  now()->addSeconds(30),
            ],
            [
                'id'            =>  31,
                'iso2'          =>  "cv",
                'name'          =>  "Chuvash",
                'name_native'   =>  "чӑваш чӗлхи",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(31),
                'updated_at'    =>  now()->addSeconds(31),
            ],
            [
                'id'            =>  32,
                'iso2'          =>  "kw",
                'name'          =>  "Cornish",
                'name_native'   =>  "Kernewek",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(32),
                'updated_at'    =>  now()->addSeconds(32),
            ],
            [
                'id'            =>  33,
                'iso2'          =>  "co",
                'name'          =>  "Corsican",
                'name_native'   =>  "corsu, lingua corsa",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(33),
                'updated_at'    =>  now()->addSeconds(33),
            ],
            [
                'id'            =>  34,
                'iso2'          =>  "cr",
                'name'          =>  "Cree",
                'name_native'   =>  "ᓀᐦᐃᔭᐍᐏᐣ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(34),
                'updated_at'    =>  now()->addSeconds(34),
            ],
            [
                'id'            =>  35,
                'iso2'          =>  "cs",
                'name'          =>  "Croatian",
                'name_native'   =>  "hrvatski",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(35),
                'updated_at'    =>  now()->addSeconds(35),
            ],
            [
                'id'            =>  36,
                'iso2'          =>  "aa",
                'name'          =>  "Czech",
                'name_native'   =>  "česky, čeština",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(36),
                'updated_at'    =>  now()->addSeconds(36),
            ],
            [
                'id'            =>  37,
                'iso2'          =>  "da",
                'name'          =>  "Danish",
                'name_native'   =>  "dansk",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(37),
                'updated_at'    =>  now()->addSeconds(37),
            ],
            [
                'id'            =>  38,
                'iso2'          =>  "dv",
                'name'          =>  "Divehi; Dhivehi; Maldivian;",
                'name_native'   =>  "ދިވެހި",
                'dir'           =>  "rtl",
                'created_at'    =>  now()->addSeconds(38),
                'updated_at'    =>  now()->addSeconds(38),
            ],
            [
                'id'            =>  39,
                'iso2'          =>  "nl",
                'name'          =>  "Dutch",
                'name_native'   =>  "Nederlands, Vlaams",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(39),
                'updated_at'    =>  now()->addSeconds(39),
            ],
            [
                'id'            =>  40,
                'iso2'          =>  "en",
                'name'          =>  "English",
                'name_native'   =>  "English",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(40),
                'updated_at'    =>  now()->addSeconds(40),
            ],
            [
                'id'            =>  41,
                'iso2'          =>  "eo",
                'name'          =>  "Esperanto",
                'name_native'   =>  "Esperanto",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(41),
                'updated_at'    =>  now()->addSeconds(41),
            ],
            [
                'id'            =>  42,
                'iso2'          =>  "et",
                'name'          =>  "Estonian",
                'name_native'   =>  "eesti, eesti keel",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(42),
                'updated_at'    =>  now()->addSeconds(42),
            ],
            [
                'id'            =>  43,
                'iso2'          =>  "ee",
                'name'          =>  "Ewe",
                'name_native'   =>  "Eʋegbe",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(43),
                'updated_at'    =>  now()->addSeconds(43),
            ],
            [
                'id'            =>  44,
                'iso2'          =>  "fo",
                'name'          =>  "Faroese",
                'name_native'   =>  "føroyskt",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(44),
                'updated_at'    =>  now()->addSeconds(44),
            ],
            [
                'id'            =>  45,
                'iso2'          =>  "fj",
                'name'          =>  "Fijian",
                'name_native'   =>  "vosa Vakaviti",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(45),
                'updated_at'    =>  now()->addSeconds(45),
            ],
            [
                'id'            =>  46,
                'iso2'          =>  "fi",
                'name'          =>  "Finnish",
                'name_native'   =>  "suomi, suomen kieli",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(46),
                'updated_at'    =>  now()->addSeconds(46),
            ],
            [
                'id'            =>  47,
                'iso2'          =>  "fr",
                'name'          =>  "French",
                'name_native'   =>  "français",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(47),
                'updated_at'    =>  now()->addSeconds(47),
            ],
            [
                'id'            =>  48,
                'iso2'          =>  "ff",
                'name'          =>  "Fula; Fulah; Pulaar; Pular",
                'name_native'   =>  "Fulfulde, Pulaar, Pular",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(48),
                'updated_at'    =>  now()->addSeconds(48),
            ],
            [
                'id'            =>  49,
                'iso2'          =>  "gl",
                'name'          =>  "Galician",
                'name_native'   =>  "Galego",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(49),
                'updated_at'    =>  now()->addSeconds(49),
            ],
            [
                'id'            =>  50,
                'iso2'          =>  "ka",
                'name'          =>  "Georgian",
                'name_native'   =>  "ქართული",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(50),
                'updated_at'    =>  now()->addSeconds(50),
            ],
            [
                'id'            =>  51,
                'iso2'          =>  "de",
                'name'          =>  "German",
                'name_native'   =>  "Deutsch",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(51),
                'updated_at'    =>  now()->addSeconds(51),
            ],
            [
                'id'            =>  52,
                'iso2'          =>  "el",
                'name'          =>  "Greek, Modern",
                'name_native'   =>  "Ελληνικά",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(52),
                'updated_at'    =>  now()->addSeconds(52),
            ],
            [
                'id'            =>  53,
                'iso2'          =>  "gn",
                'name'          =>  "Guaraní",
                'name_native'   =>  "Avañeẽ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(53),
                'updated_at'    =>  now()->addSeconds(53),
            ],
            [
                'id'            =>  54,
                'iso2'          =>  "gu",
                'name'          =>  "Gujarati",
                'name_native'   =>  "ગુજરાતી",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(54),
                'updated_at'    =>  now()->addSeconds(54),
            ],
            [
                'id'            =>  55,
                'iso2'          =>  "ht",
                'name'          =>  "Haitian; Haitian Creole",
                'name_native'   =>  "Kreyòl ayisyen",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(55),
                'updated_at'    =>  now()->addSeconds(55),
            ],
            [
                'id'            =>  56,
                'iso2'          =>  "ha",
                'name'          =>  "Hausa",
                'name_native'   =>  "Hausa, هَوُسَ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(56),
                'updated_at'    =>  now()->addSeconds(56),
            ],
            [
                'id'            =>  57,
                'iso2'          =>  "he",
                'name'          =>  "Hebrew",
                'name_native'   =>  "עברית",
                'dir'           =>  "rtl",
                'created_at'    =>  now()->addSeconds(57),
                'updated_at'    =>  now()->addSeconds(57),
            ],
            [
                'id'            =>  58,
                'iso2'          =>  "iw",
                'name'          =>  "Hebrew",
                'name_native'   =>  "עברית",
                'dir'           =>  "rtl",
                'created_at'    =>  now()->addSeconds(58),
                'updated_at'    =>  now()->addSeconds(58),
            ],
            [
                'id'            =>  59,
                'iso2'          =>  "hz",
                'name'          =>  "Herero",
                'name_native'   =>  "Otjiherero",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(59),
                'updated_at'    =>  now()->addSeconds(59),
            ],
            [
                'id'            =>  60,
                'iso2'          =>  "hi",
                'name'          =>  "Hindi",
                'name_native'   =>  "हिन्दी, हिंदी",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(60),
                'updated_at'    =>  now()->addSeconds(60),
            ],
            [
                'id'            =>  61,
                'iso2'          =>  "ho",
                'name'          =>  "Hiri Motu",
                'name_native'   =>  "Hiri Motu",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(61),
                'updated_at'    =>  now()->addSeconds(61),
            ],
            [
                'id'            =>  62,
                'iso2'          =>  "hu",
                'name'          =>  "Hungarian",
                'name_native'   =>  "Magyar",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(62),
                'updated_at'    =>  now()->addSeconds(62),
            ],
            [
                'id'            =>  63,
                'iso2'          =>  "ia",
                'name'          =>  "Interlingua",
                'name_native'   =>  "Interlingua",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(63),
                'updated_at'    =>  now()->addSeconds(63),
            ],
            [
                'id'            =>  64,
                'iso2'          =>  "id",
                'name'          =>  "Indonesian",
                'name_native'   =>  "Bahasa Indonesia",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(64),
                'updated_at'    =>  now()->addSeconds(64),
            ],
            [
                'id'            =>  65,
                'iso2'          =>  "ie",
                'name'          =>  "Interlingue",
                'name_native'   =>  "Originally called Occidental; then Interlingue after WWII",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(65),
                'updated_at'    =>  now()->addSeconds(65),
            ],
            [
                'id'            =>  66,
                'iso2'          =>  "ga",
                'name'          =>  "Irish",
                'name_native'   =>  "Gaeilge",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(66),
                'updated_at'    =>  now()->addSeconds(66),
            ],
            [
                'id'            =>  67,
                'iso2'          =>  "ig",
                'name'          =>  "Igbo",
                'name_native'   =>  "Asụsụ Igbo",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(67),
                'updated_at'    =>  now()->addSeconds(67),
            ],
            [
                'id'            =>  68,
                'iso2'          =>  "ik",
                'name'          =>  "Inupiaq",
                'name_native'   =>  "Iñupiaq, Iñupiatun",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(68),
                'updated_at'    =>  now()->addSeconds(68),
            ],
            [
                'id'            =>  69,
                'iso2'          =>  "io",
                'name'          =>  "Ido",
                'name_native'   =>  "Ido",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(69),
                'updated_at'    =>  now()->addSeconds(69),
            ],
            [
                'id'            =>  70,
                'iso2'          =>  "is",
                'name'          =>  "Icelandic",
                'name_native'   =>  "Íslenska",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(70),
                'updated_at'    =>  now()->addSeconds(70),
            ],
            [
                'id'            =>  71,
                'iso2'          =>  "it",
                'name'          =>  "Italian",
                'name_native'   =>  "Italiano",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(71),
                'updated_at'    =>  now()->addSeconds(71),
            ],
            [
                'id'            =>  72,
                'iso2'          =>  "iu",
                'name'          =>  "Inuktitut",
                'name_native'   =>  "ᐃᓄᒃᑎᑐᑦ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(72),
                'updated_at'    =>  now()->addSeconds(72),
            ],
            [
                'id'            =>  73,
                'iso2'          =>  "ja",
                'name'          =>  "Japanese",
                'name_native'   =>  "日本語 (にほんご／にっぽんご)",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(73),
                'updated_at'    =>  now()->addSeconds(73),
            ],
            [
                'id'            =>  74,
                'iso2'          =>  "jv",
                'name'          =>  "Javanese",
                'name_native'   =>  "basa Jawa",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(74),
                'updated_at'    =>  now()->addSeconds(74),
            ],
            [
                'id'            =>  75,
                'iso2'          =>  "kl",
                'name'          =>  "Kalaallisut, Greenlandic",
                'name_native'   =>  "kalaallisut, kalaallit oqaasii",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(75),
                'updated_at'    =>  now()->addSeconds(75),
            ],
            [
                'id'            =>  76,
                'iso2'          =>  "kn",
                'name'          =>  "Kannada",
                'name_native'   =>  "ಕನ್ನಡ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(76),
                'updated_at'    =>  now()->addSeconds(76),
            ],
            [
                'id'            =>  77,
                'iso2'          =>  "kr",
                'name'          =>  "Kanuri",
                'name_native'   =>  "Kanuri",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(77),
                'updated_at'    =>  now()->addSeconds(77),
            ],
            [
                'id'            =>  78,
                'iso2'          =>  "ks",
                'name'          =>  "Kashmiri",
                'name_native'   =>  "कश्मीरी, كشميري‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(78),
                'updated_at'    =>  now()->addSeconds(78),
            ],
            [
                'id'            =>  79,
                'iso2'          =>  "kk",
                'name'          =>  "Kazakh",
                'name_native'   =>  "Қазақ тілі",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(79),
                'updated_at'    =>  now()->addSeconds(79),
            ],
            [
                'id'            =>  80,
                'iso2'          =>  "km",
                'name'          =>  "Khmer",
                'name_native'   =>  "ភាសាខ្មែរ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(80),
                'updated_at'    =>  now()->addSeconds(80),
            ],
            [
                'id'            =>  81,
                'iso2'          =>  "ki",
                'name'          =>  "Kikuyu, Gikuyu",
                'name_native'   =>  "Gĩkũyũ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(81),
                'updated_at'    =>  now()->addSeconds(81),
            ],
            [
                'id'            =>  82,
                'iso2'          =>  "rw",
                'name'          =>  "Kinyarwanda",
                'name_native'   =>  "Ikinyarwanda",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(82),
                'updated_at'    =>  now()->addSeconds(82),
            ],
            [
                'id'            =>  83,
                'iso2'          =>  "ky",
                'name'          =>  "Kirghiz, Kyrgyz",
                'name_native'   =>  "кыргыз тили",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(83),
                'updated_at'    =>  now()->addSeconds(83),
            ],
            [
                'id'            =>  84,
                'iso2'          =>  "kv",
                'name'          =>  "Komi",
                'name_native'   =>  "коми кыв",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(84),
                'updated_at'    =>  now()->addSeconds(84),
            ],
            [
                'id'            =>  85,
                'iso2'          =>  "kg",
                'name'          =>  "Kongo",
                'name_native'   =>  "KiKongo",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(85),
                'updated_at'    =>  now()->addSeconds(85),
            ],
            [
                'id'            =>  86,
                'iso2'          =>  "ko",
                'name'          =>  "Korean",
                'name_native'   =>  "한국어 (韓國語), 조선말 (朝鮮語)",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(86),
                'updated_at'    =>  now()->addSeconds(86),
            ],
            [
                'id'            =>  87,
                'iso2'          =>  "ku",
                'name'          =>  "Kurdish",
                'name_native'   =>  "Kurdî, كوردی‎",
                'dir'           =>  "rtl",
                'created_at'    =>  now()->addSeconds(87),
                'updated_at'    =>  now()->addSeconds(87),
            ],
            [
                'id'            =>  88,
                'iso2'          =>  "kj",
                'name'          =>  "Kwanyama, Kuanyama",
                'name_native'   =>  "Kuanyama",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(88),
                'updated_at'    =>  now()->addSeconds(88),
            ],
            [
                'id'            =>  89,
                'iso2'          =>  "la",
                'name'          =>  "Latin",
                'name_native'   =>  "latine, lingua latina",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(89),
                'updated_at'    =>  now()->addSeconds(89),
            ],
            [
                'id'            =>  90,
                'iso2'          =>  "lb",
                'name'          =>  "Luxembourgish, Letzeburgesch",
                'name_native'   =>  "Lëtzebuergesch",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(90),
                'updated_at'    =>  now()->addSeconds(90),
            ],
            [
                'id'            =>  91,
                'iso2'          =>  "lg",
                'name'          =>  "Luganda",
                'name_native'   =>  "Luganda",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(91),
                'updated_at'    =>  now()->addSeconds(91),
            ],
            [
                'id'            =>  92,
                'iso2'          =>  "li",
                'name'          =>  "Limburgish, Limburgan, Limburger",
                'name_native'   =>  "Limburgs",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(92),
                'updated_at'    =>  now()->addSeconds(92),
            ],
            [
                'id'            =>  93,
                'iso2'          =>  "ln",
                'name'          =>  "Lingala",
                'name_native'   =>  "Lingála",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(93),
                'updated_at'    =>  now()->addSeconds(93),
            ],
            [
                'id'            =>  94,
                'iso2'          =>  "lo",
                'name'          =>  "Lao",
                'name_native'   =>  "ພາສາລາວ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(94),
                'updated_at'    =>  now()->addSeconds(94),
            ],
            [
                'id'            =>  95,
                'iso2'          =>  "lt",
                'name'          =>  "Lithuanian",
                'name_native'   =>  "lietuvių kalba",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(95),
                'updated_at'    =>  now()->addSeconds(95),
            ],
            [
                'id'            =>  96,
                'iso2'          =>  "lu",
                'name'          =>  "Luba-Katanga",
                'name_native'   =>  "Kiluba",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(96),
                'updated_at'    =>  now()->addSeconds(96),
            ],
            [
                'id'            =>  97,
                'iso2'          =>  "lv",
                'name'          =>  "Latvian",
                'name_native'   =>  "latviešu valoda",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(97),
                'updated_at'    =>  now()->addSeconds(97),
            ],
            [
                'id'            =>  98,
                'iso2'          =>  "gv",
                'name'          =>  "Manx",
                'name_native'   =>  "Gaelg, Gailck",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(98),
                'updated_at'    =>  now()->addSeconds(98),
            ],
            [
                'id'            =>  99,
                'iso2'          =>  "mk",
                'name'          =>  "Macedonian",
                'name_native'   =>  "македонски јазик",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(99),
                'updated_at'    =>  now()->addSeconds(99),
            ],
            [
                'id'            =>  100,
                'iso2'          =>  "mg",
                'name'          =>  "Malagasy",
                'name_native'   =>  "Malagasy fiteny",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(100),
                'updated_at'    =>  now()->addSeconds(100),
            ],
            [
                'id'            =>  101,
                'iso2'          =>  "ms",
                'name'          =>  "Malay",
                'name_native'   =>  "bahasa Melayu, بهاس ملايو‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(101),
                'updated_at'    =>  now()->addSeconds(101),
            ],
            [
                'id'            =>  102,
                'iso2'          =>  "ml",
                'name'          =>  "Malayalam",
                'name_native'   =>  "മലയാളം",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(102),
                'updated_at'    =>  now()->addSeconds(102),
            ],
            [
                'id'            =>  103,
                'iso2'          =>  "mt",
                'name'          =>  "Maltese",
                'name_native'   =>  "Malti",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(103),
                'updated_at'    =>  now()->addSeconds(103),
            ],
            [
                'id'            =>  104,
                'iso2'          =>  "mi",
                'name'          =>  "Māori",
                'name_native'   =>  "te reo Māori",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(104),
                'updated_at'    =>  now()->addSeconds(104),
            ],
            [
                'id'            =>  105,
                'iso2'          =>  "mr",
                'name'          =>  "Marathi (Marāṭhī)",
                'name_native'   =>  "मराठी",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(105),
                'updated_at'    =>  now()->addSeconds(105),
            ],
            [
                'id'            =>  106,
                'iso2'          =>  "mh",
                'name'          =>  "Marshallese",
                'name_native'   =>  "Kajin M̧ajeļ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(106),
                'updated_at'    =>  now()->addSeconds(106),
            ],
            [
                'id'            =>  107,
                'iso2'          =>  "mn",
                'name'          =>  "Mongolian",
                'name_native'   =>  "монгол",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(107),
                'updated_at'    =>  now()->addSeconds(107),
            ],
            [
                'id'            =>  108,
                'iso2'          =>  "na",
                'name'          =>  "Nauru",
                'name_native'   =>  "Ekakairũ Naoero",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(108),
                'updated_at'    =>  now()->addSeconds(108),
            ],
            [
                'id'            =>  109,
                'iso2'          =>  "nv",
                'name'          =>  "Navajo, Navaho",
                'name_native'   =>  "Diné bizaad, Dinékʼehǰí",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(109),
                'updated_at'    =>  now()->addSeconds(109),
            ],
            [
                'id'            =>  110,
                'iso2'          =>  "nb",
                'name'          =>  "Norwegian Bokmål",
                'name_native'   =>  "Norsk bokmål",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(110),
                'updated_at'    =>  now()->addSeconds(110),
            ],
            [
                'id'            =>  111,
                'iso2'          =>  "nd",
                'name'          =>  "North Ndebele",
                'name_native'   =>  "isiNdebele",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(111),
                'updated_at'    =>  now()->addSeconds(111),
            ],
            [
                'id'            =>  112,
                'iso2'          =>  "ne",
                'name'          =>  "Nepali",
                'name_native'   =>  "नेपाली",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(112),
                'updated_at'    =>  now()->addSeconds(112),
            ],
            [
                'id'            =>  113,
                'iso2'          =>  "ng",
                'name'          =>  "Ndonga",
                'name_native'   =>  "Owambo",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(113),
                'updated_at'    =>  now()->addSeconds(113),
            ],
            [
                'id'            =>  114,
                'iso2'          =>  "nn",
                'name'          =>  "Norwegian Nynorsk",
                'name_native'   =>  "Norsk nynorsk",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(114),
                'updated_at'    =>  now()->addSeconds(114),
            ],
            [
                'id'            =>  115,
                'iso2'          =>  "no",
                'name'          =>  "Norwegian",
                'name_native'   =>  "Norsk",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(115),
                'updated_at'    =>  now()->addSeconds(115),
            ],
            [
                'id'            =>  116,
                'iso2'          =>  "ii",
                'name'          =>  "Nuosu",
                'name_native'   =>  "ꆈꌠ꒿ Nuosuhxop",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(116),
                'updated_at'    =>  now()->addSeconds(116),
            ],
            [
                'id'            =>  117,
                'iso2'          =>  "nr",
                'name'          =>  "South Ndebele",
                'name_native'   =>  "isiNdebele",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(117),
                'updated_at'    =>  now()->addSeconds(117),
            ],
            [
                'id'            =>  118,
                'iso2'          =>  "oc",
                'name'          =>  "Occitan",
                'name_native'   =>  "Occitan",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(118),
                'updated_at'    =>  now()->addSeconds(118),
            ],
            [
                'id'            =>  119,
                'iso2'          =>  "oj",
                'name'          =>  "Ojibwe, Ojibwa",
                'name_native'   =>  "ᐊᓂᔑᓈᐯᒧᐎᓐ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(119),
                'updated_at'    =>  now()->addSeconds(119),
            ],
            [
                'id'            =>  120,
                'iso2'          =>  "cu",
                'name'          =>  "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
                'name_native'   =>  "ѩзыкъ словѣньскъ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(120),
                'updated_at'    =>  now()->addSeconds(120),
            ],
            [
                'id'            =>  121,
                'iso2'          =>  "om",
                'name'          =>  "Oromo",
                'name_native'   =>  "Afaan Oromoo",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(121),
                'updated_at'    =>  now()->addSeconds(121),
            ],
            [
                'id'            =>  122,
                'iso2'          =>  "or",
                'name'          =>  "Oriya",
                'name_native'   =>  "ଓଡ଼ିଆ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(122),
                'updated_at'    =>  now()->addSeconds(122),
            ],
            [
                'id'            =>  123,
                'iso2'          =>  "os",
                'name'          =>  "Ossetian, Ossetic",
                'name_native'   =>  "ирон æвзаг",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(123),
                'updated_at'    =>  now()->addSeconds(123),
            ],
            [
                'id'            =>  124,
                'iso2'          =>  "pa",
                'name'          =>  "Panjabi, Punjabi",
                'name_native'   =>  "ਪੰਜਾਬੀ, پنجابی‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(124),
                'updated_at'    =>  now()->addSeconds(124),
            ],
            [
                'id'            =>  125,
                'iso2'          =>  "pi",
                'name'          =>  "Pāli",
                'name_native'   =>  "पाऴि",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(125),
                'updated_at'    =>  now()->addSeconds(125),
            ],
            [
                'id'            =>  126,
                'iso2'          =>  "fa",
                'name'          =>  "Persian",
                'name_native'   =>  "فارسی",
                'dir'           =>  "rtl",
                'created_at'    =>  now()->addSeconds(126),
                'updated_at'    =>  now()->addSeconds(126),
            ],
            [
                'id'            =>  127,
                'iso2'          =>  "pl",
                'name'          =>  "Polish",
                'name_native'   =>  "polski",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(127),
                'updated_at'    =>  now()->addSeconds(127),
            ],
            [
                'id'            =>  128,
                'iso2'          =>  "ps",
                'name'          =>  "Pashto, Pushto",
                'name_native'   =>  "پښتو",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(128),
                'updated_at'    =>  now()->addSeconds(128),
            ],
            [
                'id'            =>  129,
                'iso2'          =>  "pt",
                'name'          =>  "Portuguese",
                'name_native'   =>  "Português",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(129),
                'updated_at'    =>  now()->addSeconds(129),
            ],
            [
                'id'            =>  130,
                'iso2'          =>  "qu",
                'name'          =>  "Quechua",
                'name_native'   =>  "Runa Simi, Kichwa",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(130),
                'updated_at'    =>  now()->addSeconds(130),
            ],
            [
                'id'            =>  131,
                'iso2'          =>  "rm",
                'name'          =>  "Romansh",
                'name_native'   =>  "rumantsch grischun",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(131),
                'updated_at'    =>  now()->addSeconds(131),
            ],
            [
                'id'            =>  132,
                'iso2'          =>  "rn",
                'name'          =>  "Kirundi",
                'name_native'   =>  "kiRundi",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(132),
                'updated_at'    =>  now()->addSeconds(132),
            ],
            [
                'id'            =>  133,
                'iso2'          =>  "ro",
                'name'          =>  "Romanian",
                'name_native'   =>  "română",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(133),
                'updated_at'    =>  now()->addSeconds(133),
            ],
            [
                'id'            =>  134,
                'iso2'          =>  "ru",
                'name'          =>  "Russian",
                'name_native'   =>  "русский язык",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(134),
                'updated_at'    =>  now()->addSeconds(134),
            ],
            [
                'id'            =>  135,
                'iso2'          =>  "sa",
                'name'          =>  "Sanskrit (Saṁskṛta)",
                'name_native'   =>  "संस्कृतम्",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(135),
                'updated_at'    =>  now()->addSeconds(135),
            ],
            [
                'id'            =>  136,
                'iso2'          =>  "sc",
                'name'          =>  "Sardinian",
                'name_native'   =>  "sardu",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(136),
                'updated_at'    =>  now()->addSeconds(136),
            ],
            [
                'id'            =>  137,
                'iso2'          =>  "sd",
                'name'          =>  "Sindhi",
                'name_native'   =>  "सिन्धी, سنڌي، سندھی‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(137),
                'updated_at'    =>  now()->addSeconds(137),
            ],
            [
                'id'            =>  138,
                'iso2'          =>  "se",
                'name'          =>  "Northern Sami",
                'name_native'   =>  "Davvisámegiella",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(138),
                'updated_at'    =>  now()->addSeconds(138),
            ],
            [
                'id'            =>  139,
                'iso2'          =>  "sm",
                'name'          =>  "Samoan",
                'name_native'   =>  "gagana faa Samoa",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(139),
                'updated_at'    =>  now()->addSeconds(139),
            ],
            [
                'id'            =>  140,
                'iso2'          =>  "sg",
                'name'          =>  "Sango",
                'name_native'   =>  "yângâ tî sängö",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(140),
                'updated_at'    =>  now()->addSeconds(140),
            ],
            [
                'id'            =>  141,
                'iso2'          =>  "sr",
                'name'          =>  "Serbian",
                'name_native'   =>  "српски језик",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(141),
                'updated_at'    =>  now()->addSeconds(141),
            ],
            [
                'id'            =>  142,
                'iso2'          =>  "gd",
                'name'          =>  "Scottish Gaelic; Gaelic",
                'name_native'   =>  "Gàidhlig",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(142),
                'updated_at'    =>  now()->addSeconds(142),
            ],
            [
                'id'            =>  143,
                'iso2'          =>  "sn",
                'name'          =>  "Shona",
                'name_native'   =>  "chiShona",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(143),
                'updated_at'    =>  now()->addSeconds(143),
            ],
            [
                'id'            =>  144,
                'iso2'          =>  "si",
                'name'          =>  "Sinhala, Sinhalese",
                'name_native'   =>  "සිංහල",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(144),
                'updated_at'    =>  now()->addSeconds(144),
            ],
            [
                'id'            =>  145,
                'iso2'          =>  "sk",
                'name'          =>  "Slovak",
                'name_native'   =>  "slovenčina",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(145),
                'updated_at'    =>  now()->addSeconds(145),
            ],
            [
                'id'            =>  146,
                'iso2'          =>  "sl",
                'name'          =>  "Slovene",
                'name_native'   =>  "slovenščina",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(146),
                'updated_at'    =>  now()->addSeconds(146),
            ],
            [
                'id'            =>  147,
                'iso2'          =>  "so",
                'name'          =>  "Somali",
                'name_native'   =>  "Soomaaliga, af Soomaali",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(147),
                'updated_at'    =>  now()->addSeconds(147),
            ],
            [
                'id'            =>  148,
                'iso2'          =>  "st",
                'name'          =>  "Southern Sotho",
                'name_native'   =>  "Sesotho",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(148),
                'updated_at'    =>  now()->addSeconds(148),
            ],
            [
                'id'            =>  149,
                'iso2'          =>  "es",
                'name'          =>  "Spanish; Castilian",
                'name_native'   =>  "español, castellano",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(149),
                'updated_at'    =>  now()->addSeconds(149),
            ],
            [
                'id'            =>  150,
                'iso2'          =>  "su",
                'name'          =>  "Sundanese",
                'name_native'   =>  "Basa Sunda",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(150),
                'updated_at'    =>  now()->addSeconds(150),
            ],
            [
                'id'            =>  151,
                'iso2'          =>  "sw",
                'name'          =>  "Swahili",
                'name_native'   =>  "Kiswahili",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(151),
                'updated_at'    =>  now()->addSeconds(151),
            ],
            [
                'id'            =>  152,
                'iso2'          =>  "ss",
                'name'          =>  "Swati",
                'name_native'   =>  "SiSwati",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(152),
                'updated_at'    =>  now()->addSeconds(152),
            ],
            [
                'id'            =>  153,
                'iso2'          =>  "sv",
                'name'          =>  "Swedish",
                'name_native'   =>  "svenska",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(153),
                'updated_at'    =>  now()->addSeconds(153),
            ],
            [
                'id'            =>  154,
                'iso2'          =>  "ta",
                'name'          =>  "Tamil",
                'name_native'   =>  "தமிழ்",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(154),
                'updated_at'    =>  now()->addSeconds(154),
            ],
            [
                'id'            =>  155,
                'iso2'          =>  "te",
                'name'          =>  "Telugu",
                'name_native'   =>  "తెలుగు",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(155),
                'updated_at'    =>  now()->addSeconds(155),
            ],
            [
                'id'            =>  156,
                'iso2'          =>  "tg",
                'name'          =>  "Tajik",
                'name_native'   =>  "тоҷикӣ, toğikī, تاجیکی‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(156),
                'updated_at'    =>  now()->addSeconds(156),
            ],
            [
                'id'            =>  157,
                'iso2'          =>  "th",
                'name'          =>  "Thai",
                'name_native'   =>  "ไทย",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(157),
                'updated_at'    =>  now()->addSeconds(157),
            ],
            [
                'id'            =>  158,
                'iso2'          =>  "ti",
                'name'          =>  "Tigrinya",
                'name_native'   =>  "ትግርኛ",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(158),
                'updated_at'    =>  now()->addSeconds(158),
            ],
            [
                'id'            =>  159,
                'iso2'          =>  "bo",
                'name'          =>  "Tibetan Standard, Tibetan, Central",
                'name_native'   =>  "བོད་ཡིག",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(159),
                'updated_at'    =>  now()->addSeconds(159),
            ],
            [
                'id'            =>  160,
                'iso2'          =>  "tk",
                'name'          =>  "Turkmen",
                'name_native'   =>  "Türkmen, Түркмен",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(160),
                'updated_at'    =>  now()->addSeconds(160),
            ],
            [
                'id'            =>  161,
                'iso2'          =>  "tl",
                'name'          =>  "Tagalog",
                'name_native'   =>  "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(161),
                'updated_at'    =>  now()->addSeconds(161),
            ],
            [
                'id'            =>  162,
                'iso2'          =>  "tn",
                'name'          =>  "Tswana",
                'name_native'   =>  "Setswana",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(162),
                'updated_at'    =>  now()->addSeconds(162),
            ],
            [
                'id'            =>  163,
                'iso2'          =>  "to",
                'name'          =>  "Tonga (Tonga Islands)",
                'name_native'   =>  "faka Tonga",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(163),
                'updated_at'    =>  now()->addSeconds(163),
            ],
            [
                'id'            =>  164,
                'iso2'          =>  "tr",
                'name'          =>  "Turkish",
                'name_native'   =>  "Türkçe",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(164),
                'updated_at'    =>  now()->addSeconds(164),
            ],
            [
                'id'            =>  165,
                'iso2'          =>  "ts",
                'name'          =>  "Tsonga",
                'name_native'   =>  "Xitsonga",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(165),
                'updated_at'    =>  now()->addSeconds(165),
            ],
            [
                'id'            =>  166,
                'iso2'          =>  "tt",
                'name'          =>  "Tatar",
                'name_native'   =>  "татарча, tatarça, تاتارچا‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(166),
                'updated_at'    =>  now()->addSeconds(166),
            ],
            [
                'id'            =>  167,
                'iso2'          =>  "tw",
                'name'          =>  "Twi",
                'name_native'   =>  "Twi",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(167),
                'updated_at'    =>  now()->addSeconds(167),
            ],
            [
                'id'            =>  168,
                'iso2'          =>  "ty",
                'name'          =>  "Tahitian",
                'name_native'   =>  "Reo Tahiti",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(168),
                'updated_at'    =>  now()->addSeconds(168),
            ],
            [
                'id'            =>  169,
                'iso2'          =>  "ug",
                'name'          =>  "Uighur, Uyghur",
                'name_native'   =>  "Uyƣurqə, ئۇيغۇرچە‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(169),
                'updated_at'    =>  now()->addSeconds(169),
            ],
            [
                'id'            =>  170,
                'iso2'          =>  "uk",
                'name'          =>  "Ukrainian",
                'name_native'   =>  "українська",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(170),
                'updated_at'    =>  now()->addSeconds(170),
            ],
            [
                'id'            =>  171,
                'iso2'          =>  "ur",
                'name'          =>  "Urdu",
                'name_native'   =>  "اردو",
                'dir'           =>  "rtl",
                'created_at'    =>  now()->addSeconds(171),
                'updated_at'    =>  now()->addSeconds(171),
            ],
            [
                'id'            =>  172,
                'iso2'          =>  "uz",
                'name'          =>  "Uzbek",
                'name_native'   =>  "zbek, Ўзбек, أۇزبېك‎",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(172),
                'updated_at'    =>  now()->addSeconds(172),
            ],
            [
                'id'            =>  173,
                'iso2'          =>  "ve",
                'name'          =>  "Venda",
                'name_native'   =>  "Tshivenḓa",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(173),
                'updated_at'    =>  now()->addSeconds(173),
            ],
            [
                'id'            =>  174,
                'iso2'          =>  "vi",
                'name'          =>  "Vietnamese",
                'name_native'   =>  "Tiếng Việt",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(174),
                'updated_at'    =>  now()->addSeconds(174),
            ],
            [
                'id'            =>  175,
                'iso2'          =>  "vo",
                'name'          =>  "Volapük",
                'name_native'   =>  "Volapük",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(175),
                'updated_at'    =>  now()->addSeconds(175),
            ],
            [
                'id'            =>  176,
                'iso2'          =>  "wa",
                'name'          =>  "Walloon",
                'name_native'   =>  "Walon",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(176),
                'updated_at'    =>  now()->addSeconds(176),
            ],
            [
                'id'            =>  177,
                'iso2'          =>  "cy",
                'name'          =>  "Welsh",
                'name_native'   =>  "Cymraeg",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(177),
                'updated_at'    =>  now()->addSeconds(177),
            ],
            [
                'id'            =>  178,
                'iso2'          =>  "wo",
                'name'          =>  "Wolof",
                'name_native'   =>  "Wollof",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(178),
                'updated_at'    =>  now()->addSeconds(178),
            ],
            [
                'id'            =>  179,
                'iso2'          =>  "fy",
                'name'          =>  "Western Frisian",
                'name_native'   =>  "Frysk",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(179),
                'updated_at'    =>  now()->addSeconds(179),
            ],
            [
                'id'            =>  180,
                'iso2'          =>  "xh",
                'name'          =>  "Xhosa",
                'name_native'   =>  "isiXhosa",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(180),
                'updated_at'    =>  now()->addSeconds(180),
            ],
            [
                'id'            =>  181,
                'iso2'          =>  "yi",
                'name'          =>  "Yiddish",
                'name_native'   =>  "ייִדיש",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(181),
                'updated_at'    =>  now()->addSeconds(181),
            ],
            [
                'id'            =>  182,
                'iso2'          =>  "yo",
                'name'          =>  "Yoruba",
                'name_native'   =>  "Yorùbá",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(182),
                'updated_at'    =>  now()->addSeconds(182),
            ],
            [
                'id'            =>  183,
                'iso2'          =>  "za",
                'name'          =>  "Zhuang, Chuang",
                'name_native'   =>  "Saɯ cueŋƅ, Saw cuengh",
                'dir'           =>  "ltr",
                'created_at'    =>  now()->addSeconds(183),
                'updated_at'    =>  now()->addSeconds(183),
            ],
        ];

        $language_chunks = array_chunk($languages, 2000);
        foreach ($language_chunks as $language) {
            Language::insert($language);
        }
    }
}
