FROM public.ecr.aws/d7h0j7s7/cric-node:16-alpine

WORKDIR /app

COPY . /app
COPY .npm /root/.npm

RUN npm ci --production --legacy-peer-deps
RUN pm2 install pm2-metrics

ENV NODE_ENV dev

EXPOSE 9209
EXPOSE 4004

CMD ["pm2-runtime", "start", "index.js"]
