kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: "crictracker-redis-dev-headless.dev.svc.cluster.local"
  REDIS_PORT: "6379"
  NODE_ENV: dev-prod
  PORT: "4006"
  SUPPORT_EMAIL: 'Crictracker@yudizproject.tk'
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: 'admin-media-cdn.crictracker.com'
  S3_BUCKET_URL: 'https://admin-media-cdn.crictracker.com.s3.ap-south-1.amazonaws.com/'
  S3_BUCKET_PROFILE_PATH: profile-pic/
  S3_BUCKET_KYC_PATH: kyc/pan
  S3_BUCKET_FB_PATH: fb/
  S3_BUCKET_TWITTER_PATH: twitter/
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: media/featureimage
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: media/thumbnailimage
  # AUTH_SUBGRAPH_URL: 'https://auth-dev.beta.crictracker.com/'
  AUTH_SUBGRAPH_URL: http://crictracker-authentication-dev-internal.dev.svc.cluster.local
  SENTRY_DSN: 'https://c7afbdb451d74161b1929f2af68253ba@o992135.ingest.sentry.io/6073494'
  ENTITY_SPORT_BASE_URL: 'https://rest.entitysport.com/v2'
  MATCHMANAGEMENT_GRPC_URL: 'crictracker-matchmanagement-dev-grpc.dev.svc.cluster.local:80'


  GLOBAL_WIDGET_GRPC_URL: '0.0.0.0:3006'