# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: crictracker-elk
#   namespace: monitoring
#   annotations:
#     kubernetes.io/ingress.class: alb

#     alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true,idle_timeout.timeout_seconds=58
#     alb.ingress.kubernetes.io/healthcheck-interval-seconds: '14'
#     alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '8'
#     alb.ingress.kubernetes.io/healthy-threshold-count: '3'
#     alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
#     #alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=58
#     #alb.ingress.kubernetes.io/target-group-attributes: slow_start.duration_seconds=30
#     alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=70,slow_start.duration_seconds=30
    
#     alb.ingress.kubernetes.io/group.name: crictracker-devstag-new
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/backend-protocol: HTTP
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:693583001687:certificate/a98e8d06-f891-4338-9143-1220fa55592c
#     alb.ingress.kubernetes.io/subnets: subnet-077b67cb6983824ae, subnet-079a2bebf229cbae2
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
#     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
#     external-dns.alpha.kubernetes.io/hostname: elk.beta.crictracker.com
#     alb.ingress.kubernetes.io/auth-type: cognito
#     alb.ingress.kubernetes.io/auth-scope: openid
#     alb.ingress.kubernetes.io/auth-session-timeout: '3600'
#     alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
#     alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
#     alb.ingress.kubernetes.io/auth-idp-cognito: '{"userPoolARN":"arn:aws:cognito-idp:ap-south-1:693583001687:userpool/ap-south-1_Zmmm52Vqo","userPoolClientID":"3744l6m6tj927vlpqnf8o37kfm","userPoolDomain":"elkfw"}'

# spec:
#   rules:
#     - host: elk.beta.crictracker.com
#       http:
#         paths:
#           - path: /*
#             backend:
#               serviceName: ssl-redirect
#               servicePort: use-annotation
#           - path: /*
#             backend:
#               serviceName: kibana-kibana
#               servicePort: 5601