kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  PORT: "4009"
  CONNECTION: "20"
  REDIS_HOST: "crictracker-redis-local-dev-headless.local-dev.svc.cluster.local"
  REDIS_PORT: "6379"
  JWT_VALIDITY: '1800d'
  IS_API_RATE_LIMITER_ENABLED: "true"
  SEO_GRPC_URL: "crictracker-seo-local-dev-grpc.local-dev.svc.cluster.local:80"
  AUTH_GRPC_URL: "crictracker-authentication-local-dev-grpc.local-dev.svc.cluster.local:80"
  FEED_TITLE: "CricTracker"
  FEED_DESCRIPTION: "Latest Cricket News, Updates, Articles, Stats, Records, Etc"
  FRONTEND_URL: "https://cricweb-dev.crictracker.ml/"
  S3_CDN_URL: "https://admin-media-cdn.crictracker.com/"
  LOGIN_HARD_LIMIT_CLIENT: "5"
  JWT_LOGIN_VALIDITY: "1800d"
  JWT_VERIFICATION_VALIDITY: "600s"
  POSTMARK_SERVER_CLIENT: "6bb99394-914b-4f7d-a289-71c2849b45c7"
  SMTP_FROM: "CricTracker support@crictracker.com"
  SMTP_PRODUCT_URL: "https://cricweb-dev.crictracker.ml/"
  SMTP_PRODUCT_NAME: "CricTracker"
  SMTP_SUPPORT_EMAIL: "support@crictracker.com"
  FEED_BASE_URL: "https://feed-dev.crictracker.ml/"
  FEED_GRPC_URL: "0.0.0.0:3009"