apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: crictracker-redis-dev-service
spec:
  selector:
    app: crictracker-redis-dev
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}