apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crictracker-redis-dev-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistance.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistance.size }}
