export const WISH_LIST_ASSET = 'WISH_LIST_ASSET'
export const CLEAR_WISH_LIST_ASSET_RESPONSE = 'CLEAR_WISH_LIST_ASSET_RESPONSE'

export const REMOVE_WISH_LIST_ASSET = 'REMOVE_WISH_LIST_ASSET'
export const CLEAR_REMOVE_WISH_LIST_ASSET_RESPONSE = 'CLEAR_REMOVE_WISH_LIST_ASSET_RESPONSE'

export const GET_WISH_LIST_ASSETS = 'GET_WISH_LIST_ASSETS'
export const CLEAR_GET_WISH_LIST_ASSETS_RESPONSE = 'CLEAR_GET_WISH_LIST_ASSETS_RESPONSE'
