export const GET_CARD = 'GET_CARD'
export const CLEAR_GET_CARD_RESPONSE = 'CLEAR_GET_CARDS_RESPONSE'

export const UPDATE_CARD = 'UPDATE_CARD'
export const CLEAR_UPDATE_CARD_RESPONSE = 'CLEAR_UPDATE_CARD_RESPONSE'

export const DELETE_CARD = 'DELETE_CARD'
export const CLEAR_DELETE_CARD_RESPONSE = 'CLEAR_DELETE_CARD_RESPONSE'

export const ADD_CARD = 'ADD_CARD'
export const CLEAR_ADD_CARD_RESPONSE = 'CLEAR_ADD_CARD_RESPONSE'
