kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: "redis-cache.crictracker.com.private"
  REDIS_PORT: "6379"
  NODE_ENV: prod
  PORT: "4007"
  SUPPORT_EMAIL: 'Crictracker@yudizproject.tk'
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: 'media.crictracker.com'
  S3_BUCKET_URL: 'https://media.crictracker.com.s3.ap-south-1.amazonaws.com/'
  S3_BUCKET_PROFILE_PATH: profile-pic/
  S3_BUCKET_KYC_PATH: kyc/pan/
  S3_BUCKET_FB_PATH: fb/
  S3_BUCKET_TWITTER_PATH: twitter/
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: media/featureimage
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: media/thumbnailimage
  S3_BUCKET_JOB_APPLY_CV_PATH: job/cv/
  # AUTH_SUBGRAPH_URL: 'https://auth.crictracker.com'
  AUTH_SUBGRAPH_URL: http://crictracker-authentication-prod-internal.production.svc.cluster.local
  SENTRY_DSN: 'https://c7afbdb451d74161b1929f2af68253ba@o992135.ingest.sentry.io/6073494'

  
  CONNECTION: '5'
