const enums = {
  supportedLanguage: ['English'],
  gender: ['M', 'F', 'O'],
  eventType: ['B', 'A'], // B =BIRTHDAY , A = ANNIVERSARIES
  trainerType: ['Personal', 'General'],
  userType: ['T', 'S'], // T = TRAINER , S = STAFF
  referUserType: ['T', 'S', 'C', 'O'], // T = TRAINER , S = STAFF , C = CUSTOMER , O = OTHER
  status: ['Y', 'N', 'D'],
  planType: ['A', 'C'], // A = ADMIN , C = CUSTOMER
  paymentStatus: ['C', 'P'], // C = COMPLETED , P = PENDING
  subscriptionStatus: ['Y', 'E', 'D', 'F'], // F =  FREEZED , E = EXPIRED , D = DELETED , Y = ACTIVE
  inquiryStatus: ['N', 'P', 'C', 'D', 'S'], // N = NEW , P = PENDING , C = CLOSE , D = DELETED , S = SUCCESS,
  operationType: ['C', 'U', 'D', 'R'], // C = CREATE , U = UPDATE , D = DELETE,
  maritalStatus: ['M', 'U'], // M = MARRIED , U = UNMARRIED,
  foodType: ['V', 'N', 'O'], // V =VEG , N = NON-VEG , O = OTHER
  questionCategory: ['M', 'D'], // M = MEDICAl ,D = DIET
  reportType: ['T'], // T = TRANSACTION REPORT
  operationName: {
    BRANCH_ADD: 'BRANCH_ADD',
    BRANCH_UPDATE: 'BRANCH_UPDATE',
    BRANCH_DELETE: 'BRANCH_DELETE',
    ADMIN_LOGIN: 'ADMIN_LOGIN',
    ADMIN_USER_ADD: 'ADMIN_USER_ADD',
    ADMIN_USER_UPDATE: 'ADMIN_USER_UPDATE',
    ADMIN_USER_DELETE: 'ADMIN_USER_DELETE',
    EMPLOYEE_ADD: 'EMPLOYEE_ADD',
    EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
    EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',
    CUSTOMER_ADD: 'CUSTOMER_ADD',
    CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
    CUSTOMER_DELETE: 'CUSTOMER_DELETE',
    INQUIRY_ADD: 'INQUIRY_ADD',
    INQUIRY_UPDATE: 'INQUIRY_UPDATE',
    INQUIRY_DELETE: 'INQUIRY_DELETE',
    TRANSACTION_ADD: 'TRANSACTION_ADD',
    TRANSACTION_UPDATE: 'TRANSACTION_UPDATE',
    TRANSACTION_DELETE: 'TRANSACTION_DELETE',
    SUBSCRIPTION_ADD: 'SUBSCRIPTION_ADD',
    SUBSCRIPTION_UPDATE: 'SUBSCRIPTION_UPDATE',
    SUBSCRIPTION_DELETE: 'SUBSCRIPTION_DELETE',
    SUBSCRIPTION_FREEZE: 'SUBSCRIPTION_FREEZE',
    SUBSCRIPTION_FREEZE_UPDATE: 'SUBSCRIPTION_FREEZE_UPDATE',
    SUBSCRIPTION_UNFREEZE: 'SUBSCRIPTION_UNFREEZE',
    EXERCISE_ADD: 'EXERCISE_ADD',
    EXERCISE_UPDATE: 'EXERCISE_UPDATE',
    EXERCISE_DELETE: 'EXERCISE_DELETE',
    WORKOUT_PLAN_ADD: 'WORKOUT_PLAN_ADD',
    WORKOUT_PLAN_UPDATE: 'WORKOUT_PLAN_UPDATE',
    WORKOUT_PLAN_DELETE: 'WORKOUT_PLAN_DELETE',
    WORKOUT_PLAN_DETAIL_ADD: 'WORKOUT_PLAN_DETAIL_ADD',
    WORKOUT_PLAN_DETAIL_UPDATE: 'WORKOUT_PLAN_DETAIL_UPDATE',
    MEAL_PLAN_ADD: 'MEAL_PLAN_ADD',
    MEAL_PLAN_UPDATE: 'MEAL_PLAN_UPDATE',
    MEAL_PLAN_DELETE: 'MEAL_PLAN_ADD',
    MEAL_PLAN_DETAIL_ADD: 'MEAL_PLAN_DETAIL_ADD',
    MEAL_PLAN_DETAIL_UPDATE: 'MEAL_PLAN_DETAIL_UPDATE',
    QUESTION_ADD: 'QUESTION_ADD',
    QUESTION_UPDATE: 'QUESTION_UPDATE',
    QUESTION_DELETE: 'QUESTION_DELETE',
    LIFECYCLE_HISTORY_UPDATE: 'LIFECYCLE_HISTORY_UPDATE',
    LIFECYCLE_HISTORY_ADD: 'LIFECYCLE_HISTORY_ADD',
    BATCH_SCHEDULE_ADD: 'BATCH_SCHEDULE_ADD',
    BATCH_SCHEDULE_UPDATE: 'BATCH_SCHEDULE_UPDATE',
    BATCH_SCHEDULE_DELETE: 'BATCH_SCHEDULE_DELETE',
    SETTING_ADD: 'SETTING_ADD',
    SETTING_UPDATE: 'SETTING_UPDATE'
  },
  operationCode: {
    CREATE: 'C',
    UPDATE: 'U',
    DELETE: 'D',
    READ: 'R'
  }
}

module.exports = enums
