replicaCount: 1
image: 693583001687.dkr.ecr.ap-south-1.amazonaws.com/crictracker-migrations-dev:latest
pullPolicy: Always

labels:
  tier: backend
  release: blue-green
  environment: development

namespace: dev

service:
  internaltype: ClusterIP
  internalport: 80
  type: NodePort
  port: 5001
  healthcheck: /api/ping

resources: 
  requests:
    memory: "200Mi"
    cpu: "200m"
  limits:
    memory: "400Mi"
    cpu: "400m"

livenessProbe:
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3
  initialDelaySeconds: 15
  timeoutSeconds: 30
readinessProbe:
  initialDelaySeconds: 15
  timeoutSeconds: 30
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: "1"
  maxReplicas: "5"
  targetCPU: "60"

#Because we are using our private docker registry deployed in Kubernetes if you are using AWS(ECR) than you can disable this.
imagePullSecrets:
  enabled: false
  name: regcred

tolerations:
  - key: env
    effect: "NoSchedule"
    operator: Equal
    value: spot
  - key: node.kubernetes.io/not-ready
    operator: "Exists"
    effect: NoExecute
    tolerationSeconds: 0  