export const CREATE_COMMUNITY = 'CREATE_COMMUNITY'
export const CLEAR_CREATE_COMMUNITY_RESPONSE = 'CLEAR_CREATE_COMMUNITY_RESPONSE'

export const GET_MY_COMMUNITIES = 'GET_MY_COMMUNITIES'
export const CLEAR_GET_MY_COMMUNITIES_RESPONSE = 'CLEAR_GET_MY_COMMUNITIES_RESPONSE'

export const GET_COMMUNITY_DETAILS = 'GET_COMMUNITY_DETAILS'
export const CLEAR_GET_COMMUNITY_DETAILS_RESPONSE = 'CLEAR_GET_COMMUNITY_DETAILS_RESPONSE'

export const UPDATE_COMMUNITY = 'UPDATE_COMMUNITY'
export const CLEAR_UPDATE_COMMUNITY_RESPONSE = 'CLEAR_UPDATE_COMMUNITY_RESPONSE'

export const GET_ALL_COMMUNITIES = 'GET_ALL_COMMUNITIES'
export const CLEAR_GET_ALL_COMMUNITIES_RESPONSE = 'CLEAR_GET_ALL_COMMUNITIES_RESPONSE'

export const GET_POPULAR_COMMUNITIES = 'GET_POPULAR_COMMUNITIES'
export const CLEAR_GET_POPULAR_COMMUNITIES_RESPONSE = 'CLEAR_GET_POPULAR_COMMUNITIES_RESPONSE'
