kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: "redis-cache.crictracker.com.private"
  REDIS_PORT: "6379"
  NODE_ENV: prod
  PORT: "4001"
  SUPPORT_EMAIL: 'crictracker@yudizproject.tk'
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: 'media.crictracker.com'
  S3_BUCKET_URL: 'https://media.crictracker.com.s3.ap-south-1.amazonaws.com/'
  S3_BUCKET_PROFILE_PATH: profile-pic/
  S3_BUCKET_KYC_PATH: kyc/pan/
  S3_BUCKET_FB_PATH: fb/
  S3_BUCKET_TWITTER_PATH: twitter/
  S3_BUCKET_ARTICLE_FEATUREIMAGE_PATH: media/featureimage/
  S3_BUCKET_ARTICLE_THUMBIMAGE_PATH: media/thumbnailimage/
  S3_BUCKET_ARTICLE_CHAT_MEDIA_PATH: media/chatmedia/
  S3_BUCKET_ARTICLE_EDITOR_MEDIA_PATH: media/editorimage
  S3_BUCKET_TEAM_PATH: 'team/'
  S3_BUCKET_PLAYER_PATH: 'player/'
  S3_BUCKET_CATEGORY_PATH: 'category/' 
  SEO_STATUS_CHANGE_EVENT: 'seo-status-change-event'
  SEO_STATUS_CHANGE_CONSUMER: 'seo-status-change-consumer'
  SEO_STATUS_CHANGE_GROUP: 'seo-status-change-group'
  SMTP_EMAIL: 'yudizmean@gmail.com'
  SENTRY_DSN: 'https://c7afbdb451d74161b1929f2af68253ba@o992135.ingest.sentry.io/6073494'

  CONNECTION: '10' 
  BASE_SITEMAP: 'sitemap'
  POST_SITEMAP: 'post-sitemap'
  CATEGORY_SITEMAP: 'category-sitemap'
  POST_TAG_SITEMAP: 'post_tag-sitemap'
  AUTHOR_SITEMAP: 'author-sitemap'
  SITEMAP_REDIS_KEY: 'sitemap'

  SITEMAP_SLUG_EVENT: 'sitemap-slug-event'
  SITEMAP_SLUG_CONSUMER: 'sitemap-slug-consumer'
  SITEMAP_SLUG_GROUP: 'sitemap-slug-group'
  SITEMAP_ID_EVENT: 'sitemap-id-event'
  SITEMAP_ID_CONSUMER: 'sitemap-id-consumer'
  SITEMAP_ID_GROUP: 'sitemap-id-group'
  
  POSTMARK_SERVER_CLIENT: '6bb99394-914b-4f7d-a289-71c2849b45c7'
  ISAPIRATELIMITERENABLED: 'true'

  SEO_GRPC_URL: 'crictracker-seo-prod-grpc.production.svc.cluster.local:80'
  AUTH_GRPC_URL: '0.0.0.0:3001'