apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  requirements:
    - key: karpenter.sh/capacity-type         # optional, set to on-demand by default, spot if both are listed
      operator: In
      values: ["on-demand"]
    - key: "kubernetes.io/arch" # If not included, the webhook for the AWS Cloud Provider will default to amd64
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m6a.large", "m6a.xlarge", "m6a.2xlarge"]
  limits:
    resources:
      cpu: 1000                             # optional, recommended to limit total provisioned CPUs
      memory: 1000Gi
  provider:
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3                                    # optional, recommended to use instead of `provider`
    securityGroupSelector:
      aws-ids: "sg-01dab676c50ef46f2"
    subnetSelector:
      aws-ids: "subnet-09e12eb496c2fad91,subnet-0542e89a8e4d3a2ad"
  # ttlSecondsAfterEmpty: 30                    # optional, but never scales down if not set
  ttlSecondsUntilExpired: 2592000
  # blockDeviceMappings:
  #   - deviceName: /dev/xvda
  #     ebs:
  #       volumeSize: 50Gi
  #       volumeType: gp3
        # iops: 10000
        # encrypted: true
        # kmsKeyID: "arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab"
        # deleteOnTermination: true
        # throughput: 125
        # snapshotID: snap-0123456789
