apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dump-article
  namespace: dev
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - 'curl -X PUT https://migrations-dev.beta.crictracker.com/api/article/dump-article'       
            image: curlimages/curl
            name: dump-article
          restartPolicy: OnFailure