export const CLEAR_CATEGORY_RESPONSE = 'CLEAR_CATEGORY_RESPONSE'
export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA'

export const CLEAR_CATEGORY_DELETE_RESPONSE = 'CLEAR_CATEGORY_DELETE_RESPONSE'
export const DELETE_CATEGORY_DATA = 'DELETE_CATEGORY_DATA'
