from django.urls import path
from admin_flow import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   path('', views.index, name='index'),
   path('login', views.login, name='login'),
   path('logout', views.logout, name='logout'),
   path('forgot-password', views.forgot_password, name='forgot-password'),
   path('verify-token', views.verify_token, name='verify-token'),
   path('reset-password', views.reset_password, name='reset-password'),
   path('my-account', views.my_account, name='my-account'),
   path('edit-profile', views.edit_profile, name='edit-profile'),
   path('change-password', views.change_password, name='change-password'),
   path('customer-management', views.customer_management, name='customer-management'),
   path("update-user-status/<int:id>", views.update_user_status, name="update-user-status"),
   path("delete-user/<int:id>", views.delete_user, name="delete-user"),
   path("customer-detail/<int:id>", views.customer_detail, name="customer-detail"),
   path('activity-management', views.activity_management, name='activity-management'),
   path("delete-activity/<int:id>", views.delete_activity, name="delete-activity"),
   path("update-activity-status/<int:id>", views.update_activity_status, name="update-activity-status"),
   path("activity-detail/<int:id>", views.activity_detail, name="activity-detail"),
   path("faq", views.faq, name="faq"),
   path("delete-faq/<int:id>", views.delete_faq, name="delete-faq"),
   path("edit-faq/<int:id>", views.edit_faq, name="edit-faq"),
   path("add-faq", views.add_faq, name="add-faq"),
   path("faq-detail/<int:id>", views.faq_detail, name="faq-detail"),
   path("cms", views.cms, name="cms"),
   path("edit-about-us", views.edit_about_us, name="edit-about-us"),
   path("view-about-us", views.view_about_us, name="view-about-us"),
   path("edit-term-and-condition", views.edit_term_and_condition, name="edit-term-and-condition"),
   path("view-term-and-condition", views.view_term_and_condition, name="view-term-and-condition"),
   path("edit-privacy-policy", views.edit_privacy_policy, name="edit-privacy-policy"),
   path("view-privacy-policy", views.view_privacy_policy, name="view-privacy-policy"),
   path("media-gallary", views.media_gallary, name="media-gallary"),
   path("delete-media/<int:id>", views.delete_media, name="delete-media"),
   path("save-media", views.save_media, name="save-media"),
   path("delete-multiple-faqs", views.delete_multiple_faqs, name="delete-multiple-faqs"),
   path("delete-multiple-users", views.delete_multiple_users, name="delete-multiple-users"),
   path("delete-multiple-activities", views.delete_multiple_activities, name="delete-multiple-activities"),
   path("delete-multiple-media", views.delete_multiple_media, name="delete-multiple-media"),
   path("upload-media", views.upload_media, name="upload-media"),
   path("upload-activity-image", views.upload_activity_image, name="upload-activity-image"),
   path("link-activity-image", views.link_media_image_to_activity, name="link-activity-image")
]
