<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer
 */
/** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer */
?>

<?php $_item = $block->getItem() ?>
<?php $items = $block->getChildren($_item); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>
<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $_objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $_item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item):
    /**
     * @var $_item \Magento\Sales\Model\Order\Creditmemo\Item
     */

    ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product">
                <div class="option-label"><?= /* @escapeNotVerified */
                    $attributes['option_label'] ?></div>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
        <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif; ?>
<?php endif; ?>
    <tr<?= (++$_index == $_count && !$_showlastRow) ? ' class="border"' : '' ?>>
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
            <td class="col-product">
                <div class="product-title"><?= $block->escapeHtml($_item->getName()) ?></div>
                <div class="product-sku-block">
                    <span><?= /* @escapeNotVerified */
                        __('SKU') ?>:</span>
                    <?= implode('<br />',
                        $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))) ?>
                </div>
            </td>
        <?php else: ?>
            <td class="col-product">
                <div class="option-value"><?= $block->getValueHtml($_item) ?></div>
            </td>
        <?php endif; ?>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'price') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */
                $_item->getQty() * 1 ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'subtotal') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax">
            <?php
            if (($block->canShowPriceInfo($_item))) {
                $priceHelper = $_objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
                if ($_item->getOrderItem()->getGstExclusive()) {
                    $taxableAmount = $_item->getRowTotal();
                    $_item->setRowTotal(round($taxableAmount ? $taxableAmount : 0, 2) +
                        round($_item->getOrderItem()->getCgstAmount() ? $_item->getOrderItem()->getCgstAmount() : 0, 2) +
                        round($_item->getOrderItem()->getSgstAmount() ? $_item->getOrderItem()->getSgstAmount() : 0, 2) +
                        round($_item->getOrderItem()->getIgstAmount() ? $_item->getOrderItem()->getIgstAmount() : 0, 2) +
                        round($_item->getOrderItem()->getUtgstAmount() ? $_item->getOrderItem()->getUtgstAmount() : 0, 2));
                } else {
                    $taxableAmount = round($_item->getRowTotal() ? $_item->getRowTotal() : 0, 2) -
                        round($_item->getOrderItem()->getCgstAmount() ? $_item->getOrderItem()->getCgstAmount() : 0, 2) -
                        round($_item->getOrderItem()->getSgstAmount() ? $_item->getOrderItem()->getSgstAmount() : 0, 2) -
                        round($_item->getOrderItem()->getIgstAmount() ? $_item->getOrderItem()->getIgstAmount() : 0, 2) -
                        round($_item->getOrderItem()->getUtgstAmount() ? $_item->getOrderItem()->getUtgstAmount() : 0, 2);
                }

                $formattedPrice = $priceHelper->currency($taxableAmount, true, false);
                echo $formattedPrice;
            }
            ?>
        </td>
        <td class="col-discount">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */
                $block->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <?php if (($_item->getOrderItem()->getParentItem())) : ?>
            <td class="col-price" data-th="<?php echo $block->escapeHtml(__('CGST')); ?>">
                <table class="sgst">
                    <tbody style="background:none;text-align:center">
                    <tr>
                        <td style="text-align: center;width: 50px;"><?php echo round($_item->getOrderItem()->getData('cgst_percent') ? $_item->getOrderItem()->getData('cgst_percent') : 0,
                                2); ?></span></td>
                        <td style="text-align: center;width: 50px;">
                            <?php
                            $formattedPrice = $priceHelper->currency($_item->getOrderItem()->getData('cgst_amount'),
                                true, false);
                            echo $formattedPrice;
                            ?>
                        </td>
                    </tr>
                </table>
            </td>
            <?php
            $sgstUtgstPercent = 0;
            $sgstUtgstAmount = 0;
            if ($_item->getOrderItem()->getSgstPercent() > 0) {
                $sgstUtgstPercent = $_item->getOrderItem()->getSgstPercent();
                $sgstUtgstAmount = $_item->getOrderItem()->getData('sgst_amount');
                $amountString = 'sgst_amount';
            } else {
                $sgstUtgstPercent = $_item->getOrderItem()->getUtgstPercent();
                $sgstUtgstAmount = $_item->getOrderItem()->getData('utgst_amount');
                $amountString = 'utgst_amount';
            }
            ?>

            <td class="col-price" data-th="<?php echo $block->escapeHtml(__('SGST')); ?>">
                <table class="sgst">
                    <tbody style="background:none;text-align:center">
                    <tr>
                        <td style="text-align: center;width: 50px;"><?php echo round($sgstUtgstPercent,
                                2); ?></span></td>
                        <td style="text-align: center;width: 50px;">
                            <?php
                            if ($_item->getOrderItem()->getData('product_type') == 'configurable') {
                                $item_id = $_item->getOrderItem()->getData('item_id');
                                $item = $_objectManager->get('Magento\Sales\Model\Order\Item')->getCollection();
                                $item->addFieldToFilter('parent_item_id', $item_id);
                                foreach ($item as $value) {
                                    $formattedPrice = $priceHelper->currency($value->getData($amountString), true,
                                        false);
                                    echo $formattedPrice;
                                }
                            } else {
                                $formattedPrice = $priceHelper->currency($sgstUtgstAmount, true, false);
                                echo $formattedPrice;
                            }
                            ?>
                        </td>
                    </tr>
                </table>
            </td>
            <td class="col-price" data-th="<?php echo $block->escapeHtml(__('IGST')); ?>">
                <table class="igst">
                    <tbody style="background:none;text-align:center">
                    <tr>
                        <td style="text-align: center;width: 50px;"><?php echo round($_item->getOrderItem()->getData('igst_percent') ? $_item->getOrderItem()->getData('igst_percent') : 0,
                                2); ?></span></td>
                        <td style="text-align: center;width: 50px;">
                            <?php
                            if ($_item->getOrderItem()->getData('product_type') == 'configurable') {
                                $item_id = $_item->getOrderItem()->getData('item_id');
                                $item = $_objectManager->get('Magento\Sales\Model\Order\Item')->getCollection();
                                $item->addFieldToFilter('parent_item_id', $item_id);
                                foreach ($item as $value) {
                                    $formattedPrice = $priceHelper->currency($value->getData('igst_amount'), true,
                                        false);
                                    echo $formattedPrice;
                                }
                            } else {
                                $formattedPrice = $priceHelper->currency($_item->getOrderItem()->getData('igst_amount'),
                                    true, false);
                                echo $formattedPrice;
                            }
                            ?>
                        </td>
                    </tr>
                </table>
            </td>
        <?php endif; ?>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'total') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($block->getOrderOptions() as $option): ?>
                        <dt><?= /* @escapeNotVerified */
                            $option['label'] ?></dt>
                        <dd>
                            <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                                <?= /* @escapeNotVerified */
                                $option['value'] ?>
                            <?php else: ?>
                                <?= $block->truncateString($option['value'], 55, '', $_remainder) ?>
                                <?php if ($_remainder): ?>
                                    ... <span id="<?= /* @escapeNotVerified */
                                    $_id = 'id' . uniqid() ?>"><?= /* @escapeNotVerified */
                                        $_remainder ?></span>
                                    <script>
                                        require(['prototype'], function () {

                                            $('<?= /* @escapeNotVerified */ $_id ?>').hide();
                                            $('<?= /* @escapeNotVerified */ $_id ?>').up().observe('mouseover', function () {
                                                $('<?= /* @escapeNotVerified */ $_id ?>').show();
                                            });
                                            $('<?= /* @escapeNotVerified */ $_id ?>').up().observe('mouseout', function () {
                                                $('<?= /* @escapeNotVerified */ $_id ?>').hide();
                                            });

                                        });
                                    </script>
                                <?php endif; ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($block->getItem()->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
