# Generated by Django 3.2.18 on 2023-03-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_flow', '0018_alter_userprofile_relationship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('thumbnail_image', models.CharField(blank=True, max_length=200)),
                ('activity_type', models.CharField(choices=[('restaurant', 'restaurant'), ('activity', 'activity')], default='activity', max_length=30)),
                ('activity_feeling', models.CharField(choices=[('adventurous', 'adventurous'), ('sporty', 'sporty'), ('relaxing', 'relaxing'), ('family_friendly', 'family_friendly')], default='sporty', max_length=30)),
                ('activity_start_time', models.TimeField()),
                ('activity_end_time', models.TimeField()),
                ('activity_amount', models.FloatField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('is_restaurant', models.BooleanField(default=False)),
                ('favourite', models.ManyToManyField(blank=True, to='user_flow.User')),
            ],
        ),
    ]
