# Generated by Django 3.2.18 on 2023-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_remove_activity_is_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'single'), ('relationship', 'relationship'), ('parents', 'parents')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='resident_permit',
            field=models.CharField(choices=[('resident', 'resident'), ('tourist', 'tourist')], default='resident', max_length=10),
        ),
    ]
