# Generated by Django 3.2.18 on 2023-03-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0003_auto_20230307_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_feeling',
            new_name='activity_mood',
        ),
    ]
