# Generated by Django 3.2.18 on 2023-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0004_rename_activity_feeling_activity_activity_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='relationship_status',
            field=models.CharField(choices=[('single', 'single'), ('relationship', 'relationship'), ('parents', 'parents'), ('any', 'any')], default='any', max_length=20),
        ),
    ]
