# Generated by Django 3.2.18 on 2023-03-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_alter_activity_relationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active_all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_start_time',
            field=models.TimeField(null=True),
        ),
    ]
