# Generated by Django 3.2.18 on 2023-03-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0007_alter_activity_resident_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
