# Generated by Django 3.2.18 on 2023-03-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0021_alter_userchoicepreference_user_time'),
        ('common_app', '0008_activity_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common_app.activity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_flow.user')),
            ],
        ),
    ]
