# Generated by Django 3.2.18 on 2023-03-13 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0009_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 8, 54, 1, 906735)),
            preserve_default=False,
        ),
    ]
