# Generated by Django 3.2.18 on 2023-03-14 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0011_auto_20230313_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='start_time',
            field=models.TimeField(default=datetime.time(13, 19, 55, 77965)),
            preserve_default=False,
        ),
    ]
