# Generated by Django 3.2.18 on 2023-03-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0013_useractivity_active_all_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
