# Generated by Django 3.2.18 on 2023-03-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0014_activity_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='active_status',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='activity_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
