# Generated by Django 3.2.18 on 2023-03-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0016_activity_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=100)),
                ('answer', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
