# Generated by Django 3.2.18 on 2023-03-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0017_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True)),
                ('about_us_img', models.TextField(blank=True)),
                ('term_and_conditions', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
            ],
        ),
    ]
