# Generated by Django 3.2.18 on 2023-03-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0018_cms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cms',
            old_name='term_and_conditions',
            new_name='term_and_condition',
        ),
    ]
