# Generated by Django 3.2.18 on 2023-03-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0019_rename_term_and_conditions_cms_term_and_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TimeField(blank=True),
        ),
    ]
