# Generated by Django 3.2.18 on 2023-03-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0020_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
