# Generated by Django 3.2.18 on 2023-04-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_flow', '0031_auto_20230330_1039'),
        ('common_app', '0021_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, choices=[('acitivity_alert', 'acitivity_alert'), ('budget_update', 'budget_update'), ('recommandation', 'recommandation')], max_length=20)),
                ('push_status', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_flow.user')),
            ],
        ),
    ]
