# Generated by Django 3.2.18 on 2023-04-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0022_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='push_status',
        ),
    ]
