# Generated by Django 3.2.18 on 2023-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0023_remove_notification_push_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('activity_alert', 'activity_alert'), ('budget_update', 'budget_update'), ('recommandation', 'recommandation')], max_length=20),
        ),
    ]
