# Generated by Django 3.2.18 on 2023-04-05 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0024_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_activity',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='common_app.useractivity'),
            preserve_default=False,
        ),
    ]
