# Generated by Django 3.2.18 on 2023-04-05 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0025_notification_user_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 10, 28, 58, 595944)),
            preserve_default=False,
        ),
    ]
