# Generated by Django 3.2.18 on 2023-04-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0026_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.activity'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.useractivity'),
        ),
    ]
