# Generated by Django 3.2.18 on 2023-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0027_auto_20230406_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_mood',
            field=models.CharField(choices=[('adventurous', 'adventurous'), ('sporty', 'sporty'), ('relaxing', 'relaxing'), ('family_friendly', 'family_friendly'), ('any', 'any')], default='any', max_length=30),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
