# Generated by Django 3.2.18 on 2023-04-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0028_auto_20230413_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='activity_mood',
            field=models.CharField(choices=[('adventurous', 'adventurous'), ('sporty', 'sporty'), ('relaxing', 'relaxing'), ('family_friendly', 'family_friendly'), ('any', 'any')], default='any', max_length=30),
        ),
    ]
