# Generated by Django 3.2.18 on 2023-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0029_useractivity_activity_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='active_all_day',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_start_time',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='active_all_day',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_time',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='relationship_status',
            field=models.CharField(choices=[('S', 'single'), ('R', 'relationship'), ('P', 'parents'), ('SRP', 'single, relationship and parents'), ('RP', 'relationship and parents'), ('SP', 'single and parents'), ('SR', 'single and relationship')], default='SRP', max_length=20),
        ),
    ]
