# Generated by Django 3.2.18 on 2023-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0030_auto_20230424_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_mood',
            field=models.CharField(choices=[('ASFR', 'adventurous, sporty, family-friendly, and relaxing'), ('AS', 'adventurous and sporty'), ('AF', 'adventurous and family-friendly'), ('AR', 'adventurous and relaxing'), ('SF', 'sporty and family-friendly'), ('SR', 'sporty and relaxing'), ('FR', 'family-friendly and relaxing'), ('SFR', 'sporty, family-friendly, and relaxing'), ('AFR', 'adventurous, family-friendly, and relaxing'), ('ASR', 'adventurous, sporty, and relaxing'), ('ASF', 'adventurous, sporty, and family-friendly'), ('A', 'adventurous'), ('S', 'sporty'), ('F', 'family-friendly'), ('R', 'relaxing')], default='ASFR', max_length=30),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_mood',
            field=models.CharField(choices=[('adventurous', 'adventurous'), ('sporty', 'sporty'), ('relaxing', 'relaxing'), ('family_friendly', 'family-friendly')], default='any', max_length=30),
        ),
    ]
