# Generated by Django 3.2.18 on 2023-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0031_auto_20230519_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='age_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
