# Generated by Django 3.2.18 on 2023-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0032_activity_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='booking_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='google_map',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='group_amount',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='restaurant_menu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='restaurant_type',
            field=models.CharField(blank=True, choices=[('Walk-in', 'Walk-in'), ('Reservation', 'Reservation')], max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='thumbnail_image_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='thumbnail_image',
            field=models.TextField(blank=True),
        ),
    ]
