# Generated by Django 3.2.18 on 2023-06-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0033_auto_20230612_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='google_map',
        ),
    ]
