export const NETWORKS = {
  ETHEREUM: 'Ethereum',
  POLYGON: 'Polygon',
  SOLANA: 'Solana'
}

export const NFT_CONTRACT_ADDRESS = {}
NFT_CONTRACT_ADDRESS[NETWORKS.ETHEREUM] = process.env.REACT_APP_ETHEREUM_NFT_CONTRACT_ADDRESS
NFT_CONTRACT_ADDRESS[NETWORKS.POLYGON] = process.env.REACT_APP_POLYGON_NFT_CONTRACT_ADDRESS

export const AUCTION_CONTRACT_ADDRESS = {}
AUCTION_CONTRACT_ADDRESS[NETWORKS.ETHEREUM] = process.env.REACT_APP_ETHEREUM_AUCTION_CONTRACT_ADDRESS
AUCTION_CONTRACT_ADDRESS[NETWORKS.POLYGON] = process.env.REACT_APP_POLYGON_AUCTION_CONTRACT_ADDRES

export const PAYOUT_CONTRACT_ADDRESS = {}
PAYOUT_CONTRACT_ADDRESS[NETWORKS.ETHEREUM] = process.env.REACT_APP_ETHEREUM_PAYOUT_CONTRACT_ADDRESS
PAYOUT_CONTRACT_ADDRESS[NETWORKS.POLYGON] = process.env.REACT_APP_POLYGON_PAYOUT_CONTRACT_ADDRESS

export const CHAIN_ID = {}
CHAIN_ID[NETWORKS.ETHEREUM] = process.env.REACT_APP_ETHEREUM_CHAIN_ID
CHAIN_ID[NETWORKS.POLYGON] = process.env.REACT_APP_POLYGON_CHAIN_ID

export const CHAIN_NAME = {}
CHAIN_NAME[NETWORKS.ETHEREUM] = process.env.REACT_APP_ETHEREUM_CHAIN_NAME
CHAIN_NAME[NETWORKS.POLYGON] = process.env.REACT_APP_POLYGON_CHAIN_NAME

export const RPC_URL = {}
RPC_URL[NETWORKS.ETHEREUM] = process.env.REACT_APP_ETHEREUM_RPC
RPC_URL[NETWORKS.POLYGON] = process.env.REACT_APP_POLYGON_RPC
