apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: redis-to-video
  namespace: production
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -ec
            - 'curl -X GET https://article.crictracker.com/api/viewcount/redis-to-video'
            image: curlimages/curl
            name: redis-to-video
          restartPolicy: OnFailure